### PR TITLE
DCOS-11781: fix scroll view not set correctly in packages table

### PR DESCRIPTION
**Pull request by mlunoe**
This PR fixes so the bottom packages in the table are always visible:

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [x] Did you add new integration tests?
- [x] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by mlunoe** [comment]
🤔 The test that I added is failing.. Need to look into that

**Comment by orlandohohmeier** [comment]
@mlunoe please open a PR to back-port the fix once the test pass.

**Comment by mlunoe** [comment]
Update:
This is needed for this fix to work: https://github.com/mesosphere/reactjs-components/pull/398

**Comment by mlunoe** [comment]
Yes @orlandohohmeier, that's why I added the label for my self to remember

**Comment by nLight** [comment]
run integration tests

**Comment by mlunoe** [comment]
The tests are actually failing. I need this PR  mesosphere/reactjs-components#398 to merge, add it to this before they will pass.

**Comment by mlunoe** [comment]
Rebased!

**Comment by jfurrow** [comment]
Good work, let's do it!

**Pull request merged**
