### PR TITLE
fix(Systemintegrationtest): Adjusted tests

### PR DESCRIPTION
**Pull request by Poltergeist**
Adjusted System integration tests to fulfil the
new network API

**Checklist**
- [ ] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [x] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by weblancaster** [comment]
@Poltergeist there is one SI test failing https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/public-dcos-ui-pulls-integration/4890/console

**Comment by orlandohohmeier** [comment]
@Poltergeist could you please rebase this one?

**Comment by Poltergeist** [comment]
@orlandohohmeier This is rebased now.

**Comment by orlandohohmeier** [comment]
Please note that I've change the base to `master` as we've merged `integrate/marathon-1.5` last week...

**Comment by jfurrow** [comment]
The following tests are failing for me, is this expected?
```
✘ Services Applications should create an app with command health check
✘ Services Applications should create an app with docker config
✘ Services Applications should create an app with external volume
✘ Services Applications should create an app with HTTP health check
✘ Services Applications should create an app with persistent volume
```

**Comment by ahoskins** [comment]
After I merged #2283 fixing the apps tests, this PR is no longer needed. Any objections to closing this?

**Pull request closed without merging**
