### PR TITLE
Tooltips created from schema stay open

### PR DESCRIPTION
**Pull request by kennyt**
px

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @jfurrow

**Comment by pierlo-upitup** [comment]
That's on purpose so we can add links in there... or am I missing something?

**Comment by pierlo-upitup** [comment]
Duh the title of the PR made it sound like this was an issue. Gotcha :)

**Comment by orlandohohmeier** [comment]
tooltip

@kennyt Cod looks good, but it's not working for me. Could you please double check?

**Comment by kennyt** [comment]
@orlandohohmeier hmm that's weird. it wasn't staying open for me like your gif, but then a little while later it started working... don't know what to say

**Comment by jfurrow** [comment]
This works for me, @orlandohohmeier can you verify that the `interactive` prop is set to `true`?

**Comment by orlandohohmeier** [comment]
I've retested this and it works like charm – I probably ran into a caching issue or something similar.

**Pull request merged**
