### PR TITLE
Change service modal styling

### PR DESCRIPTION
**Pull request by Poltergeist**
image

This changes the header of the service form modal to look a bit more welcoming and also now the header includes the JSON toggle button.

Fix for the react warning is PR'ed at mesosphere/reactjs-components#286

Contains #409 [~~unmerged~~merged]

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @mlunoe

**Comment by pierlo-upitup** [comment]
LGTM besides the `hold merge`

**Comment by Poltergeist** [comment]
It is dependent on #409 that's why the hold merge is there.

**Comment by Poltergeist** [comment]
retest this please

**Comment by pierlo-upitup** [comment]
retest this please

**Comment by philipnrmn** [comment]
retest this please

**Comment by pierlo-upitup** [comment]
@leemunroe is the header actually supposed to be purple?

**Comment by pierlo-upitup** [comment]
Can you also fix the typo in the heading? `Sevrice`

**Comment by leemunroe** [comment]
Negative. Latest design direction we're going for modal headers is white.

https://invis.io/7T6QREYAE

For example

image

**Comment by pierlo-upitup** [comment]
Also this is what I see: (notice the padding difference):

image

**Comment by pierlo-upitup** [comment]
Please refer to the Universe modal for a design reference: 
image

**Comment by pierlo-upitup** [comment]
@Poltergeist sorry for the intrusion, let me know if you're OK with my changes to the code. What I've done gives us the following:

image


which gives us a more consistent look & feel with the already existing Universe modal:

image


cc @orlandohohmeier for the upcoming work on the jobs page
cc @leemunroe for a 👀 check

**Comment by pierlo-upitup** [comment]
@leemunroe just to clarify what this achieves:


image


please notice that the inside of the form is what's going out of boundaries – I think the fix there needs to happen across all modal forms so let's keep that out of this PR

**Comment by pierlo-upitup** [comment]
@mesosphere-ci retest this please

**Comment by pierlo-upitup** [comment]
**mesosphere-ci** retest this please

**Comment by Poltergeist** [comment]
@pierlo-upitup I am fine with you changes. It looks good.

**Comment by orlandohohmeier** [comment]
**mesosphere-ci** retest this please

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Comment by Poltergeist** [comment]
image
**mesosphere-ci** retest this please

**Comment by pierlo-upitup** [comment]
**mesosphere-ci** retest this please

**Pull request merged**
