### PR TITLE
Add stub for queue endpoint used at TasksTable 

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
This might help with the flaky integration tests

### CODE REVIEW

**Comment by juliangieseke** [comment]
Alfred test this please :trollface: 
(✅  @ https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/1886/)

**Comment by DanielMSchmidt** [comment]
@juliangieseke was it green?

**Comment by juliangieseke** [comment]
yes, see the link in my comment 👍

**Comment by juliangieseke** [comment]
Alfred test this please :trollface: 
(Again ✅  @ https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/1889/)

Looks like you fixed it 👍

**Comment by DanielMSchmidt** [comment]
Alfred test this please
(⚠️ @ https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/1891/)

The test failed but due to something different (`shows anchored error when error in form section.Service Actions Edit Action shows anchored error when error in form section
`)

**Comment by DanielMSchmidt** [comment]
Alfred test this please
(⚠️ @ https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/1901/)

The test failed at the unit stage for some random error

**Comment by DanielMSchmidt** [comment]
Alfred test this please
(✅ @ https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/1902)

**Comment by DanielMSchmidt** [comment]
✅ @ https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/1909/

**Comment by DanielMSchmidt** [comment]
Alfred test this please

**Comment by DanielMSchmidt** [comment]
@juliangieseke @nLight Seems like the flackines of this particular test is gone, so I would like to declare this PR to be ready for review

**Pull request merged**
