### PR TITLE
DCOS-7627 Fix healthbar transform bug

### PR DESCRIPTION
**Pull request by Poltergeist**
This fixes the issue in the image:
image

Images of the solution:

image

image

image

image

image

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @pierlo-upitup

**Comment by orlandohohmeier** [comment]
Let's please make sure this does not affect the node page bars... /cc @daiyiwhale

**Comment by Poltergeist** [comment]
This is true. I had a look at the nodes page and everything looked fine, as far as I can tell, but let's make sure that this works.

**Comment by orlandohohmeier** [comment]
LGTM 💯 ✨

**Pull request merged**
