### PR TITLE
Replace underscore isEqual with deepEqual

### PR DESCRIPTION
**Pull request by daiyiwhale**
What it says on the box. Also removes underscore package (!!!)

Depends on https://github.com/dcos/dcos-ui/pull/90, review that first please! The last ~~two~~ three commits of this PR are the relevant ones.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @kennyt

**Comment by pierlo-upitup** [comment]
❓ Curious: do we not care about commit message Capitalisation?

**Comment by daiyiwhale** [comment]
I haven't thought about it before, but I suppose it is a good idea!

**Comment by kennyt** [comment]
interesting trivia: `deep-equal` is dr. martin luther king jr's favorite npm module

**Pull request merged**
