### PR TITLE
Updated CNVS from 1.1.4 to 1.1.6

### PR DESCRIPTION
**Pull request by ashenden**
Double-check I did the shrinkwrap update correctly please.

Notable updates:
* Updated .button-flush with directional modifiers
* Fixed disabled buttons of type *-link
* Adjusted background of .form-control and .form-control-toggle
* Updated background style of .form-control style variants
* URI encode inline SVG strings
* Updated styling of `disabled` state for `form-control` component

Full diff here for reviewers: https://github.com/mesosphere/cnvs/compare/4e301e8951b74b7c4d6f959ef255651f7da6a11d...d2eb4d1477a0aab827071db210a7c638f9b3cc45

### CODE REVIEW

**Comment by ashenden** [comment]
I also put up a PR for reactjs-components - https://github.com/mesosphere/reactjs-components/pull/381

**Comment by mlunoe** [comment]
@ashenden Could you add details about what this CNVS update includes?

**Comment by ashenden** [comment]
@mlunoe comments added in description.

**Comment by mlunoe** [comment]
Added full diff to make it easier to review

**Comment by mlunoe** [comment]
We will need the same change as here: https://github.com/mesosphere/reactjs-components/pull/381#issuecomment-269245976

**Comment by jfurrow** [comment]
@mlunoe which change are you referring to with that link?

**Comment by mlunoe** [comment]
Sorry, wrong link. Here you go: https://github.com/mesosphere/reactjs-components/pull/381/commits/fe9f05e97257553e4470c7a3148a7f36904e5af0

**Comment by jfurrow** [comment]
@mlunoe I updated the classes, is that the only outsanding issue for this PR?

**Comment by mlunoe** [comment]
I have not tested it thoroughly, as I found it hard to check all the changes that have been made

**Comment by jfurrow** [comment]
@ashenden We still have the same problem with the value of disabled form fields as described in https://github.com/mesosphere/cnvs/issues/76. See the following screenshot:

**Pull request merged**
