### PR TITLE
perf: apply performance improving transformation

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
## Testing

All pages are affected, so a bit of smoke testing would be great

### CODE REVIEW

**Comment by mperrotti** [comment]
Unit tests are failing, but I tested some of the things it's failing for in the UI, and they seem to be fine. I tried Googling for others experiencing similar testing issues with this version of `babel-plugin-transform-react-constant-elements`, but couldn't find anything :/

**Comment by GeorgiSTodorov** [comment]
To me, it looks like it actually tries to create these components.
Example:
Screenshot from 2019-04-09 13-32-58

**Comment by GeorgiSTodorov** [comment]
I was able to get this particular test working by doing the before and after hooks as part of the test:
```
/* eslint-disable no-unused-vars */
const React = require("react");
/* eslint-enable no-unused-vars */
const ReactDOM = require("react-dom");

const ErrorModal = require("../ErrorModal");

const thisCallback = jasmine.createSpy();
const thisContainer = global.document.createElement("div");
const thisInstance = ReactDOM.render(
  <ErrorModal onClose={thisCallback} />,
  thisContainer
);

describe("ErrorModal", function() {
  describe("#onClose", function() {
    it("doesn't call the callback after initialization", function() {
      expect(thisCallback).not.toHaveBeenCalled();
      ReactDOM.unmountComponentAtNode(thisContainer);
    });

    it("calls the callback when #onClose is called", function() {
      thisInstance.onClose();
      expect(thisCallback).toHaveBeenCalled();
      ReactDOM.unmountComponentAtNode(thisContainer);
    });
  });
});

```

**Comment by GeorgiSTodorov** [comment]
I looked into another failing test (`SideTabs-test`) and I second my previous observation. It seems like beforeEach and afterEach don't work correctly.
```
/* eslint-disable no-unused-vars */
const React = require("react");
/* eslint-enable no-unused-vars */
const ReactDOM = require("react-dom");

const SideTabs = require("../SideTabs");

describe("SideTabs", function() {
  describe("#getTabs", function() {
    it("returns a list item for each tab", function() {
      let thisTabs, thisContainer, thisInstance;
      thisTabs = [{ title: "Application" }, { title: "Host" }];
      thisContainer = global.document.createElement("div");
      thisInstance = ReactDOM.render(
        <SideTabs selectedTab="Application" tabs={thisTabs} />,
        thisContainer
      );
      var node = ReactDOM.findDOMNode(thisInstance);
      var items = node.querySelectorAll("li");
      expect(items.length).toEqual(thisTabs.length);
      ReactDOM.unmountComponentAtNode(thisContainer);
    });

    it("renders the selected tab with the 'selected' class", function() {
      let thisTabs, thisContainer, thisInstance;
      thisTabs = [{ title: "Application" }, { title: "Host" }];
      thisContainer = global.document.createElement("div");
      thisInstance = ReactDOM.render(
        <SideTabs selectedTab="Application" tabs={thisTabs} />,
        thisContainer
      );
      var node = ReactDOM.findDOMNode(thisInstance);
      var selectedTab = node.querySelector(".selected");

      expect(selectedTab.textContent).toEqual("Application");
      ReactDOM.unmountComponentAtNode(thisContainer);
    });
  });
});
```
This works.

**Comment by pierrebeitz** [comment]
@DanielMSchmidt how could i measure that this is beneficial in our codebase?

**Comment by DanielMSchmidt** [comment]
In hindsight I think it might be a micro-optimization. It should have been measurable by a slightly lower rendering time for a couple of components, but working around our unit tests is not worth it, IMHO.

**Pull request closed without merging**
