### PR TITLE
show healthchecks with unknown values

### PR DESCRIPTION
**Pull request by Poltergeist**
~~BASED on #1670~~ Merged

Added support for healthchecks with unknown protocol in the ui. There might come design suggestion for this feature. With this PR it will be possible to delete healthchecks with unknown protocols from the form.

image

\cc @leemunroe

### CODE REVIEW

**Comment by Poltergeist** [comment]
Run integration tests

**Comment by nLight** [comment]
Rebased that one, otherwise plugins threw an exception.

**Comment by mlunoe** [comment]
Same error (as in the base PR) appears here:

**Comment by mlunoe** [comment]
Problem fixed in base PR, which merged.

**Pull request merged**
