### PR TITLE
Fixing icons for JohnF

### PR DESCRIPTION
**Pull request by ashenden**

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @philipnrmn

**Comment by jfurrow** [comment]
:ship:

**Comment by jfurrow** [comment]
I pushed a commit to put the SVG sprite in `index.html`.

**Comment by jfurrow** [comment]
retest this please

**Comment by rcorral** [comment]
@ashenden your tests are failing, maybe you should fix the tests.

**Comment by ashenden** [comment]
What's failing?  I just changed some icon .SVGs in the assets directory after pulling down `master`.

**Comment by jfurrow** [comment]
retest this pleae

**Comment by jfurrow** [comment]
retest this please

**Comment by rcorral** [comment]
Dude you gotta fix those tests.

**Comment by kennyt** [comment]
@ashenden please fix these tests ASAP

**Pull request merged**
