### PR TITLE
[wip] DCOS-11726: Replace DELETE links with crosses

### PR DESCRIPTION
**Pull request by nLight**
⚠️  WIP because it doesn't implement the hover state as proposed by Lee. Feel free to review/merge it if you don't think this functionality is crucial.

This PR replaces DELETE links with crosses

screen shot 2016-12-05 at 16 38 19

### CODE REVIEW

**Comment by mlunoe** [comment]
Looks good dude! Yeah, we should probably get a hover state for this, but that can go in separately. @jfurrow not sure if this would be quick for you to add?

**Comment by jfurrow** [comment]
@mlunoe Not sure what the proposed hover effect, but I did push a change that will inherit the hover effect from the `button-link` styles.

**Comment by jfurrow** [comment]
retest this please

**Comment by nLight** [comment]
You guys are amazing! ✨

**Pull request merged**
