### PR TITLE
DCOS-41503: show JSON parsing errors as top level errors

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
## Testing

Go to the Service form and open the JSON editor. Create invalid JSON. Admire the error message being shown on the left side and the review button not doing anything on click

## Trade-offs

- Decided against system tests, as this is a UI only issue IMHO

## Dependencies

None

## Screenshots

From 1.12:

bildschirmfoto 2018-09-07 um 15 03 02

### CODE REVIEW

**Comment by nLight** [comment]
@juliangieseke 1.10 integration test failure is due to CI adjustments. Gonna have a look and try fixing it today or just reverting the change.

**Comment by nLight** [comment]
@juliangieseke @DanielMSchmidt nope, looks like change I made yesterday is sufficient, integration tests should be good. The failure looks like a legit one.

**Comment by nLight** [comment]
@DanielMSchmidt tests are failing on 1.10 branch. 1.9 unfortunately doesn't have integration tests on CI

**Comment by DanielMSchmidt** [comment]
So, this PR has nothing to do with it?

**Comment by nLight** [comment]
@DanielMSchmidt the concern is that if the same change fails on 1.10 it could probably not work on 1.9 as well

**Comment by DanielMSchmidt** [comment]
Oh, this is the 1.9 backport 🙈

**Pull request merged**
