### PR TITLE
Misc/services ui changes

### PR DESCRIPTION
**Pull request by pierlo-upitup**
Just some minor UI changes:

- Use `h4` instead of `h3` to fit the filter headline result text 
- Introduce placeholder buttons for Create Group / Deploy Service and make use of `FilterBar` to arrange them horizontally

bars

cc @leemunroe

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @rcorral

**Comment by kennyt** [comment]
tried it out. looks great

**Comment by philipnrmn** [comment]
Looks nice 👍

**Comment by leemunroe** [comment]
@pierlo-upitup Nice! One thing, I'm noticing a slight jump in the UI when it switches to results mode. Not sure why. But it's a bit jarring.

**Comment by pierlo-upitup** [comment]
@leemunroe yep the jump is there – I could fix this quick'n'dirty but I preferred to postpone this to later. 

Maybe @jfurrow can chime in on what could be a possible **good** solution that doesn't involve writing a bunch of unnecessary CSS fixes but that deals with Canvas UI `ul.h4` which is present in the FilterHeadline.

**Comment by mlunoe** [comment]
It seems that there is a difference in margin between heading and the field, which makes the whole content 'jump' up. That we should fix

**Pull request merged**
