### PR TITLE
VIPs in modal

### PR DESCRIPTION
**Pull request by philipnrmn**
This PR 
 - introduces VIP labels to portDefinitions in host mode
 - fixes the VIP labels in user mode (previously was always 0.0.0.0)
 - extends the user mode VIP labels to bridged mode

VIP labels are now constructed from the app ID and the specified port.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @mlunoe

**Comment by sargun** [comment]
Can you build a dcos/dcos cluster with this?

**Comment by philipnrmn** [comment]
I'm not sure how to do that I'm afraid.

**Comment by rcorral** [comment]
I can do that once you get the tests passing @philipnrmn

**Comment by philipnrmn** [comment]
retest this please

**Comment by rcorral** [comment]
merge when tests pass

**Pull request merged**
