### PR TITLE
DCOS-12974: Use smaller container icon

### PR DESCRIPTION
**Pull request by nLight**
⚠️ There's no green light to 24x24 icon, due to the time lag. Yet I like how it looks and think that this will be the decision. Anyways please check the discussion before hitting that merge button https://mesosphere.atlassian.net/browse/DCOS-12974

---

This PR 
1. adds margin between the network type dropbox and the header
2. reduces size of the container icon

Before:
screen shot 2017-01-19 at 10 44 44

After:
screen shot 2017-01-19 at 10 44 06

### CODE REVIEW

**Comment by nLight** [comment]
//cc @ashenden

**Comment by nLight** [comment]
retest this please

**Comment by nLight** [comment]
retest this please 😩

**Comment by wavesoft** [comment]
Discussion sounds reasonable. Looks good 👍  💯

**Comment by nLight** [comment]
run integration tests

**Comment by jfurrow** [comment]
Nice! 🚢

**Pull request merged**
