### PR TITLE
Refactor UserDropup

### PR DESCRIPTION
**Pull request by jfurrow**
This PR refactors the `UserDropup` component. We were using the `Modal` component to render the user account menu options. It also duplicated the heading for the component, and the animation wasn't very smooth. This PR addresses all of these issues.

This also addresses the `UserDropup` component living in more than one place. Now it exists as a regular component in DCOS UI and is exposed to plugins via the plugin SDK's `PluginModules` file.

The changed LOCs look worse than they really are, but it still may be a bit challenging to review. Let me know if you have any questions or concerns!

Fixes both [DCOS-8562](https://mesosphere.atlassian.net/browse/DCOS-8562) and [DCOS-8563](https://mesosphere.atlassian.net/browse/DCOS-8563).

Here it is working with Oauth:

Integration tests:

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @daiyiwhale

**Comment by jfurrow** [comment]
retest this please

**Comment by jfurrow** [comment]
**mesosphere**-ci retest this pelase

**Comment by mlunoe** [comment]
Beautiful! :information_desk_person: :sunflower:
Awesome work ⛵ :shipit:

**Comment by rcorral** [comment]
z-index for the background isn't right. See this:
gif

**Comment by jfurrow** [comment]
@rcorral That's how the designers want it.

**Comment by mlunoe** [comment]
Yup! I actually like it 🙂🙃

**Comment by orlandohohmeier** [comment]
I'm probably missing an important bit, but it looks very strange on my machine.

**Comment by jfurrow** [comment]
@orlandohohmeier You need this guy checked out also: https://github.com/mesosphere/dcos-ui-plugins-private/pull/378

**Comment by orlandohohmeier** [comment]
@jfurrow Thanks for the pointer

**Comment by orlandohohmeier** [comment]
LGTM 💯 ✨

**Comment by orlandohohmeier** [comment]
@jfurrow Could you please reopen this one once #978 is merged?

**Pull request merged**
