### PR TITLE
DCOS-13419: Enable Host volumes in all modes

### PR DESCRIPTION
**Pull request by Poltergeist**
**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

image

close DCOS-13419

### CODE REVIEW

**Comment by nLight** [comment]
LGTM! 💯  💖

**Comment by wavesoft** [comment]
You need to rebase `ph/feature/ucr-improvements` on master in order to fix a `Module ResourceTableUtil does not exist` error.
Otherwise looks great ✨ 👍

**Comment by wavesoft** [comment]
@Poltergeist  you need to rebase `ph/feature/ucr-improvements` on master in order to fix a `Module ResourceTableUtil does not exist` error.

Otherwise looks great ✨ 👍

**Comment by nLight** [comment]
Man this test!
  1) Service Actions Destroy Action Application reenables button after faulty request:

**Comment by nLight** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
@Poltergeist @wavesoft @nLight what stops us from merging this one?

**Comment by nLight** [comment]
@orlandohohmeier integration test did :)

**Comment by nLight** [comment]
Sadly there's no bot in place that would inform you that a PR status has changed to 💚 ... yet :trollface: Seal's gonna support that at some point.

**Pull request merged**
