### PR TITLE
DCOS-19021: Update Icons to match UI Kit

### PR DESCRIPTION
**Pull request by ashenden**
The DC/OS UI Kit has made updates to both the Product and System icon families. This PR attempts to reconcile these changes as well as introduce new icons into the DC/OS codebase.

Notable changes:
* Rename `icon-product-lock` icon to `icon-product-security`
* Rename `icon-product-users` icon to `icon-product-organization`
* Rename `icon-product-network` icon to `icon-product-networking`
* Rename `icon-product-network-inverse` icon to `icon-product-networking-inverse`
* Added `icon-product-insights` icon
* Added `icon-product-storage` icon
* Updated all references to product icons to use their correct ID.
* Updated system icons
* Added several new system icons (see commit for complete list)

**WARNING:** It is advised that we first merge PR #2453 prior to merging this PR.

**WARNING:** The DC/OS Private Plugins repo depends on Product Icons. There is an open PR against that repo with relevant changes.  Consider reviewing and merging both of these PR at the same time (https://github.com/mesosphere/dcos-ui-plugins-private/pull/631).

### CODE REVIEW

**Comment by nLight** [comment]
Alfred please test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this please

**Comment by nLight** [comment]
Alfred test this please

**Comment by MatApple** [comment]
alfred retest this please

**Comment by nLight** [comment]
Alfred test this please

**Comment by MatApple** [comment]
Alfred test this please

**Pull request merged**
