### PR TITLE
DCOS-37434- [master] improve merge data

### PR DESCRIPTION
**Pull request by Fabs**
This is the porting of the 1.10 performance improvement #2960, to master.

Please note that on master we changed the name of the class, and stop getting the hostname on mergeData. I would test this with more care and see if we still showing the right data. 

**Checklist**
- [X] Did you add a JIRA issue in a commit message or as part of the branch name?
- [X] Did you add new unit tests?

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot integrate  
@mesosphere-mergebot ship-it  
@mesosphere-mergebot test  
```

**Comment by DanielMSchmidt** [comment]
@bstavroulakis I think I fixed that now, please take another look :)

**Comment by Fabs** [comment]
@bstavroulakis nice catch. Think I forgot other places that are not that services page.

**Comment by juliangieseke** [comment]
Hm, legit fails? 🤔

**Comment by DanielMSchmidt** [comment]
Needs port of https://github.com/dcos/dcos-ui/pull/2982

**Comment by Fabs** [comment]
No more fails, ready to be reviewed :D

**Comment by Fabs** [comment]
@DanielMSchmidt, @bstavroulakis or @juliangieseke could you check again?

**Pull request merged**
