### PR TITLE
[CNVS Upgrade] Convert white icons to neutral

### PR DESCRIPTION
**Pull request by jfurrow**

### CODE REVIEW

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Comment by Poltergeist** [comment]
Error during Build `Error: '../../node_modules/reactjs-components/lib/Dropdown/styles.less' wasn't found.` :-(

**Comment by jfurrow** [comment]
@Poltergeist Sorry I didn't have this documented more clearly, but this PR requires the `cnvs-upgrade/master` branch be checked out for `reactjs-components` as well as the plugins repo. Tests won't pass until those branches have merged into master (or until CI can test plugins branches other than `master`).

I've added step-by-step instructions for testing this branch to the `cnvs-upgrade/master` PR: https://github.com/dcos/dcos-ui/pull/941

**Comment by jfurrow** [comment]
**mesosphere-ci** retest this please

**Pull request merged**
