### PR TITLE
Refactor volumes feature branch

### PR DESCRIPTION
**Pull request by Poltergeist**
This PR does contain all the efforts from various Pull requests please refer for reviews to the actual pull requests:
Already merged:
- #2559
- #2560 
- #2561 
- #2581
- #2578 
- #2584
- #2599

### CODE REVIEW

**Comment by weblancaster** [comment]
Hey @Poltergeist whenever I create a service with volume like so 

```
"volumes": [
      {
        "persistent": {
          "type": "root",
          "size": 10,
          "profileName": "mlancaster",
          "constraints": []
        },
        "mode": "RW",
        "containerPath": "local"
      }
    ],
```

and then try to edit to no volume selecting the `Volume Type` as the select option (basically removing) my json still displays.

```
"volumes": [
      {
        "containerPath": "mlancaster",
        "mode": "RW"
      }
    ],
```

**Comment by juliangieseke** [comment]
adding WIP label, @Poltergeist please remove when it is ready for review/test again 👍

**Comment by orlandohohmeier** [comment]
volume-json-parse-error

There seems to be an issue with the JSON parser as the I'm getting more and more host volumes when editing the JSON.

**Comment by Poltergeist** [comment]
The issue pointed out by @weblancaster has been merged with #2599 This is why I am dismissing @weblancaster's review

**Comment by juliangieseke** [comment]
this one is ready to merge if it gets the needed approvals, everything else can be merged to master afterwards 👍

**Comment by juliangieseke** [comment]
LGTM, the issues mentioned above seem to be fixed. Lets see if orlando is able to break it :trollface:

**Pull request merged**
