### PR TITLE
🛠 WIP: add .dcosrc to track compatible dcos version

### PR DESCRIPTION
**Pull request by orlandohohmeier**

### CODE REVIEW

**Comment by ahoskins** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
@ahoskins there is no need to re-trigger the test. This is work a progress (WIP) PR and in this specific case manually failed the tests.

**Comment by orlandohohmeier** [comment]
Alfred would you please restest this one

**Comment by orlandohohmeier** [comment]
_Alfred_ would you mind restesting this one please

**Comment by orlandohohmeier** [comment]
Alfred would you mind restesting this one please

**Comment by orlandohohmeier** [comment]
Alfred would you please retest this one

**Comment by orlandohohmeier** [comment]
Alfred would you please retest this one

**Comment by orlandohohmeier** [comment]
Alfred would you please retest this one

**Comment by orlandohohmeier** [comment]
Alfred please retest this one

**Comment by orlandohohmeier** [comment]
Alfred please retest this one

**Comment by orlandohohmeier** [comment]
Alfred could you please retest this one

**Comment by orlandohohmeier** [comment]
Alfred could you please retest this one

**Comment by orlandohohmeier** [comment]
Alfred would you mind retesting this one?

**Comment by MatApple** [comment]
I think we're doing something wrong when DC/OS specifies the version of UI it depends on and the UI also specifies which version of DC/OS it relies on.

I'm in favor of moving these tests into our ops workflow so we don't have circular dependency declarations.

**Pull request closed without merging**
