### PR TITLE
DCOS-14010: Bug fixes for logs and choosing log api

### PR DESCRIPTION
**Pull request by mlunoe**
This is the feature branch for log fixes. It contains the following PRs:
#1954
#1975
#1976
#1981
#1974
#1977
#1982
#1986

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by jfurrow** [comment]
🎉 Great stuff!

**Comment by rcorral** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
Please squash 1aa5522 and 320e3bf

**Comment by orlandohohmeier** [comment]
Squashed the commits, ran the integration tests and manually tested the UI. Great job everyone! 🚢

**Pull request merged**
