### PR TITLE
DCOS-14088: Fix sidebar styling in IE11

### PR DESCRIPTION
**Pull request by jfurrow**
This PR changes the sidebar's `max-width` property to `width` to avoid any inconsistent behavior with the its width. Fixes a bug in IE11 where the sidebar container element wasn't as wide as the actual sidebar.

This also fixes a bug where the user account dropdown menu was overflowing its container.

Before:

After:

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by rcorral** [comment]
@jfurrow could you please write some integration tests!

**Comment by wavesoft** [comment]
Looks good, but I aggree with @rcorral . It would be good to have some integration tests in order to ensure the text is wrapped correctly.

(Though I don't know how we can use cypress to test on IE)

**Comment by jfurrow** [comment]
@wavesoft Cypress doesn't work with other browsers yet, but it will in the future! I will add some integration tests anyway, good call 👍

**Comment by jfurrow** [comment]
@wavesoft @rcorral Added integration tests to catch this in the future

**Comment by jfurrow** [comment]
run integration tests

**Pull request merged**
