### PR TITLE
DCOS-38944 (2/2): remove remnants of sidebar header

### PR DESCRIPTION
**Pull request by tnguyen0**
Removes sidebar header, account dropdowns and hook for authenticated dropdown

Closes DCOS-38944

**Testing**
* The user account dropdown on the sidebar should be removed

**Dependencies**
Hold merge until #3084 is merged

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
@tnguyen0 I would be super happy if you could use the PR template. It would help me doing the review.

**Comment by DanielMSchmidt** [comment]
Does the dependency mean I can not test it individually or that I need to rebase onto that branch?

**Comment by tnguyen0** [comment]
Upon inspection. nope. I can add some 👀

**Comment by DanielMSchmidt** [comment]
@tnguyen0 We have some conflicts here :)

**Comment by juliangieseke** [comment]
integrated into #3084

**Pull request closed without merging**
