### PR TITLE
DCOS-14524: Refactor container reducer

### PR DESCRIPTION
**Pull request by Poltergeist**
**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

Remove Volumes from Form Reducer

close DCOS-14524

### CODE REVIEW

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Comment by nLight** [comment]
LGTM! 💯  💖

**Comment by Poltergeist** [comment]
run integration tests

**Comment by nLight** [comment]
flicts

**Comment by Poltergeist** [comment]
Already `rebase`d ™️

**Comment by nLight** [comment]
run unit tests

**Comment by jfurrow** [comment]
Looks good to me! :ship:

**Pull request merged**
