### PR TITLE
Update mesosphere-shared-reactjs to 0.0.24

### PR DESCRIPTION
**Pull request by jfurrow**
This update includes changes from https://github.com/dcos/mesosphere-shared-reactjs/pull/24

### CODE REVIEW

**Comment by jfurrow** [comment]
retest this please

**Comment by nLight** [comment]
retest this please

**Comment by Poltergeist** [comment]
retest this please

**Comment by Poltergeist** [comment]
retest this please

**Comment by Poltergeist** [comment]
LGTM

**Comment by nLight** [comment]
retest this please

**Comment by nLight** [comment]
@Poltergeist shall we just merge it, what do you think?

**Comment by nLight** [comment]
ok, we can't get rid of the integration by closing the PR

**Pull request merged**
