### PR TITLE
Enable service endpoints on UCR

### PR DESCRIPTION
**Pull request by nLight**
This PR enables Service Endpoints partials for the UCR runtime. Previously it wasn't possible to have a Service endpoints running on UCR.

Please test JSON to Form and Form to JSON. Launching and editing the app.

## Testing
Choose UCR as a runtime
screen shot 2018-03-02 at 12 45 57

Give it a hard time testing permutations
screen shot 2018-03-02 at 12 46 13

Closes DCOS_OSS-1550

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [x] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by nLight** [comment]
run integration tests

**Comment by juliangieseke** [comment]
One thing where I'm not exactly sure if it is as expected: when entering a port in the json, nothing happens in the form, but the port is actually send to marathon 🤔 
screen shot 2018-03-05 at 18 04 15

**Comment by weblancaster** [comment]
@juliangieseke The host port isn't selectable. But does raise the question why we are sending the port to Marathon.

**Comment by nLight** [comment]
@juliangieseke does this PR introduce the issue or is is reproducible for Docker runtime on master? I reported a port related bug https://jira.mesosphere.com/browse/DCOS-21307 maybe this is somewhat related

**Comment by juliangieseke** [comment]
well, there is no way changing this at all on master, not sure if it introduces it, but before there was no form element to edit this fields. Not sure if we should reset the `port` when the form is edited or not 🤔

**Comment by nLight** [comment]
@juliangieseke I'm not sure what's gone wrong in your case. I created an app with UCR and dcos network. Then I edited the app and it didn't switch network to the host mode. If your bug regarding the host network is reproducible please create a jira.

**Pull request merged**
