### PR TITLE
refactor(*): rename suspend to stop

### PR DESCRIPTION
**Pull request by weblancaster**
This commit includes a variety of refactoring where we rename suspend to stop across DCOS UI

Closes DCOS-19528

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by weblancaster** [comment]
@ahoskins your comments are addressed.

**Comment by weblancaster** [comment]
alfred test this please

**Comment by ahoskins** [comment]
alfreddo test this

**Comment by weblancaster** [comment]
alfreddo test this please

**Pull request merged**
