### PR TITLE
[Pods] DCOS-10593: Showing version in locale format

### PR DESCRIPTION
**Pull request by wavesoft**
This PR uses Date.toLocaleString to display the pod version in the table in a nicer and breakable way. This way we can steal a few pixels and make sure `Updated` and `Status` do not get wrapped in a new line, causing the table rows to get misaligned.

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
@wavesoft The `PodInstancesTable` checks are failing...

**Comment by Poltergeist** [comment]
` Expected [ '8/29/2016, 1:01:01 AM', '8/29/2016, 1:01:01 AM', '8/29/2016, 1:01:01 AM' ] to equal [ '8/29/2016, 3:01:01 AM', '8/29/2016, 3:01:01 AM', '8/29/2016, 3:01:01 AM' ].` Tests are still failing. might this be a timezone problem?

**Comment by wavesoft** [comment]
This PR needs #1278 merged in order for the tests to pass

**Comment by wavesoft** [comment]
**mesosphere-ci** retest this please

**Comment by Poltergeist** [comment]
👍 super awesome. Let's 🚢

**Comment by orlandohohmeier** [comment]
LGTM 🎆 🚢 🇮🇹

**Pull request merged**
