### PR TITLE
DCOS-13348: Increase Environment form section column widths

### PR DESCRIPTION
**Pull request by jfurrow**
Before:

After:

### CODE REVIEW

**Comment by nLight** [comment]
LGTM! 💯  💖

**Comment by philipnrmn** [comment]
Can we update the widths of the fields in the pods environment section to match?

image

**Comment by jfurrow** [comment]
@philipnrmn they actually use the same component, so the classes are applied to both. The multi-container env section was more narrow because the form's parent didn't have the right `flex-grow` property set, but that was fixed by #1861. I just rebased this to include those changes :)

**Comment by philipnrmn** [comment]
Ah, I see. I was wondering why the same component had two different widths.

**Comment by philipnrmn** [comment]
lint errors :hammer:

**Comment by jfurrow** [comment]
Ohh thank oyu @philipnrmn!

**Pull request merged**
