### PR TITLE
[deployments-table] Add services to deployments table

### PR DESCRIPTION
**Pull request by philipnrmn**
This PR introduces services to the deployments tables and adds styles for them. The `tree-list` will hopefully eventually be contributed upstream to Canvas-UI, but for the moment has been added as a dcos-ui specific component.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @MatApple

**Comment by kennyt** [comment]
all these commits legit? ;)

**Comment by philipnrmn** [comment]
Yes I am all of these people. 

No, something's badly wrong with the feature branch, which is peculiar since I should be the only one committing to it. I'm reassembling it by cherry-picking master.

**Comment by jfurrow** [comment]
Strange. I actually had to do the exact same thing earlier today on an unrelated branch.

**Pull request closed without merging**
