### PR TITLE
[Pods] Properly composing instance id

### PR DESCRIPTION
**Pull request by wavesoft**
This PR makes sure that the pod instances composed from `completed_tasks` have the correct ID.

Previously:
image

Now:
image

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
@wavesoft Please adjust the `MesosStateUtil` test accordingly

**Comment by nLight** [comment]
What about this one @wavesoft ?

**Comment by nLight** [comment]
*mesosphere-ci* retest this please

**Comment by nLight** [comment]
Awesome!

**Comment by jfurrow** [comment]
🎉

**Pull request merged**
