### PR TITLE
Using new breadcrumbs in services page.

### PR DESCRIPTION
**Pull request by rcorral**

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @pierlo-upitup

**Comment by rcorral** [comment]
retest this please

**Comment by daiyiwhale** [comment]
Code looks good! I'm not sure about this breadcrumb trail naming though, it's a bit confusing to have the service name twice when looking at the detail page. But I also don't know what would be better (naming the second breadcrumb label `tasks`? `details`? hm)

**Comment by daiyiwhale** [comment]
Oh wait that's just how the tasks happened to be named, ignore me!

**Comment by pierlo-upitup** [comment]
I think this PR removed the `Services` entry from the default (ie unfiltered) page. 

missing crumb

@rcorral what do you think?

**Comment by rcorral** [comment]
I can definitely add it back, I did this on purpose because I felt it was redundant for it to just say `Service`
If you think we should have it, I'll put up a PR. Let me know @pierlo-upitup

**Comment by pierlo-upitup** [comment]
Absolutely. As you can see in the gif the layout feels broken with the Services heading. Also, this is what the mockups indicate.

**Comment by rcorral** [comment]
PR #445

**Pull request merged**
