### PR TITLE
[1.9] feat: support docker parameters

### PR DESCRIPTION
**Pull request by weblancaster**
Support docker parameters.
This is based on @kensipe PR https://github.com/dcos/dcos-ui/pull/3037

*Testing:*
To really test this you need a special cluster. Maybe someone from the Marathon team will be able to help. In general we should verify if the shape of the JSON the form produces is in line with JIRA and switching from JSON and the Form back and forth doesn't mess up JSON.

Closes DCOS_OSS-3687

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by Fabs** [comment]
@weblancaster, @nLight. I know this needs to move faster, but I think since it is even hard to get a cluster to test this, we should have some integration or even better system level testing to verify this feature.

**Comment by weblancaster** [comment]
@Fabs I would leave the system test for the refactoring of this feat.

**Comment by juliangieseke** [comment]
adding hold merge label, see slack #frontend for more info 🤔

**Comment by weblancaster** [comment]
@juliangieseke maybe we should close, what you think?

**Comment by nLight** [comment]
@weblancaster wait for it, I think we are merging it

**Comment by Fabs** [comment]
I was given a cluster by @kensipe. The UI is not losing parameters anymore, and the form seems to work for me.

**Pull request merged**
