### PR TITLE
Polish volumes section

### PR DESCRIPTION
**Pull request by Poltergeist**
image

image

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @jfurrow

**Comment by pierlo-upitup** [comment]
Can we do something about the spacing and the cut-out icons?

**Comment by pierlo-upitup** [comment]
Sorry – I thought it was about `UI` polish. Ignore my previous comment.

**Comment by Poltergeist** [comment]
#510 is going to introduce a new icon. 
image

The spacing we aren't able to change anything without changing the logic behind the form.

Actually yes it is about the `UI`

**Comment by pierlo-upitup** [comment]
OK – how about the vertical spacing between the `Add another` link and the following duplicable row? 
image

there should be more room inbetween, imho.

**Comment by Poltergeist** [comment]
I'll look into that.

**Comment by Poltergeist** [comment]
Updated the screenshot

**Comment by pierlo-upitup** [comment]
Thanks!!

**Comment by pierlo-upitup** [comment]
🚢

**Pull request merged**
