### PR TITLE
DCOS-51384 name unknownvolumes parser

### PR DESCRIPTION
**Pull request by TattdCodeMonkey**
Gave UnknownVolumesParser function a unique name so that it could be
replaced by a plugin.

### CODE REVIEW

**Comment by brandonc** [comment]
Can you elaborate on how changing the export can allow it to be replaced by a plugin? Sorry I'm unclear

**Comment by TattdCodeMonkey** [comment]
@brandonc the parsers are passed through the plugin `Hooks.applyFilter` as a list of functions. If it has a unique name I can remove it from the list and add a replacement.

**Comment by GeorgiSTodorov** [comment]
The commit message is missing a jira number.

**Comment by TattdCodeMonkey** [comment]
This is a subtask and doesn’t close a JIRA in its own.

**Pull request merged**
