### PR TITLE
refactor(list/grid toggle): add new icons

### PR DESCRIPTION
**Pull request by lilysamimi**
Adding 2 new icons in .svg to icon-systems to be used for the list / grid toggle on the nodes page

donut
list

## Testing

Added two new icons, list and donut, to the src file. Can't see this in the UI yet. 

## Dependencies

This can be merged immediately! 💯 

This closes DCOS-28715.

### CODE REVIEW

**Comment by juliangieseke** [comment]
> This can be merged immediately! 💯 
Not so fast 😅 

1. this isnt used yet, correct? IMHO we should add it when it is actually used (css classes exists).
2. can you please add `Closes DCOS-28715` to the commit message? 
3. CI is failing - but its just flaky 😞

**Comment by leemunroe** [comment]
@lilysamimi Comparing the SVG code of these icons to our either icons it looks a little excessive. Did you export the shape from Sketch as SVG and use svgo to clean them? 

e.g. compare [this](https://raw.githubusercontent.com/dcos/dcos-ui/e4c18621a4063b86033cd9c2fe2636dca17874eb/src/img/components/icons/icon-system/donut.svg) to [this](https://raw.githubusercontent.com/dcos/dcos-ui/master/src/img/components/icons/icon-system/check.svg) or [this](https://raw.githubusercontent.com/dcos/dcos-ui/master/src/img/components/icons/icon-system/circle-fire.svg)

>IMHO we should add it when it is actually used (css classes exists)

@juliangieseke I'm not sure what you mean here. The icon library is a set of resources you can pull from when you need them. This PR is just adding another two to the inventory (I would say most of these icons aren't actually "used").

**Comment by juliangieseke** [comment]
I should have say "usable" 😅 I was asking for a css class which enables us to use the icon. wasnt aware that there are more "stale" icons in our codebase already 🤔

**Comment by lilysamimi** [comment]
@leemunroe Weird. 🤔I followed our Wiki: https://wiki.mesosphere.com/display/DCOS/Icons. I first exported the shape from in SVG from Sketch and then cleaned it up using svgo. 

screen shot 2018-07-31 at 11 11 38 am

Should I just clean it up manually? 

@juliangieseke Could we get this merged into the code first, then open another PR to write a CSS class for it?

**Comment by Fabs** [comment]
@juliangieseke what if we think of this PR as an automatic feature flag turned off? Would you think then is ok to merge them in, and write the css later?

**Comment by lilysamimi** [comment]
@Fabs @leemunroe @juliangieseke please check again. I cleaned up the code to match what our other icons are showing.

**Comment by juliangieseke** [comment]
@fabs comment: ok

But there are stilll issues with commit messages 😕

**Comment by Fabs** [comment]
I put the icons somewhere, just to test them.

screen shot 2018-08-01 at 16 15 17
screen shot 2018-08-01 at 16 09 19

**Comment by nLight** [comment]
I was just about to amend the commit to address your ask @juliangieseke

**Comment by juliangieseke** [comment]
As far as i understood the conversations yesterday, we already have other unused icons in our code 🤷‍♂️ wasnt aware that someone is working on this, sorry 😞

**Comment by nLight** [comment]
@juliangieseke I actually wanted to add `Closes DCOS-` metainfo and change it to be shore and not refactoring.

**Comment by juliangieseke** [comment]
yeah, but our master already has plenty of wrong commit messages, so why bother just lily with this? she doesnt know anything about our undocumented workflows… 

and again, I wasnt aware that someone is working on this, sorry 😞

**Comment by nLight** [comment]
> yeah, but our master already has plenty of wrong commit messages, so why bother just lily with this? she doesnt know anything about our undocumented workflows…

@juliangieseke all good, I just wanted to address the issues you pointed in _your_ review :D

**Pull request merged**
