### PR TITLE
feat(ServiceDetail): Rename Instances to Tasks

### PR DESCRIPTION
**Pull request by weblancaster**
Rename Instances to Tasks to avoid confusion and remove `<FilterHeadline />` for services detail and pods detail.

**Closes DCOS-17965**

**Before**
screen shot 2017-10-05 at 10 50 27 am

**After**
screen shot 2017-10-05 at 10 18 35 am

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by weblancaster** [comment]
@leemunroe please take a look and let me know if anything else is needed. thanks.

**Comment by ahoskins** [comment]
Alfreddo test this please

**Comment by weblancaster** [comment]
Alfreddoson test this please

**Comment by weblancaster** [comment]
@bstavroulakis I fixed the failing tests. thanks.

**Comment by MatApple** [comment]
@orlandohohmeier @Poltergeist @leemunroe putting hold merge on till somebody can explain the reasoning for removing the `<FilterHeadline/>` completely for service detail pages!

**Comment by Poltergeist** [comment]
After a discussion I had with @orlandohohmeier offline, where we also had a into the screen designs, We realised that the filterHeadline should be removed with introducing the DSL filters to the task list. So for this PR we should keep the filter headline, and make sure the wording is Tasks.

**Comment by leemunroe** [comment]
Correct, the goal is to consolidate the filtering to the DSL filter component.

@ashenden has been doing some work on the design patterns for table headings/actions but I don't think we've reached a conclusion just yet. This would also affect any other collection tables e.g. nodes, components. For the purposes of this PR I would suggest keeping the headline and we make those changes separately.

**Comment by weblancaster** [comment]
@MatApple Let us know if you need more info. Thanks.

**Comment by orlandohohmeier** [comment]
@weblancaster could you please adjust your PR to **not** remove the `FilterHeadline` as discussed in https://github.com/dcos/dcos-ui/pull/2441#issuecomment-335124670? We need apply these changes one after another and replacing the headline and filter buttons with the new filter component should be done in a separate PR.

**Pull request merged**
