### PR TITLE
DCOS-8052: Show "Clear" while filtering even if all items are shown

### PR DESCRIPTION
**Pull request by daiyiwhale**
showing "Clear" while filtering even if all items are shown

~~⚠️ Depends on https://github.com/dcos/dcos-ui/pull/660~~ merged

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @aldipower

**Comment by rcorral** [comment]
retest this please

**Comment by daiyiwhale** [comment]
retest this please

**Comment by daiyiwhale** [comment]
retest this please

**Comment by kennyt** [comment]
conflicts

**Comment by daiyiwhale** [comment]
rebased!

**Pull request merged**
