### PR TITLE
chore(PackagesTab): update copy for package types

### PR DESCRIPTION
**Pull request by MatApple**
Definition of community and certified packages needed to be more clearly communicated to users.

**Requirement**: Change description text on Catalog page for Certified and Community subtitles as follows:
- Certified packages are verified by Mesosphere for interoperability with DC/OS.
- Community packages are unverified and unreviewed content from the community.
 
**Acceptance**: From a running OSS and Enterprise DC/OS cluster
- Show the Service Catalog
- See the text from the requirements under "Certified" and "Community" sections

**Checklist**
- [ ] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by MatApple** [comment]
run integration tests

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
Shall we i18n it as we're touching it?

**Comment by orlandohohmeier** [comment]
LGTM! 🚢

**Pull request merged**
