### PR TITLE
DCOS-46169: get status for all deployments

### PR DESCRIPTION
**Pull request by natmegs**
Ensure status is retrieved from deployments, even when getStatus method is not available. Changes ported from #3453. 

Closes DCOS-46169.

## Testing

I haven't found a way to reliably get a service into a stale state so the easiest way to test this is to ensure the integration tests pass.

## Trade-offs

See #3453.

## Dependencies

N/A

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
@nLight is right, I forgot about that.

**Comment by natmegs** [comment]
@nLight Ooops, good catch :flushed: updated!

**Comment by DanielMSchmidt** [comment]
@natmegs It seems like CI is red because of a failing test in deployment modal, could you take a look?

**Comment by nLight** [comment]
It looks that `DeploymentsModal-cy.js` test is being flakey, would you please verify if we could proactively unflake it? Thanks

**Comment by DanielMSchmidt** [comment]
How do you come to the conclusion it is flaky and not really broken @nLight?

**Comment by natmegs** [comment]
@DanielMSchmidt @nLight Based on looking at the videos recorded in CI it looks like the tests always fail at the open modal step of the before each hook (but it happens irregularly - not always on the same test within the suite). I'll spend a bit of time to see if there's an easy change here otherwise I'll document in a JIRA.

**Pull request merged**
