### PR TITLE
DCOS_OSS-3968: update @dcos/mesos-client to 0.2.4

### PR DESCRIPTION
**Pull request by nLight**
The PR bumps mesos-client to include the fix for UTF8 chars in the mesos stream.

Closes DCOS_OSS-3968

## Testing
Try creating an app with a UTF8 symbol in a label.
Smoke test the UI. That services are being created/updated/deleted

### CODE REVIEW

**Comment by juliangieseke** [comment]
shall we also bump on 1.11?

**Comment by nLight** [comment]
@juliangieseke you are so right

**Comment by juliangieseke** [comment]
Friday is code freeze - lets get that one in

**Comment by nLight** [comment]
@juliangieseke #3176 please review

**Pull request merged**
