### PR TITLE
Fix merge DCOS-38481 to master

### PR DESCRIPTION
**Pull request by Fabs**
I merged https://github.com/dcos/dcos-ui/pull/3035 to another branch instead of master. This is a PR to fix it.

### CODE REVIEW

**Comment by Fabs** [comment]
I am approving this one, because it is not really my code: https://github.com/dcos/dcos-ui/pull/3035

**Comment by juliangieseke** [comment]
@Fabs I think this needs a rebase, the original PR only had 2 commits :(

**Comment by Fabs** [comment]
Well. This has two PRs in one now. Because #3032 pointed to master, and #3035 (that I merged wrong) pointed to #3032 (master < #3032 < #3035). Since I merged #3035 on #3032, now both this PR (#3038) and #3032 contains the same code (minus one merge commit).

**Comment by juliangieseke** [comment]
merged the other one, closing this 👍

**Pull request closed without merging**
