### PR TITLE
DCOS-18788: adjust port definition protocol handling

### PR DESCRIPTION
**Pull request by orlandohohmeier**
Change the reducers to properly handle missing protocols as they otherwise throw type errors which results in duplicated JSON definitions and a broken editor experience.

Closes DCOS-18788

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
Note to self: open a PR to back-port the fix to DC/OS UI 1.10

**Comment by orlandohohmeier** [comment]
@Poltergeist not sure I understand what you're after...

**Comment by Poltergeist** [comment]
Oh my bad ... the `SingleContainerPortDefinitionsReducer.js` does not have any tests. :/ And the PortDefinitions Reducer would just not return any value if tcp and udp is false.

**Comment by Poltergeist** [comment]
💯

**Comment by orlandohohmeier** [comment]
@Poltergeist yeah, though we should add test for respective reducers. Could you please file an JIRA to add the respective tests?

**Pull request merged**
