### PR TITLE
DCOS-12628: Support 'udp,tcp' simultaneously

### PR DESCRIPTION
**Pull request by nLight**
This PR adds support for `udp,tcp` value for protocol field. To achieve it I replaced radio buttons with checkboxes and changed underlying data format and logic. I also change the order of checkboxes to reflect `udp,tcp` value otherwise it might be somewhat confusing.

Multi-container version #1821 

screen shot 2017-01-19 at 15 05 03

### CODE REVIEW

**Comment by nLight** [comment]
run integration tests

**Comment by wavesoft** [comment]
Looks good to me! 👍  💯

**Comment by jfurrow** [comment]
Aside from the conflicts, it looks good & works well for me!

**Comment by nLight** [comment]
run unit tests

**Comment by nLight** [comment]
retest this please

**Comment by nLight** [comment]
retest this please

**Pull request merged**
