### PR TITLE
DCOS-12292: Display all errors on the review screen

### PR DESCRIPTION
**Pull request by nLight**
This PR adds support for top-level error messages with an empty path.

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
✨ Great

**Comment by wavesoft** [comment]
Is it possible to somehow detect unhandled paths? Because what would happen for example if you get a `expecting non-null value` on a property we don't know?

**Comment by wavesoft** [comment]
Otherwise this looks good 👍

**Comment by nLight** [comment]
@wavesoft I didn't quite get what you mean 🤔

**Comment by wavesoft** [comment]
Ok, just expose all the errors you receive now (not only top-level) just in case we don't handle some of the paths in the review sections.

**Comment by nLight** [comment]
@orlandohohmeier @wavesoft Changed the implementation to display all the errors while we don't highlight `em line by line

**Comment by nLight** [comment]
run integration tests

**Pull request merged**
