### PR TITLE
[System Tests]: DCOS-12805: Add SI tests for creating a simple pod

### PR DESCRIPTION
**Pull request by jfurrow**
This PR introduces the automated tests for [Create a simple pod](https://wiki.mesosphere.com/pages/viewpage.action?pageId=99615053)

To run this test, use:

<pre>
docker run -it --rm --ipc=host \
  -e CLUSTER_URL=$CLUSTER_URL  \
  -v `pwd`:/dcos-ui \
  mesosphere/dcos-ui dcos-system-test-driver \
  ./system-tests/driver-config/cluster.sh
</pre>

### CODE REVIEW

**Comment by MatApple** [comment]
ping @jfurrow - flicts

**Comment by jfurrow** [comment]
Thanks @MatApple, should be good now!

**Comment by wavesoft** [comment]
LGTM! ✨ 👍

**Comment by jfurrow** [comment]
Ping @MatApple

**Pull request merged**
