### PR TITLE
DCOS_OSS-1965: Change DC/OS favicon to Mesosphere DC/OS favicon

### PR DESCRIPTION
**Pull request by ashenden**
Change DC/OS favicon to Mesosphere DC/OS favicon to match updated brand.

### CODE REVIEW

**Comment by MatApple** [comment]
Alfred retest this please

**Comment by ashenden** [comment]
@orlandohohmeier it doesn't.  I can house it elsewhere.  Does having it here create some complication?

**Comment by juliangieseke** [comment]
2 approvals and its green, why isnt it merged? orlando didnt block it 🤔

**Comment by orlandohohmeier** [comment]
Let’s move this one forward. Housing the ‘favicon.iconsproj’ here shouldn’t be a problem.

**Pull request merged**
