### PR TITLE
Add /latest segment to documenationURI

### PR DESCRIPTION
**Pull request by jfurrow**
https://mesosphere.atlassian.net/browse/DOCS-844

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @MatApple

**Comment by daiyiwhale** [comment]
Wait a sec -- https://github.com/dcos/dcos-ui/pull/74

**Comment by jfurrow** [comment]
Oh my...

**Comment by daiyiwhale** [comment]
I think we should merge the previous! If/when we get responses to the tickets I filed we can make a new PR

**Comment by jfurrow** [comment]
Closing until this is settled.

**Pull request closed without merging**
