### PR TITLE
DCOS-8509: Add Run Time column to Jobs run history table

### PR DESCRIPTION
**Pull request by Thau**
This pull request adds a run time column to the jobs run history table.

screencapture-localhost-4200-1484145781607

### CODE REVIEW

**Comment by nLight** [comment]
*mesosphere-ci* retest this please

**Comment by orlandohohmeier** [comment]
**mesosphere-ci** ✅  ok to test

**Comment by rcorral** [comment]
@Thau could you please rebase your branch so that the tests can run again?

**Comment by Thau** [comment]
Done! Let me know if you need anything else.

**Comment by rcorral** [comment]
run integration tests

**Comment by rcorral** [comment]
Thanks @Thau :)

**Comment by nLight** [comment]
Good to go for me, what do you think @jfurrow?

**Comment by jfurrow** [comment]
@Thau @nLight Has the fork been deleted? I can't check this out locally.

I was able to copy & paste the file locally and I think we need to hide the column(s) for narrow viewports. The Job ID is illegible below `940px` wide:

**Comment by Thau** [comment]
I did delete it. I thought I was supposed to, because of the NDA on the interview 😟. I'm going to write to GitHub support to see if they can recover it.

Sorry for the inconvenience.

**Comment by Thau** [comment]
@jfurrow the repo has been restored. Please check if you can check out the branch now.

**Comment by jfurrow** [comment]
Thanks very much @Thau! It's working as expected.

**Pull request merged**
