### PR TITLE
DCOS-8427 Show task ids instead of name in Task List

### PR DESCRIPTION
**Pull request by pierlo-upitup**
screen shot 2016-07-15 at 16 03 57

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @daiyiwhale

**Comment by pierlo-upitup** [comment]
Relevant tests are passing: 
image

**Comment by kennyt** [comment]
in your screenshot there isn't a header for the table. should there be?

**Comment by orlandohohmeier** [comment]
@pierlo-upitup Code looks good to me, you only missed the header mapping. Feel free to merge after fixing that one.

**Comment by pierlo-upitup** [comment]
Thanks for the heads up @orlandohohmeier & @kennyt . Force-pushed the missing bit.

**Pull request merged**
