### PR TITLE
DCOS-12747: Wrap service configuration version dropdown in tooltip

### PR DESCRIPTION
**Pull request by jfurrow**

### CODE REVIEW

**Comment by jfurrow** [comment]
run unit tests

**Comment by mlunoe** [comment]
Works great! However, there is a related issue. It shows `[Object object]` on hover when the badge is present:


Doesn't have to be fixed here. Let me know if you want to fix it or if I should create a ticket.

**Comment by jfurrow** [comment]
@mlunoe Thanks for noticing, that's fixed now!

**Comment by mlunoe** [comment]
Label remains!

**Pull request merged**
