### PR TITLE
Use RequestUtil from mesosphere-shared-reactjs

### PR DESCRIPTION
**Pull request by jfurrow**
`RequestUtil` in https://github.com/dcos/mesosphere-shared-reactjs now contains all of the extra methods that previously existed only in DCOS UI.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @MatApple

**Comment by mlunoe** [comment]
Hmm... it feels sad to remove tests and not add them in the other repository. We should really add tests there. This shouldn't hold up this PR though

**Comment by kennyt** [comment]
@mlunoe there are tests in mesosphere-shared-reactjs for these no?

**Comment by jfurrow** [comment]
@mlunoe I didn't remove any tests, in fact I added 3 more :)

**Pull request merged**
