### PR TITLE
Relocate TaskDetail pages to own directory

### PR DESCRIPTION
**Pull request by daiyiwhale**
Restructure directory to reflect inheritence

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @mlunoe

**Comment by mesosphere-web** [comment]
Reviewer: @kennyt

**Comment by mlunoe** [comment]
Hmmm.. seeing that the page just keeps loading forever, when I go to a finished task

**Comment by kennyt** [comment]
yes, there's an error that gets thrown when visiting a finished taks

**Comment by daiyiwhale** [comment]
That seems to be an issue in master

**Pull request merged**
