### PR TITLE
DCOS-13773: Improve service spec blacklist

### PR DESCRIPTION
**Pull request by orlandohohmeier**
Include volumes in the service spec blacklist as the respective "state" data is generated by the MarathonUtil and shouldn't be part of a service spec. 

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [x] Did you add new unit tests?
- [x] Did you add new integration tests?
- [x] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
Volumes are not there anymore which is good, but I still can't relaunch an app :) 
Other stuff gets in the way

**Comment by nLight** [comment]
Are those legit? @orlandohohmeier https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-ui-pulls-integration/3840/console

**Comment by orlandohohmeier** [comment]
@nLight I've fixed the respective issue and the test should pass now.

**Comment by wavesoft** [comment]
Cleanups! ❤️  Looks good 👍 

Cleanup Cat

**Pull request merged**
