### PR TITLE
DCOS-7884: Adjust responsiveness of ServicesTable layout

### PR DESCRIPTION
**Pull request by jfurrow**
I consulted with @ashenden and this is where I landed:

Integration tests:

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @orlandohohmeier

**Comment by kennyt** [comment]
great job

a super minor nit: there's a point where the text sticks out

px

**Comment by kennyt** [comment]
LGTM after nit

**Comment by rcorral** [comment]
@jfurrow please put up a separate PR for Kenny's comment, I need to get this into the build.

**Pull request merged**
