### PR TITLE
[CNVS Upgrade] Fix Packages view

### PR DESCRIPTION
**Pull request by jfurrow**

### CODE REVIEW

**Comment by mlunoe** [comment]
This looks good, but I am missing the `horizontal-center` class from `alignment-utilities/styles.less`, which does not seem to be added here.

**Comment by jfurrow** [comment]
@mlunoe I just checked out this branch and it does have the `horizontal-center` class in `alignment-utilities/styles.less` — maybe I'm misunderstanding your comment?

**Comment by mlunoe** [comment]
So weird. For some reason I didn't have it when I checked it out. Will take another look!

**Comment by mlunoe** [comment]
Yes, this looks good.
You have a couple of tests failing in `PackagesTab-test`.

**Comment by mlunoe** [comment]
Yes, this looks good.
You have a couple of tests failing in PackagesTab-test.

**Comment by jfurrow** [comment]
@mlunoe Thanks, fixed now.

**Pull request merged**
