### PR TITLE
refactor(DCOS_OSS-1036): Remove not in use breadcrumb code.

### PR DESCRIPTION
**Pull request by weblancaster**
(**DCOS_OSS-1036**) This commit removes not in use code related to breadcrumb component and methods in hooks/routing.

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by nLight** [comment]
run unit tests

**Comment by nLight** [comment]
Please also 🔥  outstanding `Breadcrumbs-test.js` so that tests are 🍏

**Comment by weblancaster** [comment]
@nLight @MatApple this PR is ready now.

**Comment by jfurrow** [comment]
Great work @weblancaster! Thank you so much for doing this.

**Pull request merged**
