### PR TITLE
Backport 1.10: fix(raml-scripts): updates the download link for the raml files

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Backport of #2746

### CODE REVIEW

**Comment by nLight** [comment]
oh my...

**Comment by juliangieseke** [comment]
run integration tests

**Comment by juliangieseke** [comment]
hm
```
+ npm run cypress -- --reporter junit --reporter-options mochaFile=cypress/results.xml
npm ERR! Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "cypress" "--" "--reporter" "junit" "--reporter-options" "mochaFile=cypress/results.xml"
npm ERR! node v4.4.7
npm ERR! npm  v3.9.6

npm ERR! missing script: cypress
```
@nLight https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests-integration/516/console

**Comment by juliangieseke** [comment]
```
if(branch === release/1.10) {
 old way
} else {
 new way
}
```
?

**Comment by DanielMSchmidt** [comment]
@juliangieseke Let's fix this with backporting the jenkinsfiles properly once we are that far (like have them working properly 😢)

**Pull request merged**
