### PR TITLE
DCOS-11659: Properly handling state between form edit & review screens

### PR DESCRIPTION
**Pull request by wavesoft**
This PR makes sure the service configuration is properly maintained when switching between service editing mode and review page.

When #1401 lands, it will also disable the `Review & Run` button when there are errors on the form.

### CODE REVIEW

**Comment by wavesoft** [comment]
**mesosphere-ci** don't be a quitter, retest this please!

**Comment by nLight** [comment]
retest this please 🙇

**Comment by mlunoe** [comment]
Great improvement!

**Comment by mlunoe** [comment]
This works great! Going to merge this guy

**Pull request merged**
