### PR TITLE
Fix styling for pre code blocks

### PR DESCRIPTION
**Pull request by jfurrow**
Integration tests passing on a frankie branch, which includes this branch:

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @Poltergeist

**Comment by kennyt** [comment]
what does this do exactly? master looks pretty similar to your screenshots from what i can tell

**Comment by jfurrow** [comment]
This gets rid of the "yucky" border. Open the install modal on master and you'll see a dark border around the CLI commands.

Also, I decided to properly define the border color itself. It was previously set explicitly to be a dark border for all `pre` blocks. I changed it so that all `pre` blocks have a light border by default, and get the dark blue border when they have the `inverse` class.

**Comment by Poltergeist** [comment]
This looks good except flicts. feel free to merge once this branch is rebased.

**Comment by mlunoe** [comment]
Conflicts!

**Comment by rcorral** [comment]
retest this please

**Pull request merged**
