### PR TITLE
DCOS-21844: add hot module reloading

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
**Checklist**
- [X] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by jaxesn** [comment]
Does this supersede https://github.com/dcos/dcos-ui/pull/2859?

**Comment by DanielMSchmidt** [comment]
@jaxesn it is a second approach, but I wanted to start from a clean state

**Comment by weblancaster** [comment]
@DanielMSchmidt I tested locally and didn't work, below you will find my recordings.
I also feel this is a hack solution wrapping the providers in a `App` component.

screen recording 2018-04-09 at 12 45 pm

**Comment by bstavroulakis** [comment]
@DanielMSchmidt I also experience what Michael saw, have we tested if this works with plugins?

**Comment by DanielMSchmidt** [comment]
@weblancaster @bstavroulakis This is an issue on master, at least the one in the webpack console, we got a [jira ticket](https://jira.mesosphere.com/browse/DCOS-21991) for this already. It is not related to this PR, could you check if the hot reloading works?

**Comment by DanielMSchmidt** [comment]
I clicked on different parts of the application to find an enterprise part and I found some heavy problems that way. I won't be spending more time on this, therefore I will close the PR 👍

**Pull request closed without merging**
