### PR TITLE
Remove SecretValue component

### PR DESCRIPTION
**Pull request by daiyiwhale**
Functionality deprecated by changes to `DescriptionList` in this PR: https://github.com/dcos/dcos-ui/pull/669

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @Poltergeist

**Comment by mlunoe** [comment]
You need to remove it from PluginModules.js too, after that 🚢

**Comment by daiyiwhale** [comment]
Good catch, thanks Michael! done \o/

**Comment by pierlo-upitup** [comment]
retest this please

**Pull request merged**
