### PR TITLE
[CNVS Upgrade: 3 of 3] Update application routes new Sidebar

### PR DESCRIPTION
**Pull request by jfurrow**
Depends on:
~~#1086~~
#1087

### CODE REVIEW

**Comment by philipnrmn** [comment]
retest this please

**Comment by jfurrow** [comment]
@philipnrmn These tests are going to fail until these PRs land: #1090 and #1101.

**Comment by philipnrmn** [comment]
This looks great! One slight oddity to do with the tabs, on the /services/deployments, services remains highlighted:

screen shot 2016-09-20 at 12 16 35 pm

**Comment by philipnrmn** [comment]
Otherwise LGTM :)

**Pull request merged**
