### PR TITLE
DCOS-14727: Refactor volumes reducer

### PR DESCRIPTION
**Pull request by Poltergeist**
**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

Remove `FormReducer` as the form uses the specific
typed reducers like external volumes, host volumes
and local volumes.

close DCOS-14727

### CODE REVIEW

**Comment by Poltergeist** [comment]
**mesosphere-ci** run unit tests

**Comment by Poltergeist** [comment]
**mesosphere-ci** run unit tests

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Comment by nLight** [comment]
LGTM! 💯  💖

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Comment by jfurrow** [comment]
It reduces volumes so beautifully!

**Pull request merged**
