### PR TITLE
Handle empty log by sending update if nothing has happened

### PR DESCRIPTION
**Pull request by mlunoe**

### CODE REVIEW

**Comment by MatApple** [comment]
@mlunoe I think we should handle this by still showing the log viewer, either as empty or with a message conveying the fact that the logs are empty.

**Comment by mlunoe** [comment]
Isn't that what we hare doing?

**Comment by MatApple** [comment]
I guess we are, perhaps it's just taking a long time to fetch the error log before we realize it's empty. Is that what's happening?

**Comment by mlunoe** [comment]
Yup I can set the timeout to be slower, like 4 seconds?

**Comment by mlunoe** [comment]
Done

**Comment by jfurrow** [comment]
This makes sense to me and works well. :ship:

**Comment by jfurrow** [comment]
Feel free to merge when tests pass!

**Pull request merged**
