### PR TITLE
[Logs 2 of 2] DCOS-12710: Logs eats up a lot cpu

### PR DESCRIPTION
**Pull request by mlunoe**
~~Logs 1 of 2 PR: https://github.com/dcos/dcos-ui/pull/1736~~ Merged
Logs 2 of 2 PR: https://github.com/dcos/dcos-ui/pull/1745

Also fixes: DCOS-12752

Before:

After:

This task also fixes the problem when losing focus while tailing the log (here it works with the given test case):

### CODE REVIEW

**Comment by mlunoe** [comment]
Rebased!

**Comment by philipnrmn** [comment]
Nice work @mlunoe!

**Comment by mlunoe** [comment]
Rebased with integration test fixes

**Comment by rcorral** [comment]
run unit tests

**Pull request merged**
