### PR TITLE
DCOS-11269: Add service icon to breadcrumb

### PR DESCRIPTION
**Pull request by jfurrow**
This PR adds the service icon to the breadcrumb. ~~Let's `hold merge` until the design team has had a chance to review.~~ Ready to go!

Ping @ashenden @leemunroe

### CODE REVIEW

**Comment by mlunoe** [comment]
Great stuff

**Comment by mlunoe** [comment]
Run unit tests

**Comment by mlunoe** [comment]
A lot of tests are failing in this PR, but I am not sure it is related

**Comment by jfurrow** [comment]
Rebased with integration test fixes 🎉

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
run integration tests 😒

**Comment by nLight** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
LGTM 💯 ✨

**Comment by orlandohohmeier** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
run integration tests

**Comment by MatApple** [comment]
run integration tests

**Pull request merged**
