### PR TITLE
feat(PodEndpoints): Add vip input to virtual networks

### PR DESCRIPTION
**Pull request by Poltergeist**
Add the vip port input field to the virtual networks of pods Multi container services.
image

Closes DCOS_OSS-1553

### CODE REVIEW

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
Do you think it's a good idea to add an integration test?

**Comment by Poltergeist** [comment]
Yes definitely, will create a jira for this so that this is not blocking this issue is that okay for you?

**Comment by ahoskins** [comment]
Got the same issue as Dima.

**Comment by nLight** [comment]
@ahoskins please give it another shot

**Comment by nLight** [comment]
Let’s please address this as a high prio one outside of the ticket

Dmitrii Rozhkov
Software Engineer Frontend, Mesosphere

**Comment by bstavroulakis** [comment]
related improvement https://jira.mesosphere.com/browse/DCOS_OSS-2160

**Pull request merged**
