### PR TITLE
[GA BLOCKER] DCOS-58445: Replace the "plus icon" dropdown with two separate dropdowns

### PR DESCRIPTION
**Pull request by nLight**
Replacing `+` icon with suggested dropdowns for Service/Quota screens

## Testing

Please check empty states when group is empty
also top level group, 1 level, 2 levels deep

## Trade-offs

1. I had to leverage supplemental content and completely drop `addButton` prop on the header component
2. Overrode CNVS `button:hover` style in a nasty way 😅 

### After

Screenshot 2019-09-10 at 15 59 17

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
I also think that it would look better without the hover effects. I also agree with them being too close. Can we introduce a single dropdown that says actions?
Снимка от 2019-09-06 20-40-47

**Comment by nLight** [comment]
If we say `Actions` we can't really use the `+` icon.

/cc @izharbuendia

**Comment by GeorgiSTodorov** [comment]
"Actions" was just an example. The idea was to have a dropdown that includes both the create and the edit actions.

**Comment by GeorgiSTodorov** [comment]
Tests are passing now, but we still have the hovers. @mperrotti

**Comment by nLight** [comment]
Updated the PR, I discovered that we have "native" actions menu so I re-used it. The hover color change for the `New` button still there I will just override it.

**Pull request merged**
