### PR TITLE
fix(system-tests): increase instance size

### PR DESCRIPTION
**Pull request by juliangieseke**
this commit inceases the instance size because our AWS account has a higher limit for xlarge

### CODE REVIEW

**Comment by juliangieseke** [comment]
First try:
Alfred: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/2313/
Integration Tests: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests-integration/12/
System Tests: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests-system-tests/19/

**Comment by nLight** [comment]
Repeating my comment:
When I was talking about 6 Gb I was referring not to the system tests server but the _Jenkins Instance_ that runs all the tests

**Comment by nLight** [comment]
not a blocker

**Comment by juliangieseke** [comment]
Closing this because the issue should be solved soon

**Pull request closed without merging**
