### PR TITLE
DCOS-11482: Backport fix for unknown values wipe

### PR DESCRIPTION
**Pull request by orlandohohmeier**
Fix the wipe of unknown values from the job form.

Closes DCOS-11482

### CODE REVIEW

**Comment by mlunoe** [comment]
Looks good dude. Is this commit in master too? And if not; should it be?

**Comment by mlunoe** [comment]
Merging as integration tests aren't really working for 1.8

**Comment by orlandohohmeier** [comment]
@mlunoe yep this commit is already on master 😄

**Comment by mlunoe** [comment]
👍🏼

**Pull request merged**
