### PR TITLE
DCOS-8978: Fixing bug that drops empty environment variables

### PR DESCRIPTION
**Pull request by wavesoft**
The `JSON.stringify` function is dropping keys with `undefined` values. This pull request makes sure that no environment variable value is in this state.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @Poltergeist

**Comment by philipnrmn** [comment]
Hey @wavesoft, welcome to the team and congratulations on your first DC/OS PR!

Can we have a corresponding unit test in [ServiceUtil-test.js](https://github.com/dcos/dcos-ui/blob/master/src/js/utils/__tests__/ServiceUtil-test.js) please?

**Comment by mlunoe** [comment]
Looks good, feel free to merge once tests pass.

Note: That `ServiceUtil.js` file is not understandable and the functions in there are abnormally large. I created a ticket to clean it up.

**Comment by orlandohohmeier** [comment]
**mesosphere-ci** retest this please

**Pull request merged**
