### PR TITLE
 DCOS-14729: Move require ports reducer

### PR DESCRIPTION
**Pull request by Poltergeist**
**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

close DCOS-14729

### CODE REVIEW

**Comment by Poltergeist** [comment]
**mesosphere-ci** run integration tests

**Comment by Poltergeist** [comment]
run integration tests

**Comment by Poltergeist** [comment]
**mesosphere-ci** run unit tests

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Comment by Poltergeist** [comment]
run integration test

**Comment by jfurrow** [comment]
:ship:

**Pull request merged**
