### PR TITLE
DCOS-13154: Adjust service resource getter

### PR DESCRIPTION
**Pull request by orlandohohmeier**
This PR aligns the service specs and changes the `Service` resource getter to calculate the resources for all "running" instances instead of just forwarding the spec data. 

Closes DCOS-13154

### CODE REVIEW

**Comment by nLight** [comment]
Awesome work, man!

**Comment by philipnrmn** [comment]
run integration tests

**Comment by nLight** [comment]
flicts!

**Comment by orlandohohmeier** [comment]
run integration tests

**Comment by wavesoft** [comment]
run integration tests

**Comment by wavesoft** [comment]
Looks good! ✨  💯

**Pull request merged**
