### PR TITLE
[CNVS Upgrade] Fix inverse classes

### PR DESCRIPTION
**Pull request by jfurrow**
This PR removes some inverse classes that shouldn't be present

### CODE REVIEW

**Comment by mlunoe** [comment]
Conflicts!

**Comment by jfurrow** [comment]
@mlunoe Conflicts fixed!

**Comment by jfurrow** [comment]
ping @rcorral @MatApple @wavesoft this is one of the worst ones, this should definitely be merged before Thursday's demo

**Comment by MatApple** [comment]
Thanks @jfurrow for the clean up :)

**Pull request merged**
