### PR TITLE
-> [Store config 3 of 4] NodeHealthStore, NotificationStore, ActionTypes, SidebarStore, TaskDirectoryStore, UnitHealthStore

### PR DESCRIPTION
**Pull request by mlunoe**
This PR moves registering of stores their respective constructors instead of it being handled in StoreConfig.

Functionally there is no change from this PR.
Includes the following stores:
- NodeHealthStore
- NotificationStore
- ActionTypes
- SidebarStore
- TaskDirectoryStore
- UnitHealthStore

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @orlandohohmeier

**Comment by jfurrow** [comment]
🚢

**Pull request merged**
