### PR TITLE
1066 - Engage suspend action

### PR DESCRIPTION
**Pull request by aldipower**
This integrates the actual action to suspend a service. Engage!

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @kennyt

**Comment by pierlo-upitup** [comment]
Tests are failing for real

```
 63 passing (3m)
  27 pending
  1 failing

  1) Tasks Table Task row displays task detail page on task click:
     Uncaught Error: Uncaught TypeError: Cannot convert undefined or null to object (http://localhost:2020/index.js:37150)
      at uncaughtException.n.onerror (http://localhost:2020/__cypress/static/js/vendor.js:33:12620)
      at window.onerror (http://localhost:2020/:3:86)
```

**Comment by aldipower** [comment]
Yes, I will adjust and add integration tests once I collected everything in the base branch `feature/1066-service-actions`. 
It doesn't make sense in this PR here. The things are too dependent on each other.

**Comment by Poltergeist** [comment]
Tests pass locally 👍  Thanks for this PR and the great work.

**Pull request merged**
