### PR TITLE
Upgrade react v15.4.1 and few other deps

### PR DESCRIPTION
**Pull request by nLight**
Can't shrinkwrap because of peerDeps of cnvs and reactjs-components. 
If we roll with this I'll update all of them.

React now allows all the attributes so we don't need a special hack for SVG

### CODE REVIEW

**Comment by nLight** [comment]
retest this please

**Comment by nLight** [comment]
Need land this first https://github.com/mesosphere/reactjs-components/issues/385

**Comment by nLight** [comment]
retest this please

**Comment by nLight** [comment]
retest this please

**Comment by nLight** [comment]
run integration tests

**Comment by wavesoft** [comment]
Beautiful

**Comment by wavesoft** [comment]
Are these related to the upgrade?

image

Not breaking the functionality though...

**Comment by nLight** [comment]
@wavesoft makes sense to address them anyway, thanks!

**Comment by nLight** [comment]
Actually those come from `reactjs-components` and should be resolved there

**Comment by nLight** [comment]
Issue extracted https://jira.mesosphere.com/browse/DCOS-14955

**Comment by Poltergeist** [comment]
This looks good to me 💯  👍

**Comment by nLight** [comment]
Boom!

**Pull request merged**
