### PR TITLE
DCOS-10975: Form validation based on RAML spec

### PR DESCRIPTION
**Pull request by wavesoft**
This PR uses the `raml-validator-loader` webpack loader to translate RAML documents to javascript validation functions and then uses them to validate the form contents.

To test:

```
npm run raml-update
```

_NOTE: I have embedded the `raml-validator-loader` project with the 528b2ab commit. Ideally it should be moved on a separate project and that commit should be removed, but until we have settled with the management stuff it will stay here_

**To check only the interesting changes check [this diff here](https://github.com/dcos/dcos-ui/compare/master...862cc88d104073a6207b843fc0496586a3d1c478)**

validation mov

### CODE REVIEW

**Comment by wavesoft** [comment]
@mlunoe fixed and rebased

**Comment by mlunoe** [comment]
Went over this with @wavesoft offline and went through the generators with type validators of this project.
All the base cases seem to be covered, but it is hard to grasp all the edge cases, even though @wavesoft has done a lot for trying to catch as many as possible.
We decided that the best way of perfecting this library is for @Poltergeist and me to start working with it to uncover the rest of the edge cases.

With regards to the process of updating the raml files I think it would be good to point to a particular marathon tag, so we can ensure the right validation with the right version of Marathon. But this can happen at a later stage.

**Comment by Poltergeist** [comment]
Went over it with @wavesoft this morning this is incredible as @mlunoe said we should start using it and uncover the edge cases and try to figure out how we should handle them then. Great Work 👍  🎆  let's :shipit: as soon as it is rebased.

**Comment by nLight** [comment]
@wavesoft Flicks and merge! ;)

**Comment by wavesoft** [comment]
Hold merge because:

- [ ] Separate the embedding of `raml-validation-loader` to a separate PR
- [ ] Change the `raml-update` script to a pre-install function that fetches the RAML files of a specific marathon version
- [ ] Use the `walkObjectsByPath` from #1337

**Comment by wavesoft** [comment]
⚠️  For testing you should first merge this locally : https://github.com/dcos/dcos-ui/pull/1342

**Comment by mlunoe** [comment]
#1342 Is merged!

**Comment by wavesoft** [comment]
Well, I guess I can remove the hold merge now 😄

**Pull request merged**
