### PR TITLE
Feature - 1066 Service Actions

### PR DESCRIPTION
**Pull request by aldipower**
This PR aggregates all already merged PRs related to the Service Actions.
That means every commit was already reviewed, so this PR shouldn't receive that much comments.

So finally this enables the user to 'open the edit dialog', Scale, Suspend and Delete a service.

Last step now is to write and adjust the integration tests.

---

* [x] Everthing's implemented
* [x] Integration tests (https://github.com/dcos/dcos-ui/pull/408)
* [x] Test for delete service action

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @MatApple

**Comment by pierlo-upitup** [comment]
One question: do we surface errors to the users via a dialog? (for example when an action is 401 unauthorized, etc.)

**Comment by aldipower** [comment]
@pierlo-upitup Yes, we do. Every server error response in shown in the according dialog.

**Comment by orlandohohmeier** [comment]
LGTM 💯 ✨

**Comment by orlandohohmeier** [comment]
BTW: Are you planning to add a method (in future PRs) to force operation like suspending a service?

**Comment by aldipower** [comment]
@orlandohohmeier No, I don't plan this. Maybe somebody other?

**Pull request merged**
