### PR TITLE
Fix system tests 2

### PR DESCRIPTION
**Pull request by juliangieseke**
---

⚠️ Depends on #2646

---

this PR fixes the System tests regarding the new Select Component.

### CODE REVIEW

**Comment by juliangieseke** [comment]
Alfred: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/2315/
Integration Tests: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests-integration/13/
System Tests: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests-system-tests/20/

**Comment by nLight** [comment]
When I was talking about 6 Gb I was referring not to system tests server but the Jenkins instance that runs all the tests

**Comment by nLight** [comment]
Not a blocker, high prio

**Comment by juliangieseke** [comment]
Instance issue should be solced soon, we have to check if this PR is different to TBD (remove redundant tests)

**Comment by bstavroulakis** [comment]
Some of these updates are done in the "remove redundant tests" task => https://github.com/dcos/dcos-ui/pull/2621/files#diff-1549ad8424a561b8f555187361c013a6R50

**Comment by DanielMSchmidt** [comment]
@bstavroulakis Thank you for pointing that out, we should have added a comment about that 🙈 we copied them over 🙈

**Comment by juliangieseke** [comment]
yeah, it was that PR I tried to reference. the purpose of this one only was to verify it our assumption was true (looks like it was) - but since the other PR colves them, I'll close this one 👍

**Pull request closed without merging**
