### PR TITLE
React don't blink

### PR DESCRIPTION
**Pull request by nLight**
implement React `shouldComponentUpdate` in couple of places to kill re-renders.

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
Failing integration test is also failing locally. I will fix it.

**Comment by nLight** [comment]
@GeorgiSTodorov would appreciate it!

**Comment by mperrotti** [comment]
@GeorgiSTodorov - I can't get the test to fail locally.
When you work on the fix, could you let me know how to reproduce the failure?

**Comment by GeorgiSTodorov** [comment]
@mperrotti , I used this PR in order to run the tests - https://github.com/dcos/dcos-ui/pull/3778 .

**Comment by GeorgiSTodorov** [comment]
@nLight , if we copy and paste the components > component > node link, the breadcrumbs break. On master, it works fine.
Peek 2019-04-09 14-20

**Comment by mperrotti** [comment]
@GeorgiSTodorov - I pushed up a fix for that which should also fix the integration test that was failing after you fixed the Zones one

**Comment by GeorgiSTodorov** [comment]
@mperrotti , cool, thanks.

**Pull request merged**
