### PR TITLE
Replace packages with a dependency

### PR DESCRIPTION
**Pull request by nLight**
Dogfooding is good. Everyone likes dogfood.

I extracted all the packages:
https://github.com/dcos-labs/mesos-client
https://github.com/dcos-labs/recordio
https://github.com/dcos-labs/http-service
https://github.com/dcos-labs/connection-manager
https://github.com/dcos-labs/connections

and then added `@dcos/mesos-client` as a dependency

## Dependency

✅   #2466

### CODE REVIEW

**Comment by nLight** [comment]
Alfred test this please

**Comment by Poltergeist** [comment]
:bike:shedding ?
I'll give it a spin as soon as the tests pass.

**Comment by nLight** [comment]
🐕 fooding! :)
We needed those packages for the MesosCon hackathon.

**Comment by nLight** [comment]
@Poltergeist gulp issue should be fixed!

**Comment by nLight** [comment]
@Poltergeist it's green \o/

**Pull request merged**
