### PR TITLE
Docker in Docker Example

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Only to show a docker in docker bug, please don't merge

### CODE REVIEW

**Comment by nLight** [comment]
What's the progress on this one?

**Comment by DanielMSchmidt** [comment]
Here is the current progress documented: https://jira.mesosphere.com/browse/DCOS-43361

**Comment by pierrebeitz** [comment]
@DanielMSchmidt the linked issue is resolved, can we close here?

**Comment by DanielMSchmidt** [comment]
Yes

Pierre Beitz <notifications@github.com> schrieb am Fr., 15. März 2019,
20:31:

**Pull request closed without merging**
