### PR TITLE
DCOS-8002: Use less hacky method of positioning the sidebar

### PR DESCRIPTION
**Pull request by jfurrow**
This PR changes the way we handle the sidebar's layout and animation. It animates the `transform` property instead of the `left` property for better performance.

I tested this in all of our supported browsers and it should be good, but please try to break it!

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @mlunoe

**Comment by rcorral** [comment]
retest this please

**Comment by jfurrow** [comment]
retest this please

**Comment by rcorral** [comment]
retest this please

**Comment by rcorral** [comment]
Looks great!

**Pull request merged**
