### PR TITLE
[local volumes] add residency if needed

### PR DESCRIPTION
**Pull request by Poltergeist**
If one adds a local persistent volume also the residency has to be set. As we do not have any field in the form representing this. We only have a `JSONReducer` and `JSONParser` for this.

residency mov

The erros which you see in the animation is addressed by: #1601

### CODE REVIEW

**Comment by wavesoft** [comment]
Tested against #1601 and works perfectly! ✨  💯

**Comment by nLight** [comment]
JSON - to - From reducer (I still can't remember names) switches the Form to `UCR` from `Mesos Runtime`, which is the same thing yet can be confusing for a user. Just hit space bar anywhere in JSON editor to see what I mean

dec-14-2016 14-44-06

**Comment by orlandohohmeier** [comment]
@nLight I fear there is no simple way of fixing that issue, but I have a few ideas...  anyway, let's not block this PRs as it's not an issue related to the introduced changes. Please file an JIRA so that we don't forget to fix the parsing.

**Comment by orlandohohmeier** [comment]
LGTM 💯 ✨

**Pull request merged**
