### PR TITLE
Introduce Mesos constants

### PR DESCRIPTION
**Pull request by orlandohohmeier**
Add dedicated Mesos constants, to have them all in one place.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @mlunoe

**Comment by pierlo-upitup** [comment]
Thanks!

**Comment by pierlo-upitup** [comment]
Shouldn't we pull these in also in our Service structs/form?

**Comment by orlandohohmeier** [comment]
@pierlo-upitup Yes, I'm currently working on the service for and did this "only" to prepare stuff to properly implement validation.

**Comment by pierlo-upitup** [comment]
One nit: can we keep the naming consistent with the other constant files?

(rename to `MesosConstants.js` as well as the const itself)
image

**Comment by orlandohohmeier** [comment]
@pierlo-upitup Sure. Adjusted the name.

**Pull request merged**
