### PR TITLE
DCOS-38483 & DCOS-38484: Add Menu to Job Detail Page 

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
## Testing

Checkout the Job Detail Page and use the Menu. It should be the same as in previous versions, so make sure to check it against an "old" cluster, e.g. from master.

## Trade-offs

None that I am currently aware of, this lingered around for so long that I forgot

## Dependencies

None

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
@juliangieseke Bug is fixed, please take another look

**Comment by nLight** [comment]
screen shot 2018-07-11 at 11 03 58
Not sure why but stop job isn't working /cc @Fabs

**Comment by DanielMSchmidt** [comment]
I am sure why 🙈 Will fix it

**Comment by Fabs** [comment]
@nLight hum... looking.

**Comment by nLight** [comment]
@DanielMSchmidt shall we add some integration tests?

**Comment by DanielMSchmidt** [comment]
@nLight I am mistaken, it works fine for me... Can you share your steps?

**Comment by Fabs** [comment]
If it is behaving weirdly I would check if the `jobId` is being passed fine.

**Comment by DanielMSchmidt** [comment]
@Fabs I changed the behavior of jobId in this PR, so that would fit, but it works on my end, so I am a bit puzzled

**Comment by nLight** [comment]
@DanielMSchmidt 
jul-11-2018 11-11-35

**Comment by DanielMSchmidt** [comment]
@nLight what is going on here?
working

**Comment by juliangieseke** [comment]
Conflicts @DanielMSchmidt

**Pull request merged**
