### PR TITLE
chore(BetaOptIn): clean out unused beta opt-in code

### PR DESCRIPTION
**Pull request by MatApple**
Beta opt-in feature was switched off last minute and is something we no longer need. This cleans up dead code.

**Checklist**
- [ ] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
Alfred please retest this PR!

**Comment by orlandohohmeier** [comment]
LGTM! 🚢

**Comment by nLight** [comment]
Alfred alalalala retest this bitte

**Comment by nLight** [comment]
with-fire

**Comment by MatApple** [comment]
Alfred retest this please

**Pull request merged**
