### PR TITLE
Improve text color contrast in package install modal

### PR DESCRIPTION
**Pull request by jfurrow**
Integration tests passing on a frankie branch, which includes this:

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @pierlo-upitup

**Comment by rcorral** [comment]
retest this please

**Comment by rcorral** [comment]
retest this please

**Comment by rcorral** [comment]
flicts!

**Comment by jfurrow** [comment]
flicts resolved!

**Comment by daiyiwhale** [comment]
Looks good :D

**Comment by jfurrow** [comment]
retest this please

**Comment by jfurrow** [comment]
retest this please

**Comment by daiyiwhale** [comment]
retest this please <rising desperation in voice>

**Pull request merged**
