### PR TITLE
DCOS-6095: Use patched version of Dygraphs and minify it on build

### PR DESCRIPTION
**Pull request by jfurrow**
We're now using the a non-minified Dygraphs release, with a patched `Legend.prototype.select` method. Gets minified at build.

### CODE REVIEW

**Comment by mlunoe** [comment]
Couldn't we conditionally add this:
`new webpack.optimize.UglifyJsPlugin()` in the webpack plugins here: https://github.com/dcos/dcos-ui/blob/master/.webpack.config.js#L53
That should minify everything for us and we don't need gulp for it.
Then we can also remove this: https://github.com/dcos/dcos-ui/blob/master/gulpfile.js#L151
And we can move the css processing to webpack later.

What do you think?

**Comment by jfurrow** [comment]
@mlunoe I'm all for utilizing Webpack more than we are, but I don't think that should be done as part of this task.

**Comment by mlunoe** [comment]
Ok :)

**Comment by mesosphere-web** [comment]
Reviewer: @kennyt

**Comment by kennyt** [comment]
any idea why tests fail? I'd merge if they pass

**Comment by jfurrow** [comment]
@kennyt It's because I didn't disable `eslint` for this file 👎 

Fixed now!

**Comment by mlunoe** [comment]
Looks good to me!

**Pull request merged**
