### PR TITLE
Refactor ServicesTable status bar responsiveness

### PR DESCRIPTION
**Pull request by jfurrow**
Additional responsiveness refactoring for the `ServicesTable` status bar.

https://cl.ly/0G1p1j0D2F2N

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @kennyt

**Comment by pierlo-upitup** [comment]
retest this please

**Comment by mlunoe** [comment]
**mesosphere-ci** Retest this please

**Comment by mlunoe** [comment]
Works great! I really want this feature in! :shipit:

**Comment by mlunoe** [comment]
Rebased it off of latest master

**Pull request merged**
