### PR TITLE
Add eslint rule for should in tests

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
@orlandohohmeier did a PR to move the notation in tests away from `should`.
I wrote a small eslint plugin/rule to make sure we don't introduce these again 👍 

**Checklist**
- [ ] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by Poltergeist** [comment]
Please Rebase

**Comment by DanielMSchmidt** [comment]
@Poltergeist done 👍

**Comment by nLight** [comment]
please rebase on #2644 and bump `@dcos/eslint-config@0.3.0`

**Comment by DanielMSchmidt** [comment]
@nLight done 👍

**Comment by juliangieseke** [comment]
run all tests

**Comment by DanielMSchmidt** [comment]
run all tests

**Comment by nLight** [comment]
run system tests

**Comment by bstavroulakis** [comment]
run system tests

**Comment by Fabs** [comment]
I think the rebase, or something made the eslint-config vanish. This is the list of changed files changed:

```
M       npm-shrinkwrap.json
M       package.json
M       plugins/oauth/components/LoginPage.js
M       plugins/services/src/js/components/RecentOffersSummary.js
M       plugins/services/src/js/components/forms/ArtifactsSection.js
M       plugins/services/src/js/components/forms/ContainerServiceFormSection.js
M       plugins/services/src/js/components/forms/EnvironmentFormSection.js
M       plugins/services/src/js/components/forms/GeneralServiceFormSection.js
M       plugins/services/src/js/components/forms/HealthChecksFormSection.js
M       plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js
M       plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
M       plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
M       plugins/services/src/js/components/forms/NetworkingFormSection.js
M       plugins/services/src/js/components/forms/PlacementSection.js
M       plugins/services/src/js/components/forms/VolumesFormSection.js
M       plugins/services/src/js/components/modals/ServiceActionDisabledModal.js
M       plugins/services/src/js/constants/VolumeConstants.js
M       plugins/services/src/js/containers/service-configuration/__tests__/ServiceConfigurationContainer-test.js
M       plugins/services/src/js/containers/services/ServicesTable.js
M       plugins/services/src/js/service-configuration/ServiceStorageConfigSection.js
M       plugins/services/src/js/structs/__tests__/Volume-test.js
M       plugins/services/src/js/validators/__tests__/PlacementsValidators-test.js
D       scripts/find-broken-links
M       src/js/components/AccessDeniedPage.js
M       src/js/components/modals/CliInstallModal.js
M       src/js/config/Config.js
A       src/js/constants/Links.js
M       src/js/constants/UnitSummaries.js
M       src/js/pages/catalog/PackageDetailTab.js
M       src/js/schemas/job-schema/Schedule.js
M       system-tests/jobs/test-jobs.js
M       system-tests/services/test-apps.js
M       system-tests/services/test-environment.js
M       system-tests/services/test-pods.js
M       tests/_fixtures/marathon-1-task/app-version-1.json
M       tests/_fixtures/marathon-1-task/app-version-2.json
M       tests/pages/catalog/packages/PackagesTab-cy.js
M       tests/pages/nodes/NodesPage-cy.js
M       tests/pages/services/DeploymentsModal-cy.js
M       tests/pages/services/ServiceActions-cy.js
M       tests/pages/services/ServiceDetail-cy.js
M       tests/pages/services/ServiceExternalVolumes-cy.js
M       tests/pages/services/ServiceFormModal-cy.js
M       tests/pages/services/ServiceReviewScreen-cy.js
M       tests/pages/services/ServiceTable-cy.js
M       tests/pages/system/overview/repositories/AddRepositoryFormModal-cy.js
M       tests/plugins/tracking/TrackingPlugin-cy.js
M       tests/smoke-cy.js
M       webpack/plugins/svg-compiler-plugin.js
```

**Comment by DanielMSchmidt** [comment]
@Fabs The eslint config didn't change, because we added the rule to our base eslint config, as you can see in this commit: https://github.com/dcos/dcos-ui/pull/2638/commits/0bc1196292248f62cdebb629b9833024dc84dbad

**Comment by nLight** [comment]
run system tests

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
Hey @DanielMSchmidt do we have a respective PR for the plugins?

**Comment by DanielMSchmidt** [comment]
Not yet, will do one right now

Dmitriy Rozhkov <notifications@github.com> schrieb am Mo., 5. Feb. 2018 um
11:30 Uhr:

**Comment by DanielMSchmidt** [comment]
@nLight Yes, and it is already merged: https://github.com/mesosphere/dcos-ui-plugins-private/pull/718

**Comment by nLight** [comment]
run system tests

**Comment by Fabs** [comment]
Nice, now I understand the source of the plugins is this one.

**Pull request merged**
