### PR TITLE
refactor(system-tests): change cluster provisioning

### PR DESCRIPTION
**Pull request by nLight**
Adjust the system-tests driver configuration to use `dcos-launch` to
provision clusters.

### CODE REVIEW

**Comment by nLight** [comment]
run system tests

**Comment by brandonc** [comment]
Tell me more about the mesosphere-ci/github integration. I can't find a wiki page about it

**Comment by nLight** [comment]
@brandonc those should be all our jobs https://jenkins.mesosphere.com/service/jenkins/view/DCOS%20UI/ 
We're mostly running pipelines for 1.11 and 1.12 but for older releases we still use simple jenkins jobs.

**Comment by nLight** [comment]
run system tests

**Comment by nLight** [comment]
run system tests

**Comment by nLight** [comment]
soon to be dropped

**Pull request closed without merging**
