### PR TITLE
Yarrrn!!!

### PR DESCRIPTION
**Pull request by nLight**
It seems to be just working ¯\\_(ツ)_/¯

```bash
nvm use 4
npm i -g yarn
yarn
```

### CODE REVIEW

**Comment by mlunoe** [comment]
Rebased with latest master to get integration testes () passing

**Comment by mlunoe** [comment]
So the `npm scaffold` script moves the `npm-shrinkwrap.json` file around (@rcorral could you help me out, why was it you added that thing?), so that needs to change.
I also believe we need to change our CI configuration as well since we have pre-linked npm packages (not sure if that can just work with yarn).

**Comment by nLight** [comment]
@mlunoe much 💜  for rebasing it. @orlandohohmeier reported that `yarn` doesn't give a significant performance improvement. We could prioritize that one properly, since there's some work to be done.

**Comment by rcorral** [comment]
This is nice :)

There's lots of things to be done with this happening.
**Let's please let's do all of these things after we ship 1.9** cc/ @orlandohohmeier 

**Before merge**
- [ ] Check to see if we still need `fixShrinkwrap` task in gulp file. There's a comment in the file as to why we use it.
- [ ] Jenkins unit test build needs to be fixed
- [ ] Jenkins integration tests build needs to be fixed
- [ ] `Dockerfile.dev` needs to be updated
- [ ] `scripts/validate-engine-versions` needs updating
- [ ] Update relevant `scripts` in `package.json`
- [ ] Update `TESTING.md` file
- [ ] Update `README.md` file
- [ ] Update `webpack/modules/raml-validator-loader/README.md`
- [ ] Update `.travis.yml`

**After Merge**
- [ ] `build` file in Open DC/OS repo needs to be updated
- [ ] `build` file in Enterprise repo needs to be updated
- [ ] `cypress` file needs to be updated in `mesosphere/docker-images`

Fun stuff.

**Comment by mlunoe** [comment]
Going to close this as the PR/task seems stale

**Comment by nLight** [comment]
@mlunoe I agree, created an issue to track it https://mesosphere.atlassian.net/browse/DCOS-13171

**Pull request closed without merging**
