### PR TITLE
chore(reactjs-components): bump to 0.20.1

### PR DESCRIPTION
**Pull request by juliangieseke**
bump reactjs-components to the newest version including Modals and Select fixes

test: check this out and run `npm install` - if it passes, everything is ok 👍

### CODE REVIEW

**Comment by juliangieseke** [comment]
> Alfred — 346 tests run, 0 skipped, 29 failed. 

😭

**Comment by ahoskins** [comment]
@juliangieseke The `Confirm` modal change must be responsible for these...

**Comment by juliangieseke** [comment]
yes, I have cherrypicked a commit from lee in his PR: https://github.com/dcos/dcos-ui/pull/2485/commits/68ae48a41768be34162414088d12ee6c3828e10e
lets see if this helps. the remaining tests need to be fixed here manually :(

**Comment by juliangieseke** [comment]
@ahoskins Wow, thank you for picking this up! 
since it is my PR I cant review it, @orlandohohmeier @Poltergeist @bstavroulakis can we please get two rewviews from you guys? 🙇 👀

**Comment by juliangieseke** [comment]
Alfred test this please

**Comment by bstavroulakis** [comment]
Alfred please test this

**Pull request merged**
