### PR TITLE
Removing Destroy action for DCOS Frameworks

### PR DESCRIPTION
**Pull request by MatApple**
https://mesosphere.atlassian.net/browse/DCOS-9723

### CODE REVIEW

**Comment by rcorral** [comment]
You can still destroy from here
img

**Comment by rcorral** [comment]
could you point this PR to `master`?

**Comment by MatApple** [comment]
@rcorral good catch with dropdown in collection view. I'd rather not point it at master because it will be nearly as much work to resolve conflicts as doing this work itself ;)

**Comment by MatApple** [comment]
@rcorral fixed your catch.

**Pull request merged**
