### PR TITLE
DCOS-12279: Display product version in cluster configuration page

### PR DESCRIPTION
**Pull request by jfurrow**
This PR adds the version number to the cluster config screen.

### CODE REVIEW

**Comment by wavesoft** [comment]
Looks good! 👍 ✨

**Comment by rcorral** [comment]
run integration

**Comment by rcorral** [comment]
run integration

**Comment by mlunoe** [comment]
Rebased this for you with the integration test fix, so it should pass now.
Let's :shipit: once they do

**Comment by mlunoe** [comment]
run integration tests

**Comment by mlunoe** [comment]
run unit tests

**Comment by mlunoe** [comment]
run unit tests

**Pull request merged**
