### PR TITLE
DCOS-18082: adjust jest to disable automocking

### PR DESCRIPTION
**Pull request by orlandohohmeier**
---
⚠️  _This branch depends on changes that will be introduced with #2382 and #2383. For a list of changes please see: https://github.com/dcos/dcos-ui/compare/b8ef547...9106ba7_

---

Disable `automocking` to make it easier to write and maintain tests and remove obsolete `dontMockStore` util.

Closes DCOS-18082

### CODE REVIEW

**Comment by nLight** [comment]
Alfred retest this please

**Comment by nLight** [comment]
I saw a bunch of `jest.unmock` functions here and there. Should we delete them as well?

**Comment by orlandohohmeier** [comment]
@nLight yep, must have missed them...

**Comment by MatApple** [comment]
@orlandohohmeier please adjust plugins so they can be merged together. Adding `hold merge` but still approve.

**Comment by orlandohohmeier** [comment]
@MatApple 🤦‍♂️ I must have forgotten to open a PR...

**Pull request merged**
