### PR TITLE
[1.11] DCOS_OSS-4118: support minimal schema

### PR DESCRIPTION
**Pull request by nLight**
Backport of #3290

### CODE REVIEW

**Comment by Fabs** [comment]
Keeps loading forever:
https://cl.ly/5c2b14cc22a3

**Comment by Fabs** [comment]
Console:
image

**Comment by GeorgiSTodorov** [comment]
@Fabs you ran `npm install` right? I had a similar problem before running it.

**Comment by nLight** [comment]
@GeorgiSTodorov you are so right! When re-testing I also didn't!

**Comment by nLight** [comment]
ping @Fabs

**Pull request merged**
