### PR TITLE
Fix PageHeader icon size

### PR DESCRIPTION
**Pull request by jfurrow**

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @mlunoe

**Comment by kennyt** [comment]
tried it out. works great!

**Comment by jfurrow** [comment]
retest this please

**Comment by jfurrow** [comment]
retest this please

**Comment by jfurrow** [comment]
retest this please

**Comment by jfurrow** [comment]
Tests passing locally:

**Comment by jfurrow** [comment]
retest this please

**Pull request merged**
