### PR TITLE
DCOS-11688: Turn on prefer const eslint rule

### PR DESCRIPTION
**Pull request by nLight**
Nice Friday Pull-Request

### CODE REVIEW

**Comment by nLight** [comment]
retest this please

**Comment by nLight** [comment]
retest this please

**Comment by nLight** [comment]
This is so weird, don't get what Jenkins doesn't like here:
```
/jenkins/workspace/public-dcos-ui-pulls/plugins/services/src/js/containers/tasks/TasksView.js
  185:15  error  Expected indentation of 12 space characters but found 14  react/jsx-indent
  186:15  error  Expected indentation of 12 space characters but found 14  react/jsx-indent
```
There are even no jsx on these lines, and it is green locally

**Comment by Poltergeist** [comment]
@nLight Jenkins is using the merged version so this would happen if we merge this to master.

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Comment by nLight** [comment]
run integration

**Comment by nLight** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
**mesosphere-ci** run integration tests 🙈

**Comment by orlandohohmeier** [comment]
**mesosphere-ci** retest this please 🙏

**Comment by orlandohohmeier** [comment]
**mesosphere-ci** retest this please 🙏

**Comment by mlunoe** [comment]
Rebased to get integration testes () passing

**Comment by mlunoe** [comment]
One more try

**Comment by nLight** [comment]
Much 💜  guys! 💪

**Pull request merged**
