### PR TITLE
Don't force environment variable names to uppercase in service create form

### PR DESCRIPTION
**Pull request by philipnrmn**
ℹ️  this is a PR for the 1.8 release branch; you'll need to `npm i` and checkout appropriate plugins. 

This is a squashed reversion of #1023, which forced environment variable names to uppercase in the service form.

The user's specified environment variable case is now respected, as in current master.

### CODE REVIEW

**Comment by rcorral** [comment]
run unit tests

**Comment by MatApple** [comment]
run integration tests

**Comment by MatApple** [comment]
Ahhh 1.8 PR but no milestone/label. How are we tracking 1.8 PRs now @rcorral?

**Comment by rcorral** [comment]
Integration tests won't pass for 1.8 PRs. I just added the milestone.

**Comment by MatApple** [comment]
👌  I re-ran them before I realized it was a 1.8 patch 👍

**Comment by philipnrmn** [comment]
sorry about the lack of milestone - my bad. Thanks for the speedy merge 🚤

**Pull request merged**
