### PR TITLE
Move service schema to config directory

### PR DESCRIPTION
**Pull request by Poltergeist**
This PR moves the service schema files to the ~~`config`~~ `schemas` directory and also uses the new title attribute. Finally the `Container Settings` do also get their own file.

Depends on the fix in #331 to work.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @pierlo-upitup

**Comment by Poltergeist** [comment]
@mesosphere-ci retest this please

**Comment by aldipower** [comment]
In my opinion the config-directory is reserved for application-wise configurations like the config.dev.js.
Putting a scheme into the config-dir I think we mix the things up.
Calling it `schemes` would be much moar obvious to me. :)

**Comment by aldipower** [comment]
The title-attr is great btw! :)

**Comment by pierlo-upitup** [comment]
I agree with @aldipower – `config/` does not strike me as being the right place for this.

**Comment by Poltergeist** [comment]
I addressed the concerns about the config directory and moved the files to a new directory called `schemas`. My idea is to have a sub directory for each schema and a main file in the `schemas` directory itself
```
schemas
  |__ ServiceSchema.js
  |__ service-schema/
      |__ general.js

**Comment by pierlo-upitup** [comment]
retest this please

**Comment by aldipower** [comment]
:+1:

**Pull request merged**
