### PR TITLE
Improve visual hierarchy in new service config and review screens

### PR DESCRIPTION
**Pull request by leemunroe**
With the new CNVS update and UI Kit alignment we've decided to focus on using h1,h2,h3.

This PR updates the headings in the run service flow and review screens. It also fixes other minor bugs.

* H2s > H1s
* H3s > H2s
* H4s > H3s
* Fixed cancel button alignment on dismiss alert
* Fixed uppercase placement labels

It does not fix the hierarchy issues with package configuration (this is slightly more complicated and will be tracked separately).

Before

image
image
image
image

After
image
image
image
image

### CODE REVIEW

**Comment by ahoskins** [comment]
alfred test this please

**Comment by DanielMSchmidt** [comment]
Alfred test this please :)

**Comment by juliangieseke** [comment]
Alfred test this

**Comment by juliangieseke** [comment]
run integration tests

**Comment by DanielMSchmidt** [comment]
I looked in the integration tests, one failed because the Unique option could not be selected on the placement constraints page and the other one failed as the service dropdown could not be opened. I think it is just because of flakiness

**Comment by DanielMSchmidt** [comment]
Run integration tests

**Comment by DanielMSchmidt** [comment]
This error occured twice: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests-integration/34/ (`back button on review screen goes back to form.Service Actions Edit Action back button on review screen goes back to form
`)

**Comment by DanielMSchmidt** [comment]
Run integration tests

**Comment by DanielMSchmidt** [comment]
Same test fails again, suspicious 🤔 https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests-integration/37/

**Comment by DanielMSchmidt** [comment]
Run integration tests

**Pull request merged**
