### PR TITLE
DCOS-20222: add error for environment values without keys

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
## Testing

- Go to the pods / service form
- Go to the environment section
- Create a label without a key
- See that it is shown as an error

## Trade-offs

None that I am aware of

## Dependencies

None

## Screenshots

bildschirmfoto 2018-09-03 um 12 03 57

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
@Poltergeist Fixed that 👍

**Comment by natmegs** [comment]
I'm guessing this is out of scope for this ticket, but it looks like this is handled differently for environment variables, labels, and secrets. Labels without a key don't get added to JSON (no error), secrets with only Variable Name get assigned a random (?) secret value in JSON. Is this intentional?
environment

**Comment by DanielMSchmidt** [comment]
@natmegs Yes, but you are right. I will create two small issues for that cause 👍

**Comment by DanielMSchmidt** [comment]
@nLight @Poltergeist Could you have another look?

**Pull request merged**
