### PR TITLE
[Backport:1.11] DCOS-21122: fix(ServiceForm): fixes focus/change/blur behaviour

### PR DESCRIPTION
**Pull request by Poltergeist**
---

ℹ️ Backport of: #2761  

---

This ~commit~ PR changes the onChange handler of the ServiceForm so that
it no longer implicitly sets state.editingFieldPath, instead a new
internal function `handleFormFocus` is introduced.

Closes DCOS-21122

### CODE REVIEW

**Comment by Poltergeist** [comment]
LGTM! 👍

**Comment by juliangieseke** [comment]
integration tests were green 👍 
https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests-integration/640/

**Comment by nLight** [comment]
@juliangieseke did you change anything to make them green?

**Comment by juliangieseke** [comment]
yes, i had to fix the tests, see commit message and:
https://github.com/dcos/dcos-ui/pull/2772/files#diff-0796ef68862d3b5d45e239ff56ee5be7R994, 
https://github.com/dcos/dcos-ui/pull/2772/files#diff-d54799ec9bd45b564a6c8d09458706fb and 
https://github.com/dcos/dcos-ui/pull/2772/files#diff-01382146b0071328e199fe6bff580fcd

**Comment by juliangieseke** [comment]
hm, the first one slipped into the wrong commit :(

**Comment by juliangieseke** [comment]
^ fixed, hopefully jenkins isnt acting up again 🤞

**Pull request merged**
