### PR TITLE
Fix incorrect job detail status text color

### PR DESCRIPTION
**Pull request by jfurrow**

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @daiyiwhale

**Comment by daiyiwhale** [comment]
Yay!! I found another one though (': https://github.com/dcos/dcos-ui/blob/master/src/js/pages/jobs/JobRunHistoryTable.js#L169

**Comment by daiyiwhale** [comment]
also: https://github.com/dcos/dcos-ui/blob/master/src/js/pages/jobs/JobRunHistoryTable.js#L184

**Comment by MatApple** [comment]
After @daiyiwhale's comments, 🚢

**Comment by jfurrow** [comment]
@daiyiwhale Good catch Chris, fixed!

**Pull request merged**
