### PR TITLE
[4 of n: Icons] Implement sidebar icons

### PR DESCRIPTION
**Pull request by jfurrow**
This PR introduces the sidebar icons. It also removes the logic in the sidebar which rendered both SVG icons and sprited icons, and fixes the opacity that was previously applied to the sprited icons.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @philipnrmn

**Comment by jfurrow** [comment]
Passing locally:

**Comment by rcorral** [comment]
rebase please!

**Comment by jfurrow** [comment]
@rcorral Rebased!

**Pull request merged**
