### PR TITLE
DCOS-15287: Add checks to verify marathon response (pods)

### PR DESCRIPTION
**Pull request by juliangieseke**
Add additional checks to verify that the Marathon response is as expected. To do so the test will open the service detail, hit edit and check the form content.

### CODE REVIEW

**Comment by juliangieseke** [comment]
The failing test (enviroment variables) is related to an Marathon Issue, I'm not sure if there is already a Ticket or PR somewhere.

**Comment by rcorral** [comment]
@juliangieseke what do you mean Ticket or PR somewhere?
I'm trying to understand why these are failing.

**Comment by juliangieseke** [comment]
@rcorral JIRA Ticket

**Comment by Poltergeist** [comment]
run integration tests

**Comment by tnguyen0** [comment]
Run integration tests

**Pull request merged**
