### PR TITLE
DCOS-19403: refactor(ExternalVolumes): remove External Volumes

### PR DESCRIPTION
**Pull request by Poltergeist**
Based on #2560 
Remove External Volumes form section, reducers and parsers

Closes DCOS-19403

### CODE REVIEW

**Comment by Poltergeist** [comment]
Will look into the test tomorrow morning.

**Comment by ahoskins** [comment]
I removed the `test-external-volumes` system tests and the external volumes section from `ServiceFormModal-cy`. @Poltergeist I believe it was right of me to remove these files, rather than refactor/rewrite the tests?

**Comment by Poltergeist** [comment]
We still want to test external Volumes but I had to alter the test case a little.

**Comment by Poltergeist** [comment]
Did you check on master if it is a problem there as well?

**Comment by juliangieseke** [comment]
yes, its broken on master - not related to your PR.

**Pull request merged**
