### PR TITLE
fix: don't error on pageNotFound

### PR DESCRIPTION
**Pull request by pierrebeitz**
problem: navigate `http://localhost:4200/#/dashboard123` and see the app crashing.

fix: not registering things multiple times on the MountService. it looks like this was the only place we chose to dynamically register a component and relied on the header only being instantiated once.

TODO: follow up with an integration test, making sure PageNotFound is correctly rendered when a page is not found...

### CODE REVIEW

**Comment by pierrebeitz** [comment]
yep, totally!

**Comment by GeorgiSTodorov** [comment]
@pierrebeitz , do you want to add it or should I?

**Comment by GeorgiSTodorov** [comment]
This doesn't work for the login page. Is this expected?
Screenshot from 2019-09-02 10-44-53

**Comment by GeorgiSTodorov** [comment]
Cypress fails whenever I try to visit a non-existing url.

**Comment by pierrebeitz** [comment]
oh boy. the issue seems complicated now. 

open questions: 
* does this also happen on master? 
* do we need to test every react-router-`path` for whether it breaks or not?
* doesn't `react-router` have a feature to just render a not-found? we seem to have a "catchall" in `routes/index.js`.

**Comment by GeorgiSTodorov** [comment]
It does also happen on master. I don't know the answer to the two other questions. My own question would be if we are okay with only fixing it for some pages.

**Comment by pierrebeitz** [comment]
i'd vow to merge this as i'm really sure it's a simplification over the previous state and less error prone AND file a jira to resolve the bad behaviour we're seeing here.

**Pull request merged**
