### PR TITLE
Create ClipboardTrigger component

### PR DESCRIPTION
**Pull request by kennyt**
gf

Everything works the same. It is now a component that can be reused.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @jfurrow

**Comment by kennyt** [comment]
i have no idea why integration tests are failing. due to a timeout. i've reran multiple times

**Comment by mlunoe** [comment]
retest this please

**Comment by mlunoe** [comment]
Works beautifully! You need to rebase though, I think it is failing because it has old modules in it.
At least that's what worked for me to test this out

**Pull request merged**
