### PR TITLE
Prevent vertical tab menu from shrinking and increase its width

### PR DESCRIPTION
**Pull request by jfurrow**
This PR prevents the vertical tabbed menu from shrinking and increases its width.

### CODE REVIEW

**Comment by jfurrow** [comment]
retest this please

**Comment by nLight** [comment]
Rebased that for you, works! ✨

**Comment by Poltergeist** [comment]
LGTM Merge after 💚 💡 !

**Comment by orlandohohmeier** [comment]
**mesosphere-ci** retest this please 🙏

**Pull request merged**
