### PR TITLE
DCOS-12436: Adding missing content to networking pages

### PR DESCRIPTION
**Pull request by mlunoe**
Fixes DCOS-12436 and DCOS-12438

EDIT: The `Types` have been moved from here^

### CODE REVIEW

**Comment by mlunoe** [comment]
Adding hold merge until I get an approval from the designers about having `Type` in there or not.

**Comment by mlunoe** [comment]
This is confirmed by @silverem2

**Comment by mlunoe** [comment]
Run integration tests

**Comment by jfurrow** [comment]
:ship:

**Pull request merged**
