### PR TITLE
refactor(githooks): move and improve post-checkout checks into validate-engines

### PR DESCRIPTION
**Pull request by juliangieseke**
the current version of this check complains about node version 9.x being incorrect (it needs 8.9.4). this fixes this issue and also moves the checks into our validate-engines script.

to test this, please checkout this branch with latest node version (should NOT complain), then downgrade node to v4 and try `npm start` (should complain)

### CODE REVIEW

**Comment by ahoskins** [comment]
@juliangieseke When using nvm, it does not have an issue with me using node 4.4! When reading the script itself, this makes sense. I think we have to modify the assertions a bit.

**Comment by juliangieseke** [comment]
Yay! Even better, having `npm` as devDependency also installs the correct version locally! this means it _doesnt matter at all_ which version is installed on our machines. 🎉 

check this:
```
# Julian@Cookie:~/Code/dcos-ui/master/dcos-ui (jgieseke/improve-version-check *$%=)
$ node -v
v4.4.7
# Julian@Cookie:~/Code/dcos-ui/master/dcos-ui (jgieseke/improve-version-check *$%=)
$ npm -v
3.9.6
# Julian@Cookie:~/Code/dcos-ui/master/dcos-ui (jgieseke/improve-version-check *$%=)
$ npm run versions

> dcos-ui@1.1.14 versions /Users/Julian/Code/dcos-ui/master/dcos-ui
> echo npm $(npm --version) && echo node $(node --version)

npm 5.6.0
node v8.9.4
```

**Comment by DanielMSchmidt** [comment]
@ahoskins I think when you use nvm you need to open a new tab to have the right version. Like this: 
node

**Comment by ahoskins** [comment]
screen shot 2018-03-13 at 11 08 02 am

**Comment by DanielMSchmidt** [comment]
Strange, might be my shell. It's fish

**Comment by juliangieseke** [comment]
@ahoskins was right, it didnt complain. see my comment above, now it is even better :)
@ahoskins pls re-review 👍

**Comment by ahoskins** [comment]
I re-installed node_modules, and then used node 4.4.7, and still no error...

**Comment by ahoskins** [comment]
It's interesting what's happening here. So I switch my global node 4.4 successfully. Then if you notice, my PATH doesn't include node_modules/bin. But then, when invoking the script, it appends .node_modules/bin to my path, causing it to use the correct node version in the script. 

image 2018-03-14 at 4 37 54 pm

**Pull request merged**
