### PR TITLE
DCOS-6609: Fix clipped text in dashboard panel list items

### PR DESCRIPTION
**Pull request by jfurrow**

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @rcorral

**Comment by mlunoe** [comment]
Nice work! :shipit:

**Comment by mlunoe** [comment]
Dang, forgot to check integration tests. After merging these are failing:

**Comment by mlunoe** [comment]
Pr for fixing integration tests opened here: https://github.com/dcos/dcos-ui/pull/102

**Pull request merged**
