### PR TITLE
Fixing broken forcePullImage tests in Container-test

### PR DESCRIPTION
**Pull request by mlunoe**
---
ℹ️ My hunch is that the problem was introduced here: https://github.com/dcos/dcos-ui/pull/1762

---

This PR fixes some broken tests on master revolving around forcePullIImage

### CODE REVIEW

**Comment by mlunoe** [comment]
Retest this please

**Comment by mlunoe** [comment]
Run integration tests

**Comment by mlunoe** [comment]
Run integration tests

**Comment by jfurrow** [comment]
Works as described 👍

**Comment by philipnrmn** [comment]
Thanks @mlunoe!

**Pull request merged**
