### PR TITLE
DCOS-13445: Rename Cluster to System Overview

### PR DESCRIPTION
**Pull request by jfurrow**
This PR renames `Cluster` to `System Overview` throughout the app.

Before: Imagine the word "Cluster"
After: Now imagine the words "System Overview" :trollface: 

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by nLight** [comment]
retest this please 🍬

**Comment by nLight** [comment]
I think rebase will make this 🔴  go away

**Comment by nLight** [comment]
run unit tests

**Comment by jfurrow** [comment]
@MatApple Rebased!

**Pull request merged**
