### PR TITLE
Adjust multiple-form headings

### PR DESCRIPTION
**Pull request by jfurrow**

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @kennyt

**Comment by kennyt** [comment]
if the heading has a tooltip, then it'll be off balance:

px

**Comment by jfurrow** [comment]
Fixed:

**Comment by kennyt** [comment]
tried it out. works great!

**Comment by jfurrow** [comment]
retest this please

**Comment by mlunoe** [comment]
Feel free to merge once tests pass :) 👍

**Comment by kennyt** [comment]
retest this please

**Comment by kennyt** [comment]
retest this please

**Comment by jfurrow** [comment]
Tests passing locally:

**Pull request merged**
