### PR TITLE
[7 of 8: Service Updates & Upgrades] Add a constant that renders human-readable status text

### PR DESCRIPTION
**Pull request by jfurrow**

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @philipnrmn

**Comment by daiyiwhale** [comment]
Looks good! ⛵

**Comment by philipnrmn** [comment]
🐑

**Comment by kennyt** [comment]
i wonder why this has `7 of 8` because this seems like it doesn't depend on anything. can we merge this?

**Comment by jfurrow** [comment]
@kennyt To avoid rebase hell, none of these `[n of 8]` PRs have any code from their predecessors.

**Pull request merged**
