### PR TITLE
Breadcrumbs not functioning properly after routes got changed, ref. DCOS-11768 and DCOS-12143

### PR DESCRIPTION
**Pull request by mlunoe**
This PR fixes a bug where the Breadcrumbs where removed from the file viewer here: https://github.com/dcos/dcos-ui/commit/ba2595e15c200cd3f26cbf25455ecbb9a8e2e15c#diff-5652f87ace9e089ce90959891680d61dL331

It also corrects how the breadcrumbs work when navigating files:

### CODE REVIEW

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
run integration tests

**Comment by rcorral** [comment]
run integration tests

**Comment by mlunoe** [comment]
Rebased this guy, so it now has the integration test fix, that landed in master

**Comment by wavesoft** [comment]
Looks good! ✨ 👍 
Possibly unrelated, but the URL never changes when you navigate between files. Is this expected?

**Comment by nLight** [comment]
@wavesoft that could be a feature request, personally would love to have it, would you create an improvement JIRA for that? 

But since 1.8 UI also doesn't change the URL I decided to hit that button.

**Comment by mlunoe** [comment]
Thanks guys. Yes, there is definitely room for improvement, but I'd agree that that would be a separate task 👌🏼

**Pull request merged**
