### PR TITLE
Adding node and npm version check

### PR DESCRIPTION
**Pull request by mlunoe**
This check will run on `npm preinstall` and `npm start`

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @aldipower

**Comment by mlunoe** [comment]
Hmmm... didn't actually work, since this is a hard restriction:


Come to think of it, it might be too strict. Will look into that

**Comment by MatApple** [comment]
@mlunoe I still maintain that we shouldn't be focussing on this for now :)

**Comment by MatApple** [comment]
Going to close this PR till we have some bandwidth to re-evaluate.

**Pull request closed without merging**
