### PR TITLE
DCOS-18980: Update Typography to match UI Kit

### PR DESCRIPTION
**Pull request by ashenden**
The DC/OS UI Kit has made improvements and adjustments to the appearance of typography. This PR seeks to update the styles in the DC/OS UI codebase to mirror these changes. Notable changes include:
* Overriding CNVS variables for `h1` to match UI Kit
* Overriding CNVS variables for `h2` to match UI Kit
* Overriding CNVS variables for `h3` to match UI Kit
* Excluding CNVS `h4` type styles
* Excluding CNVS `h5` type styles
* Excluding CNVS `h6` type styles
* Moving all typographic styles out of the `/components` directory and into the `/content` directory.

**WARNING:** It is advised that we first merge PR #2452 prior to merging this PR.

Throughout the app there a many type regressions from the changes in the PR. This will all be adjust in subsequent PRs, and all addressed prior to merging the larger feature branch feature/DCOS-18977-ui-kit-consistency

### CODE REVIEW

**Comment by nLight** [comment]
Alfred test this

**Comment by ashenden** [comment]
@mesosphere-mergebot test

**Comment by ashenden** [comment]
retest this please

**Comment by ahoskins** [comment]
I'm sure you're aware @ashenden , but this is the biggest regression I see. This expands to fill all the width:
screen shot 2017-10-18 at 1 26 18 pm

**Comment by ashenden** [comment]
Thanks @ahoskins. We're aware and have noted the wide-screen look for the create flow.  This is something that will be fixed in future PRs prior to merging anything to `master`.

**Comment by nLight** [comment]
Hold merge before #2452 is merged

**Comment by MatApple** [comment]
alfred retest this please

**Comment by MatApple** [comment]
alfred retest this please

**Pull request merged**
