### PR TITLE
Show service not found

### PR DESCRIPTION
**Pull request by kennyt**
px

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @Poltergeist

**Comment by rcorral** [comment]
@kennyt could you add a simple integration test for this.

**Comment by kennyt** [comment]
integration test added

**Comment by rcorral** [comment]
I can't figure out why the tests are failing though. 
Could you also post a screenshot of the integration tests passing please?

**Comment by kennyt** [comment]
@rcorral it was failing because i left a `.only` in there

**Comment by kennyt** [comment]
@rcorral px

**Comment by rcorral** [comment]
Awesome work! Thanks for taking this on 🚀

**Pull request merged**
