### PR TITLE
Uninstall 04 | Remove unnecessary inactive delete modal areas

### PR DESCRIPTION
**Pull request by bstavroulakis**
Remove unnecessary inactive delete modal areas since all of these are handled now in the Uninstall modal.
Related to #2402 

**Checklist**
- [ ] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by weblancaster** [comment]
https://media.giphy.com/media/l3q2FZFDqFmK8fkuA/giphy.gif

**Comment by weblancaster** [comment]
blessed

**Comment by MatApple** [comment]
@bstavroulakis I hope you don't mind but I rebased this for you because I merged `03` and it caused build errors on this PR due to the change in package dependencies in `03`. @weblancaster can you please add your review again since it was dismissed?

**Comment by bstavroulakis** [comment]
@MatApple Good idea! I rebased 05 Uninstall as well.
@weblancaster One tick again since we rebased so we can merge :)

**Pull request merged**
