### PR TITLE
Change jest config to generate Cobertura coverage reports

### PR DESCRIPTION
**Pull request by orlandohohmeier**
Explicitly configure `coverageReporters ` to include the defaults  ("json", "lcov", "text") as well as `cobertura` to generate Cobertura coverage reports. This change will allow us to collect and publish code coverage metrics in Jenkins.

Closes DCOS-16515

### CODE REVIEW

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
Are we going to start collecting coverage with `'collectCoverage': true` in a separate PR? I tried that option and there's no way we have it in dev env it is sooooooo sloooooow.

**Comment by nLight** [comment]
File          |  % Stmts | % Branch |  % Funcs |  % Lines |
---------|----------|----------|----------|----------|
All files   |     82.5 |    71.46 |    76.23 |    77.85 |
 
Not that bad actually

**Comment by orlandohohmeier** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
@nLight I will adjust out unit test job to generate the report (`npm run test  -- --converage`) and use Jenkins to collect and publish code coverage metrics.

**Pull request merged**
