### PR TITLE
Update the pre-commit hook

### PR DESCRIPTION
**Pull request by orlandohohmeier**
Update the `pre-commit` to only lint staged files.

### CODE REVIEW

**Comment by wavesoft** [comment]
Debug details:

```
+ source .git/hooks/utils/git
.git/hooks/pre-commit: line 4: .git/hooks/utils/git: No such file or directory
+ source .git/hooks/utils/message
.git/hooks/pre-commit: line 5: .git/hooks/utils/message: No such file or directory
+ title 'Run pre-commit hook...'
.git/hooks/pre-commit: line 7: title: command not found
++ get_staged_files_with_name '*.js'
.git/hooks/pre-commit: line 10: get_staged_files_with_name: command not found
+ staged_javascript_files=
+ '[' -n '' ']'
++ get_staged_files_with_name '*.less'
.git/hooks/pre-commit: line 19: get_staged_files_with_name: command not found
+ staged_less_files=
+ '[' -n '' ']'
On branch orlandohohmeier/refactor/pre-commit
```

**Comment by orlandohohmeier** [comment]
@wavesoft I've addressed the import issues...

**Comment by wavesoft** [comment]
Nice ✨  I always love color on the terminal 😄

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Comment by Poltergeist** [comment]
This is not touching any tests, so the maybe failing tests are not connected to this PR, as this PR is approved by 2 people I will now merge it.

**Pull request merged**
