### PR TITLE
feature (ServiceActionDisabledModal) Moves copy text to icon

### PR DESCRIPTION
**Pull request by rcorral**
This PR removes the "copy" text to copy a command and instead adds an icon to do this. This was a request from the Design team. I've gone over it with them and gotten sign-off on the implementation.

**Before**
gif

**After**
gif

**Checklist**
- [ ] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by MatApple** [comment]
@rcorral - flicts!

**Comment by jfurrow** [comment]
Works great!

**Comment by weblancaster** [comment]
LGTM when the tests all passed. I have made a change to remove css specificity.

**Comment by nLight** [comment]
✅  x 2 + CI is 🍏  = Merge

**Pull request merged**
