### PR TITLE
Fix ServiceActions integration tests

### PR DESCRIPTION
**Pull request by MatApple**
Fixed and faster.

### CODE REVIEW

**Comment by rcorral** [comment]
run integration

**Comment by rcorral** [comment]
run integration

**Comment by rcorral** [comment]
run integration

**Comment by rcorral** [comment]
run integration

**Comment by rcorral** [comment]
@MatApple your integration tests have legit failures

**Comment by mlunoe** [comment]
One will be fixed by a rebase from master

**Comment by MatApple** [comment]
@rcorral @mlunoe should have fixed that test related to `ServiceActions-cy`. It worked locally but think because the timing for checking when disabled/not disabled was a little flaky for the button, it wasn't reliable.

**Comment by jfurrow** [comment]
Works great for me!

**Pull request merged**
