### PR TITLE
Added Product Icon SVGs

### PR DESCRIPTION
**Pull request by ashenden**
Added the product icon SVGs.  I have not applied them in Product.  You will need to do that either as another commit on this branch, or do a separate PR once you are comfortable they work.  Would be worth doing a quick text on them before merging this branch, so I can make any needed edits directly on this branch/PR.

### CODE REVIEW

**Comment by jfurrow** [comment]
I implemented them for the sidebar:

**Comment by jfurrow** [comment]
I'm adding `hold merge` until I update the renamed icon IDs.

**Comment by jfurrow** [comment]
*mesosphere-ci* retest this please

**Comment by MatApple** [comment]
I'm seeing a warning

**Comment by MatApple** [comment]
Also looks like not all the icons have been updated? Missing the jobs icon here.

**Comment by jfurrow** [comment]
@MatApple Added back the `hold merge` label, @ashenden is making some edits here :)

**Comment by MatApple** [comment]
Ok thanks @jfurrow

**Comment by MatApple** [comment]
Also think the sidebar should automatically collapse again when you click on a menu item.

**Comment by jfurrow** [comment]
@MatApple yeah I could see that being desirable, what do you think @ashenden?

**Comment by rcorral** [comment]
retest this please

**Pull request merged**
