### PR TITLE
Re-enable sane eslint rules

### PR DESCRIPTION
**Pull request by nLight**
ℹ️  I deleted _overrides_, which effectively switched them to the `error`mode.

This PR re-enables a set of sane eslint rules and fixes respective code.
It's 88 files but rather straightforward.

🙇

### CODE REVIEW

**Comment by nLight** [comment]
PR bot knows whom to assign @orlandohohmeier :trollface:

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
@jfurrow

**Comment by jfurrow** [comment]
Great work @nLight!

**Pull request merged**
