### PR TITLE
Reenable a disabled test

### PR DESCRIPTION
**Pull request by MatApple**

### CODE REVIEW

**Comment by nLight** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
L👀ks good! Feel free to merge once the integration test pass on jenkins as well...

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
run integration tests

**Comment by Poltergeist** [comment]
Passes locally. Let's merge.

**Pull request merged**
