### PR TITLE
[2 of 3: Mobile Page Header Navigation] Separate page header navigation styles

### PR DESCRIPTION
**Pull request by jfurrow**
~~1 of 3: #1850~~
2 of 3: #1872
3 of 3: #1873

This PR simply separates the styles for the page header navigation from the rest of the page header styles, as it was getting a little unruly.

### CODE REVIEW

**Comment by MatApple** [comment]
@jfurrow flicts! :)

**Comment by jfurrow** [comment]
@MatApple I think I'll wait until 1 of 3 merges before fixing this up if you don't mind!

**Comment by mlunoe** [comment]
Still flicts!

**Comment by jfurrow** [comment]
@mlunoe Flicts fixed!

**Comment by mlunoe** [comment]
I don't think #1850 has been rebased off the same point, so the diff includes a lot more than it should, which makes it harder to review.

**Comment by mlunoe** [comment]
But looking at the complete change to master actually makes sense. The base PR makes sense and this PR makes sense

**Comment by jfurrow** [comment]
@mlunoe I'm not sure why the diff links are not working properly, but they are all rebased off one another and contain the same commits. Perhaps something went awry when I rebased them...

**Comment by jfurrow** [comment]
Ping @mlunoe @MatApple Since 1 of 2 merged this should be a lot easier to review :)

**Comment by mlunoe** [comment]
Yup, my label persists!

**Comment by jfurrow** [comment]
Sorry @mlunoe for some reason I didn't think you had added your label... thanks :)

**Pull request merged**
