### PR TITLE
DCOS-14972: Enable dot separated values in Cypress tests

### PR DESCRIPTION
**Pull request by nLight**
All I did was enabling `TODO: Due to a bug in cypress you cannot type values with dots` everything else is prettier.

## Testing

CI should pass

Closes DCOS-14972

### CODE REVIEW

**Comment by Poltergeist** [comment]
How can we move this one forward @nLight ?

**Comment by nLight** [comment]
Rebase, review and merge :)

**Comment by Poltergeist** [comment]
on it.

**Comment by DanielMSchmidt** [comment]
⚔️ Conflicts

**Comment by nLight** [comment]
@pierrebeitz 🙇

**Pull request merged**
