### PR TITLE
chore(CI): add check for .only on CI

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Closes DCOS-47525

## Testing

- Open a PR based on this one
- Add a ‘it.only‘ in a test case
- The CI should fail

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
This is how it should be, right?
screenshot from 2019-01-22 11-13-45

**Comment by DanielMSchmidt** [comment]
Wow, great catch @GeorgiSTodorov 

It seems like we had already build what we wanted to build in this JIRA :D 
Having an overview over big systems is hard I guess 🤷‍♂️

**Comment by GeorgiSTodorov** [comment]
So the error was not because of this branch?

**Comment by DanielMSchmidt** [comment]
Nope, this branch should have failed before.

**Pull request closed without merging**
