### PR TITLE
Feature: Add Dialog component

### PR DESCRIPTION
**Pull request by Poltergeist**
This adds a Dialog component which wraps the Modal component,

You may add buttons with css `classNames` and `onClick` handler and `text` Also a `title` can be set with a prop and the `severity` which is based on the Constants, `info`, `warning` and `danger`.

This PR does only contain the component and only a basic styling (removing grey footer and header). 

Sorry for the Size of this PR, but 🎆 260 lines are tests 🎉 

image

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @pierlo-upitup

**Comment by rcorral** [comment]
@Poltergeist could we see some screenshots of what these Dialogs look like?

**Comment by Poltergeist** [comment]
I added a screenshot as mentioned in the description there has been no css added yet.

**Comment by rcorral** [comment]
It looks very similar to the Confirm Modal we already have in reactjs components.
http://mesosphere.github.io/reactjs-components/#confirm

Any chance we can use that or add more options to it?

**Comment by pierlo-upitup** [comment]
As @rcorral said, what I see in the PR doesn't justify the creation of a new Dialog component that replicates the already existing Confirm component. I'm closing this – please re-open if I missed something, @Poltergeist .

**Pull request closed without merging**
