### PR TITLE
Add deploy service methods to marathon store

### PR DESCRIPTION
**Pull request by Poltergeist**
Introduction of the createService action which posts an app definition to marathon. And notifies the store of a successful or unsuccessful POST request.

The store emits in both cases an event which will be picked up by a later component and then either closes a modal or displays the error.

This is a dependency for #212

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @kennyt

**Comment by pierlo-upitup** [comment]
I'd like to see some (basic) unit tests that we can later improve

**Comment by kennyt** [comment]
looks good. needs simple tests

**Comment by Poltergeist** [comment]
Basic testing has been added.

**Comment by pierlo-upitup** [comment]
LGTM

**Comment by jfurrow** [comment]
:ship:

**Pull request merged**
