### PR TITLE
accurate status follow up

### PR DESCRIPTION
**Pull request by pierrebeitz**
# Reviewing / Testing

i suggest reviewing commit by commit. 
* i looked at constants-files and investigated whether they are used anymore. 
* i think the CSS-class `service-running-state` is obsolete. if it is everything `StatusMapping`-related is as well (thus it has been removed). 
* `subTitleClassName` then followed along `StatusMapping`, having no place of usage anymore.
* the other changes should mostly be cosmetics (ES6-syntax, im- and exports, stuff like that)

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
@pierrebeitz , I see 17 commits, you gave testing instructions for only two.

**Comment by pierrebeitz** [comment]
@GeorgiSTodorov i rebased and updated the instructions. this is not a priority though.

**Comment by GeorgiSTodorov** [comment]
@pierrebeitz , a conflicting file.

**Comment by pierrebeitz** [comment]
resolved, please re-review.

**Comment by mperrotti** [comment]
@pierrebeitz - file conflicts

**Comment by pierrebeitz** [comment]
resolved, please re-review

**Pull request merged**
