### PR TITLE
DCOS-41059: Deleting groups in Services has a misleading message

### PR DESCRIPTION
**Pull request by GeorgiSTodorov**
Added "or groups" to make delete message more accurate.

Closes https://jira.mesosphere.com/browse/DCOS-41059

## Testing
1. Go to services tab
2. Create a group
3. Create a group inside that group
4. Try to delete the first group
5. See the message that appears.

## Trade-offs
None.

## Dependencies
None.

### Before
screenshot from 2018-12-07 12-21-14

### After
screenshot from 2018-12-07 11-45-21

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
File conflicts in messages catalog. Not sure what our policy is.

**Comment by natmegs** [comment]
Same feedback as other PRs - let's revert any manual changes to message catalogs and update them using `npm run lingui-extract-with-plugins` for consistency

**Comment by GeorgiSTodorov** [comment]
Updated.

**Comment by nLight** [comment]
flicts

**Comment by GeorgiSTodorov** [comment]
Updated message catalog format, please take another look when you have time.

**Pull request merged**
