### PR TITLE
-> [Store config 2 of 4] MarathonStore, MesosLogStore, MesosSummaryStore, MetadataStore, MetronomeStore

### PR DESCRIPTION
**Pull request by mlunoe**
This PR moves registering of stores their respective constructors instead of it being handled in StoreConfig.

Functionally there is no change from this PR.
Includes the following stores:
- MarathonStore
- MesosLogStore
- MesosSummaryStore
- MetadataStore
- MetronomeStore

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @pierlo-upitup

**Comment by jfurrow** [comment]
Works great, nice work!

**Comment by philipnrmn** [comment]
[Tiny style issue](https://github.com/dcos/dcos-ui/pull/840#discussion_r72716481), then feel free to merge

**Pull request merged**
