### PR TITLE
DCOS-14728: Move Residency Reducer

### PR DESCRIPTION
**Pull request by Poltergeist**
**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

close DCOS-14728

### CODE REVIEW

**Comment by Poltergeist** [comment]
**mesosphere-ci** run unit tests

**Comment by nLight** [comment]
LGTM! 💯  💖

**Comment by Poltergeist** [comment]
run integration tests

**Comment by Poltergeist** [comment]
run integration tests

**Comment by jfurrow** [comment]
It works!

**Pull request merged**
