### PR TITLE
Enable optional linting arguments

### PR DESCRIPTION
**Pull request by orlandohohmeier**
Adjust the npm lint script to enable optional linting arguments e.g. different file patterns. Using the optional arguments (e.g. `npm run lint -- src/js/stores/**/*.js`) will overwrite the default file patter, thus one you always have to specify the file pattern if you supply agreement.
This adjustments enables us to only lint specific components, or only staged files (`npm run-script lint -- $(git diff --staged --name-only -- '*.js'`).

/cc @MatApple

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @rcorral

**Comment by kennyt** [comment]
conflicts

**Comment by pierlo-upitup** [comment]
LGTM. I'd ask @MatApple who has a tighter grip on the build system to make the final call here.

**Comment by MatApple** [comment]
I like it! Nice @orlandohohmeier!

**Pull request merged**
