### PR TITLE
1.12 Train

### PR DESCRIPTION
**Pull request by GeorgiSTodorov**
This is a 1.12 train containing the following jiras:
https://jira.mesosphere.com/browse/DCOS-46307
https://jira.mesosphere.com/browse/DCOS-46413
https://jira.mesosphere.com/browse/DCOS-21472
https://jira.mesosphere.com/browse/DCOS-50452

Corresponding master PRs (containing testing instructions, screenshots, etc.):
https://github.com/dcos/dcos-ui/pull/3744
https://github.com/dcos/dcos-ui/pull/3733
https://github.com/dcos/dcos-ui/pull/3718
https://github.com/dcos/dcos-ui/pull/3719

### CODE REVIEW

**Comment by pierrebeitz** [comment]
is this up2date?

**Comment by GeorgiSTodorov** [comment]
@pierrebeitz , as far as I know, 1.12 CI is still broken.

**Comment by juliangieseke** [comment]
1.12 CI should be fixed. updated branch, lets see

**Comment by GeorgiSTodorov** [comment]
System tests are failing now, investigating.

**Comment by GeorgiSTodorov** [comment]
Failing test seems unrelated, retriggered.

**Pull request merged**
