### PR TITLE
refactor (universe) Renamed Universe routes and copy to Catalog

### PR DESCRIPTION
**Pull request by rcorral**
refs: DCOS-14793

gif/image

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by jfurrow** [comment]
Also we should make sure the docs team is aware of this change! :)

**Comment by rcorral** [comment]
@jfurrow I'm done with the changes you asked for.

@leemunroe @joel-hamill - I just wanted to run this through you guys for feedback. @joel-hamill I'm hoping you're aware of this change

**Comment by mlunoe** [comment]
It would be nice with a little more informative description, so I don't have to discover that we are removing the installed packages tab here.

**Comment by joel-hamill** [comment]
@rcorral created a JIRA to track fixing doc for 1.10: https://jira.mesosphere.com/browse/DOCS-1864.

**Comment by jfurrow** [comment]
Nice work!

**Comment by rcorral** [comment]
@mlunoe uninstalling non-sdk services isn't a requirement from Product, therefore it's not something we've prioritized for this release.

**Pull request merged**
