### PR TITLE
Allow use of title for schema tabs

### PR DESCRIPTION
**Pull request by kennyt**
So in the `ServiceSchema` if you made the `title` in `General` into `WTF???` it would look like this: 

px

@Poltergeist @aldipower

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @philipnrmn

**Comment by Poltergeist** [comment]
This is super awesome and very helpful thanks for taking the time to implement it! A 💯  👍  for this PR!

**Comment by orlandohohmeier** [comment]
Looks good to me. Feel free to merge this once the test pass.

**Comment by aldipower** [comment]
Nice one!! :)

**Comment by orlandohohmeier** [comment]
retest this please

**Comment by ssk2** [comment]
retest this please

**Comment by ssk2** [comment]
Retest this please!

**Pull request merged**
