### PR TITLE
DCOS-20158: Backport marked fix to 1.8

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
This puts the port introduced in https://github.com/dcos/dcos-ui/pull/2631 to the `1.8` release.

**Checklist**
- [X] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
Alfred test this please :)

**Comment by juliangieseke** [comment]
Alfred test this

**Comment by DanielMSchmidt** [comment]
Alfred test this please :)

**Comment by juliangieseke** [comment]
Something is wrong with Alfred here 🤔

**Comment by DanielMSchmidt** [comment]
Alfred test this please :)

**Comment by DanielMSchmidt** [comment]
@juliangieseke I think your are right 🤔  Reading through [the logs](https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/2171/console) I see that cypress expects a support folder to be there, which we don't seem to have in this version of the code.

It might be that our CI code and this branch are no longer in sync, therefore the test break.
I would like to suggest to keep our alfred configuration, at least the installation part in code, is there any ticket for that?

cc @nLight

**Comment by orlandohohmeier** [comment]
@DanielMSchmidt Yeah, our Jenkins configuration isn't working for this branch as the respective files were never back-ported. We're planning to use Jenkins pipelines to build and release DC/OS UI which would allow us to move the entire configuration into git. For details please see: https://jira.mesosphere.com/browse/DCOS-12802

I'm going to merge this PR despite the cypress test failure due to the points mentioned above.

**Pull request merged**
