### PR TITLE
DCOS-48818: add secret spacing

### PR DESCRIPTION
**Pull request by DanielMSchmidt**

### CODE REVIEW

**Comment by mperrotti** [comment]
@TattdCodeMonkey is making some changes to this to fix alignment. We may be able to close this PR and just take his changes :)

**Comment by brandonc** [comment]
@mperrotti @TattdCodeMonkey I added his suggestion but also found an icon issue. Can you take a look? https://github.com/mesosphere/dcos-ui-plugins-private/pull/986

**Comment by mperrotti** [comment]
@DanielMSchmidt - instead of adding these styles, you can just add the class name `flex-item-grow-1` to that element

**Comment by DanielMSchmidt** [comment]
Worked just fine 👍

**Pull request closed without merging**
