### PR TITLE
Upgrade Marathon to 1.4.0-RC4

### PR DESCRIPTION
**Pull request by orlandohohmeier**
---
~~⚠️  Depends on the fix in https://github.com/dcos/dcos-ui/pull/1687~~ Merged
ℹ️ also fixes: DCOS-13218

---

Upgrade Marathon RAML to 1.4.0-RC4, this version includes some RAML fixes and should improve the form validation.

Closes DCOS-12766

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
**mesosphere-ci** run integration tests 🙈

**Comment by orlandohohmeier** [comment]
run integration tests

**Comment by rcorral** [comment]
@orlandohohmeier I'm getting errors just running my dev server. I'm sure they are related to the errors for the integration tests.

**Comment by wavesoft** [comment]
There is an issue with `raml-validation-loader`, not properly escaping regular expressions. Fixed in #1687

**Comment by mlunoe** [comment]
@wavesoft Could you attend to you #1687 PR?

**Comment by mlunoe** [comment]
Run integration tests

**Comment by mlunoe** [comment]
Ran through it and it fixes the DCOS-12766 issue as well.

**Comment by rcorral** [comment]
Works well :)

**Pull request merged**
