### PR TITLE
Enforce Semicolons

### PR DESCRIPTION
**Pull request by orlandohohmeier**
I'm getting a lots of comments on my PRs, because of missing semicolons. My IDE doesn't automatically adds them, as omitting the semicolons is most of the time absolutely no problem and covered by JavaScripts automatic semicolon insertion feature. But there are certain circumstances where you actually need to add a semicolon, thus I've added a eslint rule to enforce semicolons everywhere. I hope this puts an end to all the needless review cycles and discussions.

/cc @dcos/frontend

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @MatApple

**Comment by rcorral** [comment]
Who would've known that we were missing so many. Thanks!

**Comment by rcorral** [comment]
retest this please

**Comment by aldipower** [comment]
@orlandohohmeier Thank you very much.

**Pull request merged**
