### PR TITLE
[Backport:1.11] DCOS-21122: fix(ServiceForm): fixes focus/change/blur behaviour

### PR DESCRIPTION
**Pull request by juliangieseke**
---

ℹ️ Backport of: #2761  

---

This ~commit~ PR changes the onChange handler of the ServiceForm so that
it no longer implicitly sets state.editingFieldPath, instead a new
internal function `handleFormFocus` is introduced.

Closes DCOS-21122

### CODE REVIEW

**Comment by juliangieseke** [comment]
run integration tests

**Comment by Poltergeist** [comment]
run integration tests

**Comment by Poltergeist** [comment]
run integration tests

**Comment by juliangieseke** [comment]
We have to reopen this PR because Alfred is toast again 😠 
=> #2772

**Pull request closed without merging**
