### PR TITLE
Add resource table to node detail page

### PR DESCRIPTION
**Pull request by philipnrmn**
This PR adds the resource table to the nodes detail page.

screen shot 2017-02-09 at 3 21 57 pm

### CODE REVIEW

**Comment by philipnrmn** [comment]
run unit tests

**Comment by nLight** [comment]
⚔️  flicts!

**Comment by philipnrmn** [comment]
:hammer:

**Comment by wavesoft** [comment]
Shall we expand this in the same way @jfurrow has done in his PRs like #1904 ?

**Comment by philipnrmn** [comment]
Can do! What's the intention of this? Just more expressive?

**Comment by philipnrmn** [comment]
Hmm, I'm actually not sure that it's any better, unless we want to deprecate the HashMapDisplay entirely?

**Comment by jfurrow** [comment]
@philipnrmn My take on it is that `HashMapDisplay` should be used when we don't know exactly what keys might exist in an object, but we want to display whatever the API gives us. When we do know what keys we want to display (e.g. the resources in the second `HashMapDisplay` instance you added in this PR), then we should use the `ConfigurationMap` components.

I don't feel super strongly about this and don't want it to hold up this PR, so I'm happy to add my label!

**Comment by MatApple** [comment]
@philipnrmn I do agree with @jfurrow here - would you have time to update? If not, @jfurrow - how would you feel about making the change?

**Comment by jfurrow** [comment]
@MatApple @philipnrmn I'm on it!

**Comment by jfurrow** [comment]
@MatApple @philipnrmn Done!

**Comment by nLight** [comment]
run unit tests

**Pull request merged**
