### PR TITLE
Add missing instructions for DC/OS Vagrant setup

### PR DESCRIPTION
**Pull request by pierlo-upitup**
Add the proxy_buffering nginx directive to ~~increase~~ decrease assets loading time and add explicit instructions to get started on the Vagrant DC/OS setup.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @philipnrmn

**Comment by pierlo-upitup** [comment]
Actually I wonder if these values shouldn't be part of the `Config.js` file by default as the Vagrant setup seems to be the recommended setup anyway.

**Comment by pierlo-upitup** [comment]
cc @rcorral

**Comment by aldipower** [comment]
LGTM

**Comment by rcorral** [comment]
They are useful at times, IMO.

**Pull request merged**
