### PR TITLE
chore(package): update webpack-dev-server

### PR DESCRIPTION
**Pull request by juliangieseke**
## Testing

check that `npm start` is still working with and without plugins 👍

### CODE REVIEW

**Comment by nLight** [comment]
why?

**Comment by juliangieseke** [comment]
the page might be only visible for admins 🤔 replaced the link with description

**Comment by mperrotti** [comment]
@juliangieseke - what do you mean when you say "with and without plugins"?

**Comment by GeorgiSTodorov** [comment]
@mperrotti , I think with and without the private plugins repository.

**Pull request merged**
