### PR TITLE
[spike] DCOS-46215: Error requesting UI Configuration message email is shown as {0}

### PR DESCRIPTION
**Pull request by GeorgiSTodorov**
Change the error message function in order to show the email.

Closes https://jira.mesosphere.com/browse/DCOS-46215

## Testing
1. In `proxy.dev.js` use an outdated cluster url and run `npm start`.
2. Verify that the email is shown on the error page

## Trade-offs
The message appears in English, even when the language is changed to Chinese, I am not sure why.

## Dependencies
https://github.com/mesosphere/dcos-ui-plugins-private/pull/926

### Before
screenshot from 2018-12-13 13-28-19

### After
screenshot from 2019-02-01 16-48-26

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
I am not sure what broke with the previous PR, this one should work.

**Comment by GeorgiSTodorov** [comment]
Rebased.

**Comment by pierrebeitz** [comment]
What happened to https://github.com/dcos/dcos-ui/pull/3575? It says "The functionality is broken".

I actually like that one better, as the translators would be able to freely move the email-link inside of the translated stuff.

This is no blocking concern though. I just want us to be able to properly work with lingui and not around it.

**Comment by GeorgiSTodorov** [comment]
@pierrebeitz , the old PR wasn't working as expected, maybe something broke while rebasing. After that, I couldn't get it working with the email inside the `<Trans>`.

**Comment by pierrebeitz** [comment]
i re-implemented the solution of #3575 and it seems to work for me. it keeps the link  as a lingui-indexed-tag.

as this is not important for that very issue, feel free to delete my commit at will.

**Comment by nLight** [comment]
@GeorgiSTodorov mergable?

**Comment by GeorgiSTodorov** [comment]
@nLight , it should be as long as we merge the other PR too.

**Pull request merged**
