### PR TITLE
Prevent caret--undefined className

### PR DESCRIPTION
**Pull request by jfurrow**

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @daiyiwhale

**Comment by ssk2** [comment]
@mesosphere-ci: retest this please

**Comment by ssk2** [comment]
@jfurrow please confirm this is expected to fail...

**Comment by jfurrow** [comment]
@ssk2 Yikes, that was a legit failure. Thanks, it's fixed now.

**Pull request merged**
