### PR TITLE
[spike] DCOS-15019: Poor default for container Image

### PR DESCRIPTION
**Pull request by GeorgiSTodorov**
Make the default container for Single Container services to be UCR
for better user experience.

Closes https://jira.mesosphere.com/browse/DCOS-15019

## Testing
1. Go to Services tab
2. Create a new Single Container service
3. In the Service tab, click "More Settings"
4. Verify that "Universal Container Runtime (UCR)" is selected as Container Runtime

## Trade-offs
If I understand this correctly, "Container Image" is not used for UCR, so disabling it when UCR is active is worth considering. Also hiding it in the Configuration tab if the service uses UCR Container.

## Dependencies
None.

### Before
peek 2019-01-04 21-26

### After
peek 2019-01-04 16-34

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
Great 👍 Just wanted to make sure we are clear on this 😇 Thank you for asking beforehand 🙇

**Comment by AmrAbdelrazik** [comment]
@DanielMSchmidt  and @GeorgiSTodorov  let's do it.

**Comment by AmrAbdelrazik** [comment]
@GeorgiSTodorov I would appreciate if I can be notified when this merges to DC/OS master please

**Comment by GeorgiSTodorov** [comment]
I think the failing tests are flaky.

**Comment by GeorgiSTodorov** [comment]
Tests failing locally, will fix.

**Comment by GeorgiSTodorov** [comment]
Tests should be fixed now, @DanielMSchmidt , @natmegs , please re-review.

**Pull request merged**
