### PR TITLE
[backport 1.11] fix(UniversePackage): fallback to type: "object" for config

### PR DESCRIPTION
**Pull request by ahoskins**
backport of #2719 

**Checklist**
- [ ] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
Alfred test this please :)

**Comment by Fabs** [comment]
I had the Alfred errors of this PR in another place. Will retest Alfred.

**Comment by Fabs** [comment]
Alfred test this please

**Comment by DanielMSchmidt** [comment]
Alfred test this please :)

**Comment by DanielMSchmidt** [comment]
Alfred test this please :)

**Comment by juliangieseke** [comment]
run integration tests

**Comment by ahoskins** [comment]
alfred test this please

**Comment by ahoskins** [comment]
run integration tests

**Pull request merged**
