### PR TITLE
DCOS-43324: fix Cosmos icons

### PR DESCRIPTION
**Pull request by nLight**
The PR drops parsing of cosmos URL as that can break URL on some clusters.

## Testing

1. add `--https` to npm start like so `"start": "NODE_ENV=development webpack-dev-server --https --config ./webpack/webpack.dev.js --hot --progress --colors --content-base ./build --host 0.0.0.0 --port $npm_package_config_port",`
2. Launch any catalog service with an icon
3. Verify that icon is visible

## Trade-offs

Dev mode without `https` won't show icons
We can' switch to https on dev just now as webpack crashes on the catalog page

### CODE REVIEW

**Comment by natmegs** [comment]
I'm seeing all placeholder purple icons in the catalog and then webpack crashes... am I missing something? Changed npm start as indicated

**Comment by nLight** [comment]
@natmegs please launch something from the catalog before testing Services page. As I mentioned in the PR Catalog page crashes webpack :(

**Comment by GeorgiSTodorov** [comment]
Are we adding this to master?

**Comment by GeorgiSTodorov** [comment]
@nLight Okay, I thought we forgot because I still have buggy icons for services when running it locally.

**Comment by nLight** [comment]
@GeorgiSTodorov please refer to the trade-offs section. icons will be always broken locally unless running webpack with `--https` key which we can't do as it is crashes on the Catalog page

**Comment by GeorgiSTodorov** [comment]
@nLight Okay, thank you.

**Pull request merged**
