### PR TITLE
DCOS-18784: pod instance

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
**Checklist**
- [X] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by weblancaster** [comment]
Hey @DanielMSchmidt whenever you create a new PR it's a good practice for us to give it good description, how to test and whenever possible a screenshot or gif.

e.g https://github.com/dcos/dcos-ui/pull/2585

**Comment by DanielMSchmidt** [comment]
Alfred test this please :)

**Comment by DanielMSchmidt** [comment]
Alfred test this please :)

**Comment by DanielMSchmidt** [comment]
Run integration tests

**Comment by orlandohohmeier** [comment]
@DanielMSchmidt please open a PR to back-port the fix to DC/OS UI 1.10

**Comment by DanielMSchmidt** [comment]
Will do 👍

**Pull request merged**
