### PR TITLE
DCOS-12608: Collapsing repeating errors in ActionsModal

### PR DESCRIPTION
**Pull request by wavesoft**
This PR enables collapsing of repeating errors in the ActionsModal

image

Related plugins-private PR: https://github.com/mesosphere/dcos-ui-plugins-private/pull/543

### CODE REVIEW

**Comment by nLight** [comment]
Do we want to show what exactly failed to be added? There could be a situation when you select all, click add and one half is added successfully and the other half hasn't been and we say just 10x Is already part of the Group, without providing any info.

**Comment by wavesoft** [comment]
Unfortunately marathon does not respond with more details about the error:
```
{
    "title": "Bad Request",
    "description": "User is already part of group",
    "code": "ERR_USER_ALREADY_IN_GROUP"
}
```

If we have the XHR object along with the error (when Matt's PRs gets merged), we could extract the request URL and from there the token. But currently it's not very easy 😑

**Comment by nLight** [comment]
I get both :(

feb-10-2017 15-33-53

**Comment by wavesoft** [comment]
@nLight , you also need the mesosphere/dcos-ui-plugins-private#543

**Comment by nLight** [comment]
LGTM! 💯  💖

**Comment by jfurrow** [comment]
Nice work!

**Pull request merged**
