### PR TITLE
WIP: chore(reactjs-components): beta24

### PR DESCRIPTION
**Pull request by nLight**
This PR bumps reactjs-components version so as react and react-addons-css-transition-group

### CODE REVIEW

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
Alfred would you please retest this?

**Comment by orlandohohmeier** [comment]
Alfred could you please retest this PR?

**Comment by orlandohohmeier** [comment]
@nLight I'm not sure why the test is failing... I ran the tests locally and everything looked good. Please Investigate and feel free to merge if the test is unrelated to you changes.

**Comment by nLight** [comment]
@orlandohohmeier So I messed up `reactjs-components`, removing too much 😅  
I'm creating a fix

**Comment by nLight** [comment]
retest this please

**Comment by nLight** [comment]
retest this please

**Comment by nLight** [comment]
One can't just use pre-release version of components 😩

**Pull request closed without merging**
