### PR TITLE
[Spike] Refactor ServicesPage: update with es6 class

### PR DESCRIPTION
**Pull request by natmegs**
Move ServicesPage from createReactClass to es6 class.

## Testing

Go to services page, tab around and make sure nothing breaks.

## Trade-offs

I 90% converted this to TS but got hung up on the mixin types 😞 

## Dependencies

N/A

### CODE REVIEW

**Comment by nLight** [comment]
> I 90% converted this to TS but got hung up on the mixin types 😞

Can't we ignore/`any` those missing types? I feel like otherwise it's to heavy to do in one take

**Comment by nLight** [comment]
@pierrebeitz to rescue? 🙏

**Comment by pierrebeitz** [comment]
PR is already on the radar as i think TS's static properties will also make this PR easier to review.

**Comment by pierrebeitz** [comment]
@natmegs 	added a commit that addresses what i think might have been the problem.

as always feel free to use, alter or throw away my commits.

**Comment by natmegs** [comment]
Hey @pierrebeitz thanks for the help! I had actually tried something super similar, but the problem that I see is that the typing of the mixin as returning `any` makes it so that we are not getting the benefit of types at all inside of the component (it doesn't know what types the props or state should be. For ex if you take out the state initializer it should yell at you but it doesn't). Maybe this is ok for a first pass though?

**Comment by pierrebeitz** [comment]
to properly infer all that information we'd have to make up for our magic mixins - i.e. the `TabsMixin` with dynamically generated `render${currentTab}TabView`-functions. i'm not sure whether it is possible to create sound and complete typings for that mixin-mechanism.

i strongly believe that the codebase would benefit from removing the mixins (e.g. by making everything they do explicit) and thus think there's not much value in trying to come up with those really complex types.

**Pull request merged**
