### PR TITLE
Fixed Deploy New Service Text

### PR DESCRIPTION
**Pull request by jmanalus**
Text original said “Deploy new Service” and I’ve updated it to say “Deploy New Service”

https://mesosphere.atlassian.net/browse/DCOS-8700

Original: https://cl.ly/2i0Y1c3Q432N
Updated: https://cl.ly/08223o3S3Y2O

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @daiyiwhale

**Comment by jfurrow** [comment]
@jmanalus Did you test this in Safari?

**Comment by jmanalus** [comment]
@jfurrow - si https://cl.ly/1K0L1x1y171Y

**Comment by kennyt** [comment]
@jfurrow i honestly can't tell if that's a joke or not

**Comment by jfurrow** [comment]
@jmanalus @kennyt It was supposed to be a joke...

**Comment by leemunroe** [comment]
Trolls

**Pull request merged**
