### PR TITLE
refactor(sidebar): es6 class & remove mixin

### PR DESCRIPTION
**Pull request by nLight**
I wanted to do it within the next sprint, but my #2907 pushed me to do the refactoring searching a solution to a problem I stumbled onto.
 
I dug into the DC/OS UI history and discovered that the internal storage not being used since 3 years. We set the state but never read it.

Closes DCOS-22293

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by nLight** [comment]
@DanielMSchmidt turned out I've forgotten to bind few things... Did you know you can fold/unfold the Sidebar by pressing <kbd>[</kbd>

**Comment by DanielMSchmidt** [comment]
No I didn't, nice to know 👍

**Comment by DanielMSchmidt** [comment]
I could not fold/unfold the sidebar by pressing `[`, not `cmd+[`, neither on master, nor here. Might be because I have a german keyboard

**Comment by nLight** [comment]
@DanielMSchmidt where, on German keyboard, this key is located?

**Comment by DanielMSchmidt** [comment]
its the combination of alt + 5

**Comment by nLight** [comment]
No, it wouldn't work :trollface:

**Comment by DanielMSchmidt** [comment]
Can't review this then 😞

**Pull request merged**
