### PR TITLE
DCOS-40644: wrap text for constraint field tooltip

### PR DESCRIPTION
**Pull request by tnguyen0**
## Testing

* Test on Open Cluster
* Go on Catalog Page and click on Cassandra
* Click Review and Run
* Click Nodes Tab and scroll down to Placement Constraints

### Before
screen shot 2018-09-07 at 4 29 29 pm

### After
screen shot 2018-09-07 at 4 30 03 pm

### CODE REVIEW

**Comment by nLight** [comment]
@GeorgiSTodorov screenshots are wrong. This PR is about Placement constraints section in the Service Form, not the Catalog Form
screenshot 2018-09-10 at 12 49 36

**Comment by nLight** [comment]
Funny how it jumps when you shrink the window :D it resets to the proper place though, not blocking

**Comment by GeorgiSTodorov** [comment]
@nLight how to open the service form?

**Comment by nLight** [comment]
That's the regular form. Services -> launch either a Pod or a Single container app

**Comment by GeorgiSTodorov** [comment]
That's what I thought, but it still doesn't work for me.

screenshot from 2018-09-10 14-01-58

**Comment by nLight** [comment]
Do we have another one for Pods? 😅

**Pull request merged**
