### PR TITLE
DCOS-20976: fix(CliInstall): renames terminal to command prompt

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Test this by opening the install cli modal and switching to windows

**Checklist**
- [X] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
@juliangieseke @Fabs @nLight I just rebased 👍

**Comment by DanielMSchmidt** [comment]
Run system tests :)

**Comment by DanielMSchmidt** [comment]
Run system tests :)

**Comment by DanielMSchmidt** [comment]
Run integration tests :)

**Comment by DanielMSchmidt** [comment]
Alfred test this please :)

**Comment by DanielMSchmidt** [comment]
Alfred test this please :)

**Comment by DanielMSchmidt** [comment]
run system tests

**Comment by DanielMSchmidt** [comment]
run integration tests

**Comment by ahoskins** [comment]
run integration tests

**Pull request merged**
