### PR TITLE
DCOS-8420 & DCOS-8446: Capitalise ‘Service’

### PR DESCRIPTION
**Pull request by daiyiwhale**
Capitalises 'Service' in deployment tab `location` column and also services tab search filter.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @pierlo-upitup

**Comment by mlunoe** [comment]
Retest this please

**Comment by mlunoe** [comment]
Feel free to merge once tests pass ⛵

**Comment by pierlo-upitup** [comment]
retest this please

**Pull request merged**
