### PR TITLE
DCOS-14854: Remove edit link on service config page

### PR DESCRIPTION
**Pull request by mlunoe**
PR #1957 wrongly added onEditClick to this view. This PR reverts that effort and adds a test to guard against it

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [x] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by mlunoe** [comment]
Once this PR merges we need to point a PR with the change to 1.8.

**Comment by mlunoe** [comment]
Run integration tests

**Comment by mlunoe** [comment]
Run integration tests

**Comment by mlunoe** [comment]
Run integration tests

**Comment by orlandohohmeier** [comment]
@mlunoe please open a PR to back-port the fix to DC/OS UI 1.9

**Comment by wavesoft** [comment]
Looks good to me 👍  ✨

**Comment by mlunoe** [comment]
Will do as soon as this merges, hence the label

**Comment by weblancaster** [comment]
Looks good.

**Pull request merged**
