### PR TITLE
DCOS-19400: Refactor - local volumes

### PR DESCRIPTION
**Pull request by Poltergeist**
This PR is the first of a series of refactoring efforts.

This PR mostly just changes localVolumes logic to Volumes and removes the localVolumes header

### CODE REVIEW

**Comment by weblancaster** [comment]
alfred test this please

**Comment by ahoskins** [comment]
Alfred test this please

**Comment by Poltergeist** [comment]
To @weblancaster comment: 
This localVolumes ist what marathon gives us, which is right. So we should not change this I guess.

**Comment by Poltergeist** [comment]
alfred, retest this please

**Pull request merged**
