### PR TITLE
Fix task finished text color

### PR DESCRIPTION
**Pull request by jfurrow**
Verified with @cleverroffey, this is the intended text color.

Before:

After:

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @daiyiwhale

**Comment by kennyt** [comment]
should we also remove the class application to JSX?

**Comment by jfurrow** [comment]
The class is applied generically (`task-status-${taskStatus}`) so I don't think it's worth removing only for this status.

**Comment by daiyiwhale** [comment]
nice :D

**Pull request merged**
