### PR TITLE
[Nodes Page] Purify unit health component

### PR DESCRIPTION
**Pull request by philipnrmn**
_Successor to #1121_

This is part of the wider nodes modularity/refactoring story.

This component is used by two routes:
- `components/:unitID/nodes/:unitNodeID/`
- `nodes/:nodeID/health/:unitNodeID/:unitID`

It is current nested in /system.

I'd especially welcome suggestions on improving the directory structure and the naming pattern.

### CODE REVIEW

**Comment by MatApple** [comment]
We need to update the shrinkwrap :)

**Comment by MatApple** [comment]
LGTM! Nice 👍 . I'd merge if tests were passing

**Comment by MatApple** [comment]
Going to fix up these lint errors as part of the rebase and then we can merge.

**Comment by philipnrmn** [comment]
Cool, thanks. There are a whole bunch of test failures but they're all present on the feature branch too so I think this is safe to merge.

**Pull request closed without merging**
