### PR TITLE
Fix spelling of 'Ephemeral'

### PR DESCRIPTION
**Pull request by philipnrmn**
screen shot 2016-12-21 at 11 37 17 am

For your convenience, here's the [wiktionary page on ephemeral](https://en.wiktionary.org/wiki/ephemeral).

### CODE REVIEW

**Comment by mlunoe** [comment]
run integration tests

**Comment by mlunoe** [comment]
Feel free to ⛵️ once tests pass

**Comment by philipnrmn** [comment]
run integration tests 🗡

**Comment by rcorral** [comment]
merging as the same failing integration tests are failing on all PRs. We're looking into this right now.

**Pull request merged**
