### PR TITLE
eslint jsx max len rule

### PR DESCRIPTION
**Pull request by mlunoe**
---
~~:warning: Dependent on this PR: https://github.com/dcos/dcos-ui/pull/1865~~ Merged!

---

This PR introduces the `jsx-max-len` eslint rule.

Diff for review can be found here: https://github.com/dcos/dcos-ui/compare/mlunoe/feature/update-eslint-3.14.1...mlunoe/feature/eslint-jsx-max-len-rule?expand=1

### CODE REVIEW

**Comment by mlunoe** [comment]
Retest this please

**Comment by mlunoe** [comment]
Run unit tests

**Comment by jfurrow** [comment]
Glad to see a hard rule for this! :ship: (after conflict is addressed)

**Comment by mlunoe** [comment]
Yay! :)
Rebased!

**Comment by mlunoe** [comment]
Run unit tests

**Comment by nLight** [comment]
Like how it adds consistency

**Pull request merged**
