### PR TITLE
DCOS-42348: Show error page when the log file won't load

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
## Testing

Look at a task and go to Log. Now open the network tab and search for "files/read". Block that URL. Reload. See an error message instead of infinite loading.

## Trade-offs

- Decided to use the very same error page for both errors as the origin of this issue is unclear in both occasions.
- Decided to directly show the error, might lead to blinking if it's first not there and then there, but this is really an upstream bug (if it even exists) and I am willing to do this tradeoff

## Dependencies

None

## Screenshots

Not so interesting here 🤷‍♂️

### CODE REVIEW

**Comment by nLight** [comment]
That `release/1.11-` got you in trouble man :D

**Comment by GeorgiSTodorov** [comment]
screenshot from 2018-09-25 13-35-24
This is the message that I got, is it correct?

**Comment by nLight** [comment]
As it goes for 1.11 I think that was our default message

**Comment by nLight** [comment]
Sorry, hit `Close and comment` 😅

**Pull request merged**
