### PR TITLE
DCOS_OSS-2017 - fixes the description of the IS operator

### PR DESCRIPTION
**Pull request by Fabs**
The current description for the IS operator is a copy and paste from the CLUSTER one. Because of that, based on [Marathon Documentation](https://github.com/mesosphere/marathon/blob/master/docs/docs/constraints.md) we are providing an adequate description.

image

### CODE REVIEW

**Comment by Fabs** [comment]
Hey, @leemunroe could you check the description of this one please :-). The link in the documentation mentioned above did not have a concise description, so I came up with something based on the other descriptions in the same dropdown.

**Comment by leemunroe** [comment]
Nice one @Fabs. I believe @sascala was working on content for this with Lily so I'll let her give thumbs up for this one.

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
system-tests test this

**Comment by ahoskins** [comment]
Nice, thanks for picking this up @Fabs

**Comment by Fabs** [comment]
@leemunroe. I think there is a second measure which is to get the best content for those options, I created DCOS-20155 and gave it to @orlandohohmeier so we can plan it accordingly. 

IMHO this PR solves a wrong content problem and if my proposed text is correct I believe we should merge it, and deal with the precise content later.

By the way, I am working on why the test is failing.

My pleasure @ahoskins

**Comment by Fabs** [comment]
Alfred test this bitte

**Comment by DanielMSchmidt** [comment]
Alfred test this please 😏

**Comment by Fabs** [comment]
Alfred test this　ください

**Comment by Fabs** [comment]
Alfred test this please

**Comment by juliangieseke** [comment]
The related test was green 🤛
Alfred please test this

**Comment by juliangieseke** [comment]
Alfred test this

**Comment by Fabs** [comment]
Alfred test this

**Comment by Fabs** [comment]
Alfred test this

**Comment by Fabs** [comment]
Alfred test this

**Pull request merged**
