### PR TITLE
DCOS-13349: Let the form grow freely

### PR DESCRIPTION
**Pull request by nLight**
Before:
screen shot 2017-01-26 at 16 51 06

After:
screen shot 2017-01-26 at 16 50 33

Me:
b7e

### CODE REVIEW

**Comment by nLight** [comment]
run unit tests

**Comment by nLight** [comment]
run unit tests

**Comment by jfurrow** [comment]
LOL @ image!

This is perfect! This element is a child of a `display: flex` parent, so we need it to grow and shrink in accordance with its siblings (the first and second values of the `flex` shorthand property, respectively). The third value is the `flex-basis` property, and `auto` is exactly what we want because we don't want to make any assumptions about the content width.

**Comment by nLight** [comment]
run unit tests

**Comment by orlandohohmeier** [comment]
✨ Awesome

**Pull request merged**
