### PR TITLE
feat(locale): Adds initial chinese catalog

### PR DESCRIPTION
**Pull request by brandonc**
## Testing

- Before starting, run `npx lingui compile`
- Switch to chinese locale in profile menu or UI settings

## Trade-offs

Including in the webpack build is probably not a good idea because each catalog is quite large (100 KB minified). Asynchronous loading can be added separately.

## Screenshots

screen shot 2018-11-14 at 8 04 10 pm
screen shot 2018-11-14 at 8 04 31 pm

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
Not sure what the scope here is (therefore not setting request changes), but I found a lot of places where our translation was incomplete. Sorry for the long post.
1
screenshot from 2018-11-15 12-12-36
2
screenshot from 2018-11-15 11-52-52
3
screenshot from 2018-11-15 11-53-19
4
screenshot from 2018-11-15 11-53-45
5
screenshot from 2018-11-15 11-55-42
6
screenshot from 2018-11-15 11-55-57
7 (the entire jobs modal)
screenshot from 2018-11-15 11-56-17
8
screenshot from 2018-11-15 11-52-09
9
screenshot from 2018-11-15 11-57-03
10
screenshot from 2018-11-15 11-57-51
11
screenshot from 2018-11-15 11-58-02
12
screenshot from 2018-11-15 11-58-13
13
screenshot from 2018-11-15 11-58-24
14
screenshot from 2018-11-15 11-59-05
15
screenshot from 2018-11-15 11-59-45
16
screenshot from 2018-11-15 11-59-55
17
screenshot from 2018-11-15 12-00-31
18
screenshot from 2018-11-15 12-00-44
19
screenshot from 2018-11-15 12-01-01
20
screenshot from 2018-11-15 12-01-12

**Comment by nLight** [comment]
@GeorgiSTodorov thanks for the comprehensive review here! Would you please capture that in a ticket? I believe there are a lot pluralization related misses and other part is the server response like on [15].

@brandonc shall we create a Jira, point it and pull into the sprint implementing Dynamic Import? We still have one week for that.

**Comment by GeorgiSTodorov** [comment]
@nLight : https://jira.mesosphere.com/browse/DCOS-45175 .

**Comment by jaxesn** [comment]
Probably still worth merging this since its at least the first pass and then in another we can go thru and try to extract some of the strings we missed?

**Comment by brandonc** [comment]
@GeorgiSTodorov Appreciate the detailed look at missing translations! Hopefully this squares with my expectations

@nLight I am surprised by the idea to pull this work or dynamic import into the sprint when it feels overcommitted already. I think we should add to the top of the backlog. I'm feeling pretty booked

**Comment by nLight** [comment]
Fair enough, let's get this in and plan refactoring then

**Pull request merged**
