### PR TITLE
Feature - Service versions rollback buttons

### PR DESCRIPTION
**Pull request by aldipower**
* [x] Implements functionality (Edit and direct Apply) for rollback a service by a given version
* [x] Integration tests
* [x] Styling completed

nogap

@ashenden Is there an straight-forward way of putting a gap between the dropdown and the edit button?
I've already invested some time to solve this actually easy problem, but gave up to proceeded with the implementation of functionality.
I don't want to add a specific class only for that.
Maybe you have a hint?

current-structure

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @philipnrmn

**Comment by aldipower** [comment]
There is now a gap between the dropdown and the edit! :)

edit-apply

**Comment by aldipower** [comment]
Tests passing locally. Really.

**Comment by Poltergeist** [comment]
works / tests pass local. LGTM lets :shipit: 🎆

**Pull request merged**
