### PR TITLE
Use break-word classname for DescriptionList key

### PR DESCRIPTION
**Pull request by jfurrow**
px

Integration tests passing on a frankie branch, which includes this:

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @philipnrmn

**Comment by rcorral** [comment]
retest this please

**Comment by rcorral** [comment]
retest this please

**Comment by mlunoe** [comment]
Feel free to merge once tests pass ⛵-y McBoatFace

**Comment by rcorral** [comment]
retest this please

**Pull request merged**
