### PR TITLE
feat(loginmodal): update styles for privacy policy (master)

### PR DESCRIPTION
**Pull request by bstavroulakis**
Update styles for privacy policy.

Closes DCOS-22402

**Checklist**
- [X] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by bstavroulakis** [comment]
Depends on:
https://github.com/mesosphere/dcos-ui-plugins-private/pull/787
https://github.com/mesosphere/auth0-ui/pull/22

**Comment by juliangieseke** [comment]
@bstavroulakis you're stating that all PRs are dependend on each other, if thats true we have a deadlock :( can you please clarify which PRs actually depend on what so that we can merge them? I guess this one isnt really depending on anything else, but the others depend on the dcos-ui ones.

**Comment by bstavroulakis** [comment]
Please don't review as discussions are made.

**Comment by bstavroulakis** [comment]
We clarified when do we want to show the privacy policy.

The 2 cases are:

When the user has enabled tracking.
Or when the user has enabled OAuth.

**Pull request merged**
