### PR TITLE
DCOS-45803: backport: support scheduling in Pods

### PR DESCRIPTION
**Pull request by nLight**
backport #3425

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
Not sure what this means:
```
==> Running Tests for ./tests/pages/catalog/packages/package/PackageTab-cy.js

===> Executing Cypress (1/3)

Sending interrupt signal to process

sh: line 1:  3109 Terminated              JENKINS_SERVER_COOKIE=$jsc '/jenkins/workspace/cos-ui-oss-pipeline_PR-3427-YFEDUTN6VGZUK5HEE25W3BG6Y2XZL76YV45UOSMV7CR24ZJJAOYA@tmp/durable-74ce7326/script.sh' > '/jenkins/workspace/cos-ui-oss-pipeline_PR-3427-YFEDUTN6VGZUK5HEE25W3BG6Y2XZL76YV45UOSMV7CR24ZJJAOYA@tmp/durable-74ce7326/jenkins-log.txt' 2>&1
```
, retriggered tests.

**Comment by GeorgiSTodorov** [comment]
Re-running tests again.

**Comment by GeorgiSTodorov** [comment]
And again. A failing test is known to be flaky - https://jira.mesosphere.com/browse/DCOS-20273 .

**Comment by nLight** [comment]
@GeorgiSTodorov @DanielMSchmidt and I planning CI unflake effort for the next RI as _the_ focus for foundation. Thanks for raising awareness and checking failing tests against the flake list

**Comment by nLight** [comment]
@TattdCodeMonkey @GeorgiSTodorov snuk in some latest ci improvements. Thanks for understanding

**Pull request closed without merging**
