### PR TITLE
Fix Ace editor tooltip positioning

### PR DESCRIPTION
**Pull request by orlandohohmeier**
Change the fullscreen modal side panel positioning to use position `right` instead of transform `translateX` as `transform` creates a new stacking context and the containing block is changing the context which results in "wrong" positions.

For more details please see:
https://drafts.csswg.org/css-transforms-1/#transform-rendering

With this change in place we no longer need the hacks to correct the Ace editor tooltip position, as position fixed (used to position the tooltip) is working as expected.

### CODE REVIEW

**Comment by wavesoft** [comment]
Take that hack out!! 💯  ✨  

Cleanup

**Comment by jfurrow** [comment]
+1000 thanks for doing this!

**Comment by orlandohohmeier** [comment]
@jfurrow why do you want to use pixel values instead of percent?

**Comment by jfurrow** [comment]
@orlandohohmeier I pushed a commit, hope you don't mind. The `right: -100%` value for the side panel needs to change at each breakpoint, because the `100%` refers to the whole width of the modal, rather than the width of the side panel itself.

**Comment by jfurrow** [comment]
I'll let someone else merge since I had a hand in this as well :)

**Comment by wavesoft** [comment]
Looks good 👍

**Pull request merged**
