### PR TITLE
docs(testing): fix image paths

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Hi there,

I just noticed that the docs had broken images, possibly through the renaming in the organisation.
I hope I followed the contributing guidelines correctly, if not please let me know 👍 

Happy Holidays ❄️

### CODE REVIEW

**Comment by nLight** [comment]
Hey, @DanielMSchmidt! Thanks for the PR, very good catch! The URLs target a private repo, so everyone of us is able to see the images 😅

**Comment by nLight** [comment]
@mesosphere-ci ok to test

**Comment by nLight** [comment]
Alfred retest this please

**Comment by nLight** [comment]
skip ci

**Comment by MatApple** [comment]
Hey @DanielMSchmidt  - thanks for the PR!! 💯

**Comment by DanielMSchmidt** [comment]
No worries, just noticed while scrolling through the docs 👍

**Comment by orlandohohmeier** [comment]
**mesosphere-ci** ✅  ok to test

**Comment by Poltergeist** [comment]
Alfred please retest this

**Comment by orlandohohmeier** [comment]
Thanks a lot for fixing these paths! 💜

**Pull request merged**
