### PR TITLE
Bump @dcos/mesos-client 0.1.8

### PR DESCRIPTION
**Pull request by nLight**
To remove the 30 seconds timeout so the browser will control timeouts. 

The rxjs timeout has a flaw that it doesn't take into account slow connections and would just close the connection

### CODE REVIEW

**Comment by nLight** [comment]
Alfred test this please

**Comment by bstavroulakis** [comment]
I merged the reactjs-components bump with master and this has to get rebased. Probably have to run shrinkwrap again 😬 .

**Comment by nLight** [comment]
Rebased, please ✅

**Comment by juliangieseke** [comment]
Alfred test this please

**Pull request merged**
