### PR TITLE
    DCOS-40779: [Firefox] Form control icons overflow issue (for other components) backport 1.11

### PR DESCRIPTION
**Pull request by GeorgiSTodorov**
In 1.11 add min-width to the input to fix overflowing icons in Firefox.

Closes https://jira.mesosphere.com/browse/DCOS-40779

## Testing
1. Set up node to use version 4.4.7 and npm to use version 3.9.6
I recommend using a new copy of the dcos-ui repository.
Setting up node is easy: just use a node version manager (I used https://github.com/creationix/nvm) and run (if you are using nvm) `nvm install 4.4.7` in the directory. Setting up npm is a bit trickier - navigate to the nvm directory, for example `cd ~/.nvm/versions/node/v4.4.7/lib` and run `npm install npm@3.9.6`. Then run `npm install`.

https://stackoverflow.com/a/33575448

2. Verify that the icons are fixed for all input bars (see screenshots). If possible, verify that the icons look good in other browsers.

## Trade-offs
I added `{display: block}}` to the icons like Mike suggested.

## Dependencies
None

## Screenshots
These are all the places that I found:

### Jobs > (Create a job if needed)
screenshot from 2018-08-24 13-44-07

### Nodes > Node > Health
screenshot from 2018-08-24 13-47-17

### Services > Service > Logs
screenshot from 2018-08-24 13-48-23

### Catalog
screenshot from 2018-08-24 13-48-37

### Networking > Networks
screenshot from 2018-08-24 13-48-54

### Components
screenshot from 2018-08-24 13-49-48

### Settings > Package Repositories
screenshot from 2018-08-24 13-50-02

### Organization > Users
screenshot from 2018-08-24 13-50-21

### CODE REVIEW

**Comment by natmegs** [comment]
Is this DCOS-40893 and DCOS-40779 in one?

**Comment by nLight** [comment]
@GeorgiSTodorov would you mind rebasing and dropping that commit instead of reverting it?

**Comment by GeorgiSTodorov** [comment]
@nLight Okay, I will.

**Comment by DanielMSchmidt** [comment]
bildschirmfoto 2018-08-27 um 12 37 05
The logs view looks pretty broken, but this is a separate bug I guess. Could you create a new bug ticket for this? Or am I the only one perceiving it as broken?

**Comment by GeorgiSTodorov** [comment]
@DanielMSchmidt You are right, it's broken, I will create a bug ticket. It looks like it's broken here in 1.11 and in 1.10 as well, but it's fine in 1.12 (see screenshots for https://github.com/dcos/dcos-ui/pull/3204)

**Pull request merged**
