### PR TITLE
DCOS_OSS-4582: [1.11]  accept floating points in FrameworkConfigurationForm

### PR DESCRIPTION
**Pull request by mperrotti**
## Testing
Use a browser other than Chrome.. With your browser and OS in locale that uses "," as a decimal separator  (de-DE, ru, fr-FR, etc...).
1. Go to Catalog and add a new service
2. Go to the "Nodes" tab
3. Change CPUs to another floating point

The field should not be considered invalid

## Trade-offs
- Setting `novalidate` on this form makes us miss out on browser validation (e.g.: people can put letters into an `input[type="number"]`)
- We're setting `novalidate` on this form, but there may be other forms where we have this issue that we just haven't caught yet

## Dependencies
None

## Screenshots
Before:
floatingpoint-broken

After:
floatingpoint-fixed

### CODE REVIEW

**Comment by mperrotti** [comment]
@GeorgiSTodorov - can you send me a screen capture? I can't reproduce

intlnumberinput

**Comment by GeorgiSTodorov** [comment]
@mperrotti , I started recording a gif, but I realized I have no way of showing that I am pressing "," and not delete.

**Comment by mperrotti** [comment]
@GeorgiSTodorov That's ok, I understand you're pressing comma. I mostly just want to see if you're doing something different from me.

Is it only happening in 1.11?

**Comment by GeorgiSTodorov** [comment]
Yes, I have only see it happen in 1.11.

**Comment by brandonc** [comment]
Can confirm. As soon as I press "," in firefox, the entire input is deleted.

**Comment by mperrotti** [comment]
@GeorgiSTodorov  - what language are you testing that 1.11 issue in? I've been using French, and I can't reproduce the issue you're seeing

i18nnumberinput

**Pull request merged**
