### PR TITLE
DCOS-19033: Update Badges to match UI Kit (2nd try)

### PR DESCRIPTION
**Pull request by juliangieseke**
This is a new PR for an old already merged one, it looks like some rebasing went wrong 🤔 

Old PR: https://github.com/dcos/dcos-ui/pull/2451

### CODE REVIEW

**Comment by juliangieseke** [comment]
Alfred test this

**Comment by juliangieseke** [comment]
> ENOMEM: not enough memory, read
        at Error (native)

 Alfred test this, please.

**Comment by juliangieseke** [comment]
@leemunroe as mentioned in slack, can you please check this one again? looks like the styles are "wrong"(?) and its still with rounded edges.

**Comment by Poltergeist** [comment]
Alfred please test this

**Comment by juliangieseke** [comment]
Alfred test this

**Pull request merged**
