### PR TITLE
test(DCOS-12816): Create an app with service address

### PR DESCRIPTION
**Pull request by tnguyen0**
This PR adds a system test for creating an app with service address.

To run the test:
```
docker run -it --rm --ipc=host \
    -v `pwd`:/dcos-ui \
    -e CLUSTER_URL=$openCluster \
    mesosphere/dcos-ui dcos-system-test-driver --only "apps"  \
    ./system-tests/driver-config/cluster.sh
```

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by jfurrow** [comment]
This failed for me :(

`✘ Services Applications should create an app with service address`

**Comment by tnguyen0** [comment]
Run integration tests

**Comment by weblancaster** [comment]
After running I had 5 failing tests but none of them are yours.

screen shot 2017-06-12 at 4 04 04 pm

**Comment by jfurrow** [comment]
I'm seeing the same as @weblancaster, so this is good to go!

**Pull request merged**
