### PR TITLE
[2 of 2] Render SVG sidebar icons if they exist

### PR DESCRIPTION
**Pull request by jfurrow**
This allows us to specify both SVG components and strings as page icon. This should only be necessary for a short time until we move all icons to SVG.

Also depends on #414

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @daiyiwhale

**Comment by jfurrow** [comment]
retest this please

**Comment by jfurrow** [comment]
retest this please

**Comment by rcorral** [comment]
retest this please

**Comment by rcorral** [comment]
retest this please

**Pull request merged**
