### PR TITLE
Fix integration tests

### PR DESCRIPTION
**Pull request by daiyiwhale**
This fixes some of the integration tests \o/

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @kennyt

**Comment by orlandohohmeier** [comment]
There are still 4 tests failing... 
```
  1) Service Actions Destroy Action shows error message on conflict:
     Error: Invariant Violation: Objects are not valid as a React child (found: object with keys {message}). 

  2) Service Actions Destroy Action shows error message on not authorized:
     Error: Invariant Violation: Objects are not valid as a React child (found: object with keys {message}). 

  3) Service Versions Configuration Tab opens correct edit modal of the selected service version:
     TypeError: Cannot read property 'overlays' of undefined
 
  4) Service Versions Configuration Tab opens correct edit modal of the selected service version:
     TypeError: Cannot read property 'overlays' of undefined
```

**Comment by daiyiwhale** [comment]
All fixed \o/

**Comment by jfurrow** [comment]
Nice! :ship:

**Comment by orlandohohmeier** [comment]
Fixed one last "issue" with the job detail tests...

**Comment by orlandohohmeier** [comment]
> `146 passing (4m)`
> `19 pending`

**Pull request merged**
