### PR TITLE
Drozhkov/dcos 21044 fix sdk tasks health

### PR DESCRIPTION
**Pull request by Fabs**
Reopen that https://github.com/dcos/dcos-ui/pull/2727

now hooks for test will work.

Please look at the other PR for the history.

### CODE REVIEW

**Comment by Fabs** [comment]
@DanielMSchmidt can you please look again?

**Comment by nLight** [comment]
Alfred test this

**Comment by juliangieseke** [comment]
Alfred test this

**Comment by ahoskins** [comment]
alfred test this

**Comment by DanielMSchmidt** [comment]
\cc @nLight can you do a backport PR to 1.11 and link it here?

**Comment by nLight** [comment]
https://github.com/dcos/dcos-ui/pull/2747 🙇

**Pull request merged**
