### PR TITLE
Revert 2858 fabs/1.11/fix/dcos 21784 mesos stream microtask

### PR DESCRIPTION
**Pull request by juliangieseke**
second try of #2887

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
I don't get how I can validate / review this

**Comment by nLight** [comment]
run integration tests

**Comment by ahoskins** [comment]
run integration tests

**Comment by juliangieseke** [comment]
these tests failed six times in a row in pipeline, are we sure its just flaky?

**Comment by juliangieseke** [comment]
ping @orlandohohmeier @Fabs

**Comment by ahoskins** [comment]
run integration tests

**Comment by ahoskins** [comment]
run integration tests

**Comment by DanielMSchmidt** [comment]
run integration tests

**Comment by Fabs** [comment]
@juliangieseke the revert should not have broken the test. I will take a look.

**Comment by Fabs** [comment]
run integration test

**Comment by Fabs** [comment]
run integration tests

**Comment by Fabs** [comment]
run integration tests

**Comment by Fabs** [comment]
@juliangieseke it is not triggering integration tests again 😢

**Comment by juliangieseke** [comment]
We disabled the old setup, 1.11 is pipeline now 👍

**Comment by nLight** [comment]
@juliangieseke I doubt it's legit. Volumes tests are known to be flaky

**Comment by juliangieseke** [comment]
flaky, yes. but this isnt flaky: https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/frontend%2Fdcos-ui-oss-pipeline/activity?branch=PR-2891-merge (red 7 of 7 times…)

**Comment by juliangieseke** [comment]
After looking into the runs: your right, not a single test failed in all runs 🤔

**Comment by nLight** [comment]
@Poltergeist there will be a follow-up PR addressing the issue

**Comment by Poltergeist** [comment]
@nLight so we are going to force merge this without green tests?

**Comment by nLight** [comment]
@Poltergeist ah, you mean flaky tests, no we're waiting for 🍏

**Pull request merged**
