### PR TITLE
DCOS-40039: add tasks column again

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
## Testing

- Check if tasks are back in the Nodes Table

## Trade-offs

- went for a simple revert of the commit in the previous PR: b20961eb0cc9bc0043428e4462187e84af0adac6

## Dependencies

None

### CODE REVIEW

**Comment by Fabs** [comment]
should it show 0 for 0, or empty is fine?

image

**Comment by DanielMSchmidt** [comment]
@lilysamimi What do you say about nodes with no tasks

**Comment by lilysamimi** [comment]
It should show 0 when there are no tasks.

**Comment by Fabs** [comment]
Nice 
image

**Pull request merged**
