### PR TITLE
↩️ fix(JSONReducers/Containers): delete protocol field on ADD_ITEM

### PR DESCRIPTION
**Pull request by nLight**
Backporting #2416 

Closes DCOS-18696

### CODE REVIEW

**Comment by nLight** [comment]
Alfred test this please

**Comment by nLight** [comment]
Alfred retest this please

**Comment by orlandohohmeier** [comment]
Alfred would you be so kind and retest this one please?

**Comment by orlandohohmeier** [comment]
LGTM! 🚢

**Pull request merged**
