### PR TITLE
DCOS-19401: refactor(externalVolumes): add external volumes logic to volumes

### PR DESCRIPTION
**Pull request by Poltergeist**
Based on #2559 (MERGED)

This PR introduces the externalVolumes logic to the now called volumes reducers.

This is the second of three PR's which will merge external and local volumes

### CODE REVIEW

**Comment by juliangieseke** [comment]
Alfred test this

**Comment by ahoskins** [comment]
@Poltergeist *Note*: this issue is not happening on #2561 👏

**Comment by Poltergeist** [comment]
Yes sorry forgot to note this here. As there are two ways to handle external volumes in this PR the form will not work as expected, this is also why the test does fail. But this was impossible to avoid by keeping the PR as small as possible. So as soon as you enter the JSON editor and do something chaos breaks loose. As the parser will parse a *volume* and a *externalVolume* from one volume.

**Comment by Poltergeist** [comment]
Alfred retest this please

**Pull request merged**
