### PR TITLE
Defaulting to string, where it is set to not change value type

### PR DESCRIPTION
**Pull request by mlunoe**
Was hitting a warning with this property being required, where it should not be

### CODE REVIEW

**Comment by jfurrow** [comment]
We assign a default value of an empty string to `searchString`, so I am wondering how you were able to get the warning?

Furthermore, since we explicitly pass this property to controlled `input` element, so we should never allow the value to ever be `null` or `undefined`.

**Comment by mlunoe** [comment]
The problem is exactly `null`, which will override the default assignment of empty string. What is the problem of having `null` or `undefined` as the value for an input field? We do that a lot of places

**Comment by jfurrow** [comment]
Because then we will be switching between controlled inputs and uncontrolled inputs, and it will throw warnings in React 15.  https://facebook.github.io/react/docs/forms.html#controlled-components

But if we are doing it elsewhere then I guess we'll just fix them all at once when we upgrade.

**Comment by mlunoe** [comment]
ok, that's fair. We should follow the recommendations for React.
I've changed users of the component to default to an empty string

**Comment by mlunoe** [comment]
One thing though is that we probably should is to introduce a linting rule about not using mixed types for the same variable. Then we wouldn't hit these warnings again

**Comment by philipnrmn** [comment]
Looks good!

Can we also avoid getting this warning in future implementations by checking `target.value` in the `handleChange` event of [FilterInputText](https://github.com/dcos/dcos-ui/blob/master/src/js/components/FilterInputText.js#L38)?

**Comment by mlunoe** [comment]
@philipnrmn: Fixed!

**Comment by philipnrmn** [comment]
Separately, this PR highlights a pre-existing performance issue - each of the affected components has many children and some form of tabular data. The data gets re-filtered, and the component and all its children get completely re-rendered, on each search string change. 

In the future, we should trap and handle circumstances where the user has cleared the input and handle them by not applying the filter, avoiding the costly filter.

Separately, the filter should not be called in `render`, which circumvents `shouldComponentUpdate`.

**Comment by mlunoe** [comment]
I would actually argue to do the filtering in render, unless you have large amounts of data. I can't remember where I read it, but it comes from the "do more in render()" pattern. They even use it as an example here: https://facebook.github.io/react/docs/thinking-in-react.html#step-2-build-a-static-version-in-react

**Comment by philipnrmn** [comment]
Kind of academic at this point, but it's a Friday afternoon so here's my $0.02:

Maybe the example isn't a perfect illustration of your point, but if the props/state data in that component changes, the view always needs re-rendering. In the `HealthTab` and similar, every keystroke in the search input triggers a re-render, and we don't know until we've performed the filter whether it's necessary or not. 

So I reckon the idiomatic way of doing it is to filter before setting state and then use checks in `shouldComponentUpdate` to prevent unnecessary renders.

**Pull request merged**
