### PR TITLE
Ensure ports are only added if either name or lbPort is set

### PR DESCRIPTION
**Pull request by Poltergeist**
image
Before when the user opened the deploy service modal and toggled to the JSON mode one port was set by default. This fix makes sure that only ports with a set name or lbPort are added.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @mlunoe

**Comment by rcorral** [comment]
Good catch!

**Comment by orlandohohmeier** [comment]
The code looks to me. Please adjust the respective test cases as well, as the checks are failing.

**Comment by pierlo-upitup** [comment]
Not too sure we actually want this. Let's keep it open and revisit this later.

**Comment by pierlo-upitup** [comment]
@rcorral suggests we need this.

**Comment by MatApple** [comment]
@Poltergeist @aldipower Are you guys able to fix the tests here so we can merge? Thanks guys! Nice work

**Pull request merged**
