### PR TITLE
1066 - Integration tests for edit, scale, suspend and destroy actions

### PR DESCRIPTION
**Pull request by aldipower**
This adds the integration tests for edit, scale, suspend and destroy actions buttons…

Related PR #390

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @daiyiwhale

**Comment by pierlo-upitup** [comment]
```
  100 passing (5m)
  19 pending
  6 failing

  1) Service Actions Destroy Action disables button during API request:
     CypressError: Timed out retrying: expected '<button.button.button-danger>' to have class 'disabled'
      at Object.$Cypress.Utils._.cypressErr (http://localhost:2020/__cypress/static/js/cypress.js:4689:15)
      at Object.$Cypress.Utils._.throwErr (http://localhost:2020/__cypress/static/js/cypress.js:4653:22)
      at Object.$Cypress.Utils._.throwErrByPath (http://localhost:2020/__cypress/static/js/cypress.js:4681:21)
      at $Cypress.Cy.extend._retry (http://localhost:2020/__cypress/static/js/cypress.js:5600:26)
      at http://localhost:2020/__cypress/static/js/cypress.js:7618:28
      at i (http://localhost:2020/__cypress/static/js/vendor.js:581:40)
      at e._settlePromiseFromHandler (http://localhost:2020/__cypress/static/js/vendor.js:580:5260)
      at e._settlePromiseAt (http://localhost:2020/__cypress/static/js/vendor.js:580:6529)
      at e._settlePromises (http://localhost:2020/__cypress/static/js/vendor.js:580:8394)
      at i._drainQueue (http://localhost:2020/__cypress/static/js/vendor.js:579:3183)
      at i._drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:3244)
      at MutationObserver.drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:1186)

  2) Service Actions Destroy Action reenables button after faulty request:
     CypressError: Timed out retrying: expected '<button.button.button-danger>' to have class 'disabled'
      at Object.$Cypress.Utils._.cypressErr (http://localhost:2020/__cypress/static/js/cypress.js:4689:15)
      at Object.$Cypress.Utils._.throwErr (http://localhost:2020/__cypress/static/js/cypress.js:4653:22)
      at Object.$Cypress.Utils._.throwErrByPath (http://localhost:2020/__cypress/static/js/cypress.js:4681:21)
      at $Cypress.Cy.extend._retry (http://localhost:2020/__cypress/static/js/cypress.js:5600:26)
      at http://localhost:2020/__cypress/static/js/cypress.js:7618:28
      at i (http://localhost:2020/__cypress/static/js/vendor.js:581:40)
      at e._settlePromiseFromHandler (http://localhost:2020/__cypress/static/js/vendor.js:580:5260)
      at e._settlePromiseAt (http://localhost:2020/__cypress/static/js/vendor.js:580:6529)
      at e._settlePromises (http://localhost:2020/__cypress/static/js/vendor.js:580:8394)
      at i._drainQueue (http://localhost:2020/__cypress/static/js/vendor.js:579:3183)
      at i._drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:3244)
      at MutationObserver.drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:1186)

  3) Service Actions Scale Action disables button during API request:
     CypressError: Timed out retrying: expected '<button.button.button-primary.button-medium>' to have class 'disabled'
      at Object.$Cypress.Utils._.cypressErr (http://localhost:2020/__cypress/static/js/cypress.js:4689:15)
      at Object.$Cypress.Utils._.throwErr (http://localhost:2020/__cypress/static/js/cypress.js:4653:22)
      at Object.$Cypress.Utils._.throwErrByPath (http://localhost:2020/__cypress/static/js/cypress.js:4681:21)
      at $Cypress.Cy.extend._retry (http://localhost:2020/__cypress/static/js/cypress.js:5600:26)
      at http://localhost:2020/__cypress/static/js/cypress.js:7618:28
      at i (http://localhost:2020/__cypress/static/js/vendor.js:581:40)
      at e._settlePromiseFromHandler (http://localhost:2020/__cypress/static/js/vendor.js:580:5260)
      at e._settlePromiseAt (http://localhost:2020/__cypress/static/js/vendor.js:580:6529)
      at e._settlePromises (http://localhost:2020/__cypress/static/js/vendor.js:580:8394)
      at i._drainQueue (http://localhost:2020/__cypress/static/js/vendor.js:579:3183)
      at i._drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:3244)
      at MutationObserver.drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:1186)

  4) Service Actions Scale Action reenables button after faulty request:
     CypressError: Timed out retrying: expected '<button.button.button-primary.button-medium>' to have class 'disabled'
      at Object.$Cypress.Utils._.cypressErr (http://localhost:2020/__cypress/static/js/cypress.js:4689:15)
      at Object.$Cypress.Utils._.throwErr (http://localhost:2020/__cypress/static/js/cypress.js:4653:22)
      at Object.$Cypress.Utils._.throwErrByPath (http://localhost:2020/__cypress/static/js/cypress.js:4681:21)
      at $Cypress.Cy.extend._retry (http://localhost:2020/__cypress/static/js/cypress.js:5600:26)
      at http://localhost:2020/__cypress/static/js/cypress.js:7618:28
      at i (http://localhost:2020/__cypress/static/js/vendor.js:581:40)
      at e._settlePromiseFromHandler (http://localhost:2020/__cypress/static/js/vendor.js:580:5260)
      at e._settlePromiseAt (http://localhost:2020/__cypress/static/js/vendor.js:580:6529)
      at e._settlePromises (http://localhost:2020/__cypress/static/js/vendor.js:580:8394)
      at i._drainQueue (http://localhost:2020/__cypress/static/js/vendor.js:579:3183)
      at i._drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:3244)
      at MutationObserver.drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:1186)

  5) Service Actions Suspend Action disables button during API request:
     CypressError: Timed out retrying: expected '<button.button.button-primary>' to have class 'disabled'
      at Object.$Cypress.Utils._.cypressErr (http://localhost:2020/__cypress/static/js/cypress.js:4689:15)
      at Object.$Cypress.Utils._.throwErr (http://localhost:2020/__cypress/static/js/cypress.js:4653:22)
      at Object.$Cypress.Utils._.throwErrByPath (http://localhost:2020/__cypress/static/js/cypress.js:4681:21)
      at $Cypress.Cy.extend._retry (http://localhost:2020/__cypress/static/js/cypress.js:5600:26)
      at http://localhost:2020/__cypress/static/js/cypress.js:7618:28
      at i (http://localhost:2020/__cypress/static/js/vendor.js:581:40)
      at e._settlePromiseFromHandler (http://localhost:2020/__cypress/static/js/vendor.js:580:5260)
      at e._settlePromiseAt (http://localhost:2020/__cypress/static/js/vendor.js:580:6529)
      at e._settlePromises (http://localhost:2020/__cypress/static/js/vendor.js:580:8394)
      at i._drainQueue (http://localhost:2020/__cypress/static/js/vendor.js:579:3183)
      at i._drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:3244)
      at MutationObserver.drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:1186)

  6) Service Actions Suspend Action reenables button after faulty request:
     CypressError: Timed out retrying: expected '<button.button.button-primary>' to have class 'disabled'
      at Object.$Cypress.Utils._.cypressErr (http://localhost:2020/__cypress/static/js/cypress.js:4689:15)
      at Object.$Cypress.Utils._.throwErr (http://localhost:2020/__cypress/static/js/cypress.js:4653:22)
      at Object.$Cypress.Utils._.throwErrByPath (http://localhost:2020/__cypress/static/js/cypress.js:4681:21)
      at $Cypress.Cy.extend._retry (http://localhost:2020/__cypress/static/js/cypress.js:5600:26)
      at http://localhost:2020/__cypress/static/js/cypress.js:7618:28
      at i (http://localhost:2020/__cypress/static/js/vendor.js:581:40)
      at e._settlePromiseFromHandler (http://localhost:2020/__cypress/static/js/vendor.js:580:5260)
      at e._settlePromiseAt (http://localhost:2020/__cypress/static/js/vendor.js:580:6529)
      at e._settlePromises (http://localhost:2020/__cypress/static/js/vendor.js:580:8394)
      at i._drainQueue (http://localhost:2020/__cypress/static/js/vendor.js:579:3183)
      at i._drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:3244)
      at MutationObserver.drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:579:1186)
```

**Comment by aldipower** [comment]
retest this please

**Comment by aldipower** [comment]
retest this please

**Comment by aldipower** [comment]
retest this please

**Comment by aldipower** [comment]
retest this please

**Comment by aldipower** [comment]
retest this please

**Comment by aldipower** [comment]
retest this please

**Comment by aldipower** [comment]
retest this please

**Comment by aldipower** [comment]
retest this please

**Comment by aldipower** [comment]
retest this please

**Comment by aldipower** [comment]
oohu9

**Comment by aldipower** [comment]
They passssedddd!!! WTF :))

**Pull request merged**
