### PR TITLE
Introduce Babel Polyfill

### PR DESCRIPTION
**Pull request by daiyiwhale**
Previously introduced by @aldipower into our unified-ui feature branch and now being introduced into master in anticipation of `_`-free project

### CODE REVIEW

**Comment by daiyiwhale** [comment]
Oddly enough `babel-polyfill` is already in the shrinkwrap.

**Comment by daiyiwhale** [comment]
Also, any idea why tests are failing? :/

**Comment by kennyt** [comment]
my guess is that it's running out of space. reading the console it says that in places

**Comment by kennyt** [comment]
px

**Pull request merged**
