### PR TITLE
Update button-collection component spacing

### PR DESCRIPTION
**Pull request by ashenden**
Very minor style tweak to support changes needed for the oAuth UI.
Review and merge this related PR: https://github.com/mesosphere/dcos-ui-plugins-private/pull/722

### CODE REVIEW

**Comment by Poltergeist** [comment]
run integration tests

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
Could you please provide a screenshot of what's changed? 
If it's oAuth (open source) why do we need changes in plugins?

This is what I'd expect to see changed, open source oauth login screen
screen shot 2018-01-31 at 11 37 53

**Comment by ashenden** [comment]
@nLight this actually has nothing to do with the oAuth screen.  The branch was originally created thinking we could do all the oAuth work in the dcos-ui codebase, before realizing that markup/styles is hosted externally. But the work here is a small tweak to the `.button-collection` component.

**Comment by Fabs** [comment]
I would need some instruction on how to enable SAML or OpenID and how to test this.

**Comment by nLight** [comment]
@fabs, adding to the secret knowledge...

**Comment by nLight** [comment]
Safe to merge separately.

**Pull request merged**
