### PR TITLE
Update reactjs-components to 0.16.0-beta.13

### PR DESCRIPTION
**Pull request by jfurrow**
This PR updates `reactjs-components` to `0.16.0-beta.13` which includes the following changes:
1. [Specify c++ version for Travis build](https://github.com/mesosphere/reactjs-components/pull/389)
2. [Update stylelint deps](https://github.com/mesosphere/reactjs-components/pull/388)
3. [Make virtual list bind its onScroll function correctly](https://github.com/mesosphere/reactjs-components/pull/391)
4. [Fix modal height calculations in IE11](https://github.com/mesosphere/reactjs-components/pull/393)
5. [Explicitly set dropdown positioning properties to auto](https://github.com/mesosphere/reactjs-components/pull/394)
6. [Push commit and tags in release script](https://github.com/mesosphere/reactjs-components/pull/395)
7. [Properly remove event listener](https://github.com/mesosphere/reactjs-components/pull/396)

**Checklist**
- [ ] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by jfurrow** [comment]
run unit tests

**Comment by jfurrow** [comment]
There's a legit unit test failing here. I'm debugging now.

**Comment by jfurrow** [comment]
run unit tests

**Comment by rcorral** [comment]
works great, and built and tested it locally

**Comment by mlunoe** [comment]
Same here!

**Comment by mlunoe** [comment]
Retest this please

**Pull request merged**
