### PR TITLE
Upgrade reactjs-components to current version

### PR DESCRIPTION
**Pull request by Poltergeist**

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @orlandohohmeier

**Comment by kennyt** [comment]
conflicts

px

i think you might've published it publicly. we've been doing beta releases with `npm publish ./ --tag -beta.28`

**Comment by Poltergeist** [comment]
damn why there are flicts?

**Comment by mlunoe** [comment]
@Poltergeist You can unpublish this https://docs.npmjs.com/cli/unpublish, and publish a beta version in stead

**Comment by Poltergeist** [comment]
@mlunoe you may only unpublish within the first 24 hours of the release.

**Comment by orlandohohmeier** [comment]
**mesosphere-ci** retest this please

**Pull request merged**
