### PR TITLE
Fix multi container volumes name

### PR DESCRIPTION
**Pull request by philipnrmn**
This PR corrects a spelling error in the filename of the multi container volumes form.

### CODE REVIEW

**Comment by rcorral** [comment]
run integration tests

**Comment by rcorral** [comment]
Aaaand your tiny PR now has conflicts.

**Comment by mlunoe** [comment]
Rebased it for you

**Comment by Poltergeist** [comment]
Looks good to me.

**Comment by philipnrmn** [comment]
retest this please

**Comment by mlunoe** [comment]
run unit tests

**Pull request merged**
