### PR TITLE
Introduce service volumes tab

### PR DESCRIPTION
**Pull request by orlandohohmeier**
--- 
~~⚠️  This branch is still work in progress – don't merge! It also depends on features that will be introduced with #327, thus it will not work until the respective branch is merged.~~

---
Introduce a service volumes tab to display all the volumes that are linked to a service. 

/cc @kennyt

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @MatApple

**Comment by mlunoe** [comment]
Rebased this for you @orlandohohmeier

**Comment by rcorral** [comment]
@orlandohohmeier looks good, could we remove the WIP?

**Comment by pierlo-upitup** [comment]
retest this please

**Pull request merged**
