### PR TITLE
DCOS-19012: Update Page Header to match UI Kit

### PR DESCRIPTION
**Pull request by ashenden**
The DC/OS UI Kit has made a number of improvements and adjustments to the appearance of the Page Header, the breadcrumbs, and page header navigation. The styles that define the Page Headers, as well as the variables that drive these styles, have been refactored to mirror the preferred appearance as well as make future maintenance of the sidebar easier.

**WARNING:** It is advised that we first merge PR #2454 prior to merging this PR.

### CODE REVIEW

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Pending dependencies

**Comment by MatApple** [comment]
alfred retest this please

**Comment by MatApple** [comment]
Alfred test this please

**Comment by ashenden** [comment]
Alfred test this please

**Comment by MatApple** [comment]
@ashenden I'm going to fix the test

**Comment by MatApple** [comment]
@ashenden it's a known flaky test which we have a fix for in https://github.com/dcos/dcos-ui/pull/2521

**Pull request merged**
