### PR TITLE
Unified UI

### PR DESCRIPTION
**Pull request by orlandohohmeier**
---
⚠️  Work in progress. Please merge!

---

This PR lays the foundation to unify the marathon and DC/OS UI. It introduces new data structures, views and actions to enable seamless service management.

* [x] Introduces new service structs 
* [x] Uses the Marathon groups instead of apps endpoint
* [x] Reworks the services page to include all services
* [x] Adds a basic service detail page
* [ ] Introduces a deployments view
* [x] Adds a sidebar to filter services
* [x] Reworks the task detail views
* [x] Introduces a progress/status bar 
* [ ] Adds a service configuration view
* [ ] Introduces a service debug view
* [ ] ...

### CODE REVIEW

**Comment by colin-msphere** [comment]
retest this please

**Comment by colin-msphere** [comment]
retest this please

**Comment by mesosphere-web** [comment]
Reviewer: @daiyiwhale

**Comment by kennyt** [comment]
one test is failing. let's fix that then :ship:

**Pull request merged**
