### PR TITLE
[BACKPORT] DCOS-21190: hide text if the service status is N/A on 1.11

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
---
# 🚨🚨🚨 THIS IS A BACKPORT to 1.11 🚨🚨🚨
---

**Checklist**
- [X] Did you add a JIRA issue in a commit message or as part of the branch name?
- [X] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [X] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
run integration tests

**Comment by juliangieseke** [comment]
adding high prio because its 1.11 👍 
@DanielMSchmidt can you please update it? 🙇

**Comment by juliangieseke** [comment]
run integration tests

**Comment by DanielMSchmidt** [comment]
@jgehrcke yay, green now 👍

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
Oh no, CI doesn't like the PR anymore 😱

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
run integration tests

**Pull request merged**
