### PR TITLE
Update eslint 3.14.1

### PR DESCRIPTION
**Pull request by mlunoe**
This PR updates the `eslint` and `eslint-plugin-react` packages to newest release.
This makes the linting work properly with the extension of the Airbnb base rules.
Note: all `let` -> `const` have been done using `--fix` the useless escapes have only been removed as pointed out by the linter.

### CODE REVIEW

**Comment by mlunoe** [comment]
Run unit tests

**Comment by nLight** [comment]
excitment

**Comment by mlunoe** [comment]
Run integration tests

**Comment by MatApple** [comment]
Nice work @mlunoe!

**Pull request merged**
