### PR TITLE
chore(deps): update dependency @dcos/eslint-config to v0.3.1

### PR DESCRIPTION
**Pull request by mesosphere-web**
This PR contains the following updates:

| Package | Type | Update | Change | References |
|---|---|---|---|---|
| @&#8203;dcos/eslint-config | devDependencies | patch | `0.3.0` -> `0.3.1` | [source](https://togithub.com/dcos-labs/eslint-config) |

---

### Release Notes

<details>
<summary>dcos-labs/eslint-config</summary>

### [`v0.3.1`](https://togithub.com/dcos-labs/eslint-config/blob/master/CHANGELOG.md#&#8203;031httpsgithubcomdcos-labseslint-configcomparev030v031-2018-02-20)

[Compare Source](https://togithub.com/dcos-labs/eslint-config/compare/v0.3.0...v0.3.1)

##### Bug Fixes

-   **test-names:** also capture Should in tests ([5e32110](https://togithub.com/dcos-labs/eslint-config/commit/5e32110))

</details>

---

### Renovate configuration

:date: **Schedule**: At any time (no schedule defined).

:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

:recycle: **Rebasing**: Whenever PR is stale, or if you modify the PR title to begin with "`rebase!`".

:no_bell: **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [x] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://renovatebot.com).

### CODE REVIEW

**Comment by mperrotti** [comment]
When I run `lint`, I get this error: 
```
Referenced from: /Users/mikep/dcos-ui/.eslintrc
Error: @dcos:
	Configuration for rule "test-names/blacklist-word-in-test-name" is invalid:
	Value "[object Object]" is the wrong type.
```

When I tried upgrading `eslint-plugin-test-names` to the latest version (2.1.1) and got this error:
```
Referenced from: /Users/mikep/dcos-ui/.eslintrc
Error: @dcos:
	Configuration for rule "test-names/blacklist-word-in-test-name" is invalid:
	Value "should" is the wrong type.
```

@DanielMSchmidt - do you know what the problem might be?

**Comment by GeorgiSTodorov** [comment]
I can confirm @mperrotti 's error.
screenshot from 2019-01-15 10-30-44

**Comment by DanielMSchmidt** [comment]
@GeorgiSTodorov @mperrotti The peer dependency was not met as we had pinned to an older version

**Comment by mesosphere-web** [comment]
### PR has been edited

:construction_worker: This PR has received other commits, so Renovate will stop updating it to avoid conflicts or other problems. If you wish to abandon your changes and have Renovate start over then you can add the label `rebase` to this PR and Renovate will reset/recreate it.

**Comment by mesosphere-web** [comment]
### Renovate Ignore Notification

As this PR has been closed unmerged, Renovate will now ignore this update (0.3.1). You will still receive a PR once a newer version is released, so if you wish to permanently ignore this dependency, please add it to the `ignoreDeps` array of your renovate config.

If this PR was closed by mistake or you changed your mind, you can simply rename this PR and you will soon get a fresh replacement PR opened.

**Pull request closed without merging**
