### PR TITLE
DCOS-38900 - Fix build by removing type declaration.

### PR DESCRIPTION
**Pull request by Fabs**
Check out and build. If it builds without:

```
ERROR in /Users/ahoy/ship/dcos-ui/plugins/jobs/src/js/JobsOverview.tsx
[tsl] ERROR in /Users/fabs/ship/dcos-ui/plugins/jobs/src/js/JobsOverview.tsx(158,18)
      TS2352: Type 'Observable<any>' cannot be converted to type 'Observable<{ data: { jobs: JobConnection; }; }>'.

ERROR in /Users/ahoy/ship/dcos-ui/plugins/jobs/src/js/JobsOverview.tsx
[tsl] ERROR in /Users/fabs/ship/dcos-ui/plugins/jobs/src/js/JobsOverview.tsx(158,18)
      TS2352: Type 'Observable<any>' cannot be converted to type 'Observable<{ data: { jobs: JobConnection; }; }>'.
  Property 'buffer' is missing in type 'Observable<any>'.
```

Yay!

### CODE REVIEW

**Comment by Fabs** [comment]
Oh no, CI does not like it:

```
ERROR in /jenkins/workspace/cos-ui-oss-pipeline_PR-3049-AVOMJSOKLHU2ZPMK3RM5IINGXGPM3SUMPBPIFQQUGKUXKZEY7DDA/plugins/jobs/src/js/JobsOverview.tsx

[tsl] ERROR in /jenkins/workspace/cos-ui-oss-pipeline_PR-3049-AVOMJSOKLHU2ZPMK3RM5IINGXGPM3SUMPBPIFQQUGKUXKZEY7DDA/plugins/jobs/src/js/JobsOverview.tsx(163,27)

      TS2339: Property 'data' does not exist on type '{}'.
```

**Comment by nLight** [comment]
```
WARNING in ./src/js/plugin-bridge/Loader.js

Module not found: Error: Can't resolve '#EXTERNAL_PLUGINS/index.js' in '/jenkins/workspace/cos-ui-oss-pipeline_PR-3049-AVOMJSOKLHU2ZPMK3RM5IINGXGPM3SUMPBPIFQQUGKUXKZEY7DDA/src/js/plugin-bridge'
```

That one I also don't like

**Comment by Fabs** [comment]
@nLight had a different idea that builds on my machine, let's see what CI does. cc/ @orlandohohmeier and @juliangieseke.

**Comment by Fabs** [comment]
Build failed because of a system test. I think now we have something that pass CI.

**Comment by juliangieseke** [comment]
The Issue @nLight mentioned is unrelated and there is a JIRA for that already

**Pull request merged**
