### PR TITLE
Change LogView container offset

### PR DESCRIPTION
**Pull request by rcorral**
When I was testing out the log viewer I noticed that if I scrolled up a  little and a new log line would come through, the autoscroll would kick in, thinking that I was at the bottom, but I scrolled up just a bit. This confused me and frustrated me, so I've lowered this buffer that we have to something really small.

**Checklist**
- [ ] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by mlunoe** [comment]
Run integration tests

**Comment by rcorral** [comment]
run unit tests

**Comment by mlunoe** [comment]
Looks good mah dudes :sunglasses:

**Comment by jfurrow** [comment]
Works well for me.

**Pull request merged**
