### PR TITLE
chore: double quote paths so that it allows spaces

### PR DESCRIPTION
**Pull request by nLight**
I've messed up my new laptop setup and now I have a space in my home directory name 😩 
Because of that I realized that our scripts don't support that. So I double quoted everything that `shellcheck` asked me to double quote and what made sense to me.

On top of that I followed its advice and added `:?` to `rm -rf ${VAR}` so it become `rm -rf ${VAR:?}` so that if `$VAR` for whatever reason empty we don't kill `/`

## Testing

Try running those scripts from a path that has a space in it.

## Trade-offs

There are some more stuff `shellcheck` complains about. I decided keeping the scope rather small.

### CODE REVIEW

**Comment by nLight** [comment]
@juliangieseke yes, I did that and it has created a new user instead. Now I'm recovering my configs and stuff

**Comment by nLight** [comment]
@orlandohohmeier puts a smiley but no ✅ :)

**Comment by orlandohohmeier** [comment]
LGTM! 🚢

**Comment by orlandohohmeier** [comment]
@nLight forgot to submit my review... 🤦‍♂️

**Pull request merged**
