### PR TITLE
DCOS-37432 - [1.11] improve merge data

### PR DESCRIPTION
**Pull request by Fabs**
This is the porting of the 1.10 performance improvement #2960. 

Please note that on 1.11 we changed the name of the class, and stop getting the hostname on mergeData. I would test this with more care and see if we still showing the right data. 

**Checklist**
- [X] Did you add a JIRA issue in a commit message or as part of the branch name?
- [X] Did you add new unit tests?

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot integrate  
@mesosphere-mergebot ship-it  
@mesosphere-mergebot test  
```

**Comment by Fabs** [comment]
alfred run tests

**Comment by bstavroulakis** [comment]
rebased, waiting for tests to pass

**Comment by DanielMSchmidt** [comment]
@bstavroulakis I think I fixed that now, please take another look :)

**Comment by Fabs** [comment]
Those tests pass locally: I triggere a re-run
====> Successfully finished tests for pages/services/TasksTable-cy.js

**Comment by DanielMSchmidt** [comment]
Needs port of https://github.com/dcos/dcos-ui/pull/2982

**Comment by Fabs** [comment]
Rebased, should be reviewable now.

**Comment by Fabs** [comment]
This needs a small fix once #2987 lands.

**Comment by juliangieseke** [comment]
@Fabs #2987 got merged 👍

**Comment by Fabs** [comment]
@juliangieseke fixed.

**Comment by Fabs** [comment]
@DanielMSchmidt, @bstavroulakis or @juliangieseke could you check again?

**Pull request merged**
