### PR TITLE
DCOS 19054: Update Buttons to match UI kit

### PR DESCRIPTION
**Pull request by leemunroe**
Brings all of our buttons up to date with the latest UI kit design direction. Primary buttons are purple solid buttons. Secondary buttons are purple link buttons. This PR purposely doesn't touch the style of button group filter toggles or the layout of buttons in modals.

Examples
image
image
image
image

### CODE REVIEW

**Comment by MatApple** [comment]
@ashenden @leemunroe I think something isn't right with the rebase. Could you please rebase against the feature branch for UI Kit?

**Comment by MatApple** [comment]
@leemunroe @ashenden cleaned this up with some fun rebasing.

**Comment by leemunroe** [comment]
mesosphere-ci retest this please

**Comment by leemunroe** [comment]
retest this please

**Pull request merged**
