### PR TITLE
DCOS-51547: only use VirtualList for tables with large data sets

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
## Testing

- Check if all old tables work faster or equally fast

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
An integration test is failing.

**Comment by DanielMSchmidt** [comment]
@GeorgiSTodorov Do you have time to look into it? I won't get to it for the next couple of hours

**Comment by GeorgiSTodorov** [comment]
@DanielMSchmidt , I forgot to mention it in my last comment, but I am already investigating.

**Comment by GeorgiSTodorov** [comment]
@DanielMSchmidt , it looks like with this reactjs-components version, we no longer have two empty row in the table.
### Before
Screenshot from 2019-04-10 14-30-37

### Now
Screenshot from 2019-04-10 14-27-35

I will push a commit fixing `JobDetails-cy`, but I am pretty sure other integration tests will fail as well. Do you know a way to run all integration tests locally?

**Comment by GeorgiSTodorov** [comment]
Same thing in PodDetail now. I am still wondering if these is a way to run all integration tests locally like we could before.

**Comment by TattdCodeMonkey** [comment]
Testing this against soak the PodDetail page crashes and I get TypeErrors in the console.

**Comment by DanielMSchmidt** [comment]
Thank you for the pointers @TattdCodeMonkey 
I am currently trying to fix all tests, could you take a quick look?

**Comment by natmegs** [comment]
Investigating test failures

**Comment by brandonc** [comment]
🎉

**Pull request merged**
