### PR TITLE
↩️ [1.9] Improve UX for Package Install Beta opt-in

### PR DESCRIPTION
**Pull request by MatApple**
Backport of https://github.com/dcos/dcos-ui/pull/2201 to 1.9.

**Checklist**
- [ ] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by weblancaster** [comment]
Testing only this PR fails with the screenshot below (without #2201)
screen shot 2017-05-25 at 12 03 24 pm

**Comment by MatApple** [comment]
@weblancaster - I suggest checking out `release/1.9` branch of plugins, running `npm i` and then running `npm start` again.

**Comment by MatApple** [comment]
retest this please

**Comment by weblancaster** [comment]
@MatApple Thanks. I was able to run normally but I noticed a big decrease in performance/UI particularly related to the changes made.

**before**
before

**Comment by MatApple** [comment]
Thanks for the testing @weblancaster. I don't think those performance issues are related to these changes. If you test `beta-dse` on `release/1.9` branch and then on this branch, you'll find they both perform equally bad. It's a package with a large config that takes a longer time to load over the wire and second to that, our `SchemaForm` performs badly on such a large package.

Please validate again using the same package on `release/1.9` branch to keep all other variables equal. I'd also suggest testing the opening/closing of the modal at least 3 times to negate outlier test results.

**Comment by nLight** [comment]
Hey @orlandohohmeier, code looks good to me is there any particular reason for the `hold merge`?

**Comment by orlandohohmeier** [comment]
@nLight It's basically a back-port of #2201 and we shouldn't merge this one 'til we've addressed all the comments.

**Comment by orlandohohmeier** [comment]
We discussed the `hold merge` offline and decided to move forward with this PR even though the `master` fix is still on hold.

**Pull request merged**
