### PR TITLE
chore(reactjs-components): bump 0.17.1

### PR DESCRIPTION
**Pull request by juliangieseke**
this commit bumps reactjs-components to version ~0.17.0, also bumps
react-gemini-scrollbar to 2.3.4 because it is updated in
reactjs-components.~ 0.17.1

### CODE REVIEW

**Comment by juliangieseke** [comment]
Alfred please test this

**Comment by nLight** [comment]
Don't see how the only updated dependency - `react-gemini-scrollbar` could affect this https://github.com/noeldelgado/react-gemini-scrollbar/blob/master/CHANGELOG.md

**Comment by bstavroulakis** [comment]
The problem occurs from the react-gemini-scrollbar update. Once I install the 2.1.5 version the tests pass locally, once I upgrade to 2.2.0 they fail.

I researched today to find why this is happening without success.

In the FieldAutofocus.js I added
```
    console.log(input);
    input.focus();
```

and the input does appear in the console log in the Cypress test. But it just fails to focus on it. 
In the browsers that I tested this works, but for Cypress something changed with gemini-scrollbar.

I noticed in a commit that there is a new resize callback that removes/adds elements.

https://github.com/noeldelgado/gemini-scrollbar/commit/bcb291f2d354772f4c1f8a2be9506682a8a54614

And also it adds an object element on the page. Could this object element overlap maybe the elements that we want to focus on and Cypress doesn't find them?

image

**Comment by nLight** [comment]
Hey. @bstavroulakis! Thank you for research! Since we've lost some time here already, I've created a PR https://github.com/mesosphere/reactjs-components/pull/427 to just unblock this change. We will revisit the `cypress / gemini-scrollbar` issue on a latter stage if you guys don't mind.

**Comment by nLight** [comment]
Please try 0.17.1 reverting react-gemini-scrollbar to 2.1.5

**Comment by juliangieseke** [comment]
updated & rebased 👍 
🤞 that its ✅  now.

**Pull request merged**
