### PR TITLE
DCOS-8352 Show pretty cron schedule in job detail page

### PR DESCRIPTION
**Pull request by pierlo-upitup**
Worst-case scenario:

image

Sweet spot:
screen shot 2016-07-26 at 15 33 26

cc @leemunroe as we discussed, we're moving the schedule text below the heading. Here you go!

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @daiyiwhale

**Comment by leemunroe** [comment]
Nice one! Two things:

1. Can we start the line with `Scheduled to run every 0, 2, 4...` so it's clear what it is telling us?
2. Can we move it under the status?

Originally we had designed the status directly below the heading to the right of the icon. Was there a reason we didn't do that or did it get missed?

image

**Comment by jfurrow** [comment]
@leemunroe The status rendering below the icon is an application-wide change to the `PageHeader` component, which was requested by @ashenden.

**Comment by pierlo-upitup** [comment]
I will add the `Scheduled to run ...` copy.

**Comment by pierlo-upitup** [comment]
@leemunroe actually things can get tricky pretty quickly here. The schedule may start with "Every" but also with specific times and other variations. So, prepending `Scheduled to run ` is not going to work with schedules such as `01:00 on the 6th in Sep`. 

I'd suggest to address this outside of this PR and possibly with a simpler approach. One idea:

[ ] **Scheduled** Every other monday
[ ] **Scheduled** 01:00 on the 6th in Sep

**Comment by leemunroe** [comment]
@pierlo-upitup I'm not sure why `Scheduled to run` doesn't work here. `Scheduled to run 01:00 on the 6th in Sep` sounds good to me. But if you think there are situations it doesn't fit happy to fall back to your suggestion of `Scheduled`.

**Comment by pierlo-upitup** [comment]
Shouldn't it be `Scheduled to run AT (time)`, `Scheduled to run ON (week day)` etc.? I will go ahead with the **Scheduled** suggestion as it seems more future-proof.

**Comment by pierlo-upitup** [comment]
All feedback addressed. 

image

**Comment by leemunroe** [comment]
Sorry my fault for not being clear. In your screenshot it looks like `Scheduled` is a separate thing, it's bold and has a space to the right of it and then there's a capital `E` for Every. I'm suggesting it all reads as one sentence `Scheduled to run every 5th minute past every hour on the 1st in February`.

**Comment by Poltergeist** [comment]
👍 It is looking great to me, except the copy change. Please fix this.

**Comment by MatApple** [comment]
LGTM - lets get the copy changed and merge :)

**Comment by jfurrow** [comment]
Just a heads up, we can use the CSS selector `:first-letter` to change the casing of `Every` to `every`, but we can't change `Feb` to `February` unless we fork the [prettycron](https://github.com/azza-bazoo/prettycron) library.

**Comment by pierlo-upitup** [comment]
@leemunroe OK, that's exactly what I suggested here https://github.com/dcos/dcos-ui/pull/845#issuecomment-235575723 and I thought you confirmed it. Anyway, I will remove the bolding and make it look like a single sentence. :shipit:

**Comment by pierlo-upitup** [comment]
Following @jfurrow's suggestion the last commit adds a `.lowercase-first` class that does the trick.

image

**Comment by pierlo-upitup** [comment]
**mesosphere_ci** retest this please

**Comment by orlandohohmeier** [comment]
Seems like we lost the ellipsis from your first screenshot...

**Comment by pierlo-upitup** [comment]
@orlandohohmeier you're right. That's because `.lowercase-first` needs a block-level element for the `:first-letter`, but that doesnt play nice with the ellipsis... 

@jfurrow can you think of a fix here?

**Comment by pierlo-upitup** [comment]
In the end I decided to revert the CSS solution and to go for a `StringUtil.lowercase` function instead, as we already had a `capitalize` function. 

image

**Comment by pierlo-upitup** [comment]
Relevant tests are passing

image

**Comment by mlunoe** [comment]
@pierlo-upitup Let's make sure to run _all_ of the tests, this is what broke tests here:
https://github.com/dcos/dcos-ui/pull/865#issuecomment-236301669

I know this is overhead right now, but we're going to have to suck it in until we get it fixed

**Pull request merged**
