### PR TITLE
DCOS-12288: Replace pre-push with post-rewrite

### PR DESCRIPTION
**Pull request by nLight**
Let's liberate `git push` and address the problem of rebase artifacts the right way 💪 

PS. don't forget to unlink `pre-push` afterwards

### CODE REVIEW

**Comment by nLight** [comment]
retest this please

**Comment by orlandohohmeier** [comment]
Let's add an empty `pre-push` file so that the old links don't break.

**Comment by nLight** [comment]
@orlandohohmeier done 👍

**Comment by Poltergeist** [comment]
Luv it, mürge it!

**Pull request merged**
