### PR TITLE
Use FilterBar component

### PR DESCRIPTION
**Pull request by daiyiwhale**
Wrapping all filter bars with `FilterBar` component for consistent handling of wrapping and margins.

Depends on https://github.com/dcos/dcos-ui/pull/47.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @MatApple

**Comment by kennyt** [comment]
FilterBar might be one of my favorite components in the application now

**Comment by daiyiwhale** [comment]
<3

**Comment by mlunoe** [comment]
I think this can be rebased now

**Comment by daiyiwhale** [comment]
Rebased ✨

**Comment by rcorral** [comment]
Awesome work Chris!

**Pull request merged**
