### PR TITLE
Remove advanced config

### PR DESCRIPTION
**Pull request by kennyt**
Advanced config is no longer useful. Luckily it is only being used in one place and it essentially just passed the props down to `SchemaForm`

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @pierlo-upitup

**Comment by rcorral** [comment]
R.I.P advanced config.

**Comment by jfurrow** [comment]
Why is this being removed? The service configuration update relies on this.

**Comment by pierlo-upitup** [comment]
Would also love to have some more context.

**Comment by pierlo-upitup** [comment]
Thanks for the edit in the description, @kennyt – just saw that.

**Comment by pierlo-upitup** [comment]
@jfurrow does your comment block the merging of this PR?

**Comment by pierlo-upitup** [comment]
It certainly blocks https://github.com/dcos/dcos-ui/pull/212/files

**Comment by pierlo-upitup** [comment]
This other PR also depends on the AdvancedConfig component https://github.com/dcos/dcos-ui/pull/267 

Please remove the hold merge if you're fine with this, @Poltergeist

**Comment by Poltergeist** [comment]
This will not block #212 since the advanced config isn't used anymore. I got some minor changes in the advanced config but only because I introduced those changes earlier and they weren't needed anymore. So I am okay with removing the advanced config component.

**Comment by mlunoe** [comment]
The `AdvancedConfig` is just a wrapper fro `SchemaForm` and therefore has no purpose anymore

**Comment by jfurrow** [comment]
@pierlo-upitup No, my comment doesn't block this. :ship:

**Pull request merged**
