### PR TITLE
Updated DC/OS CLI installation link to latest.

### PR DESCRIPTION
**Pull request by ArmandGrillet**
The new DC/OS CLI is designed to work for any version of DC/OS >= 1.10.
We can thus safely use the latest release for the current and upcoming
versions of DC/OS.

### CODE REVIEW

**Comment by jaxesn** [comment]
Is there value in having a specific version link tho.  As we update, older clusters would still point to their respective version of the documentation?

**Comment by nLight** [comment]
@jaxesn I think CLI is version agnostic nowadays. Is that correct @AmrAbdelrazik? Why do we want to always point to the latest?

**Comment by jaxesn** [comment]
Oh yeah, sorry I was thinking docs for some reason, not cli 🤦‍♂️

**Comment by ArmandGrillet** [comment]
The new CLI is now version agnostic (works with any DC/OS version as long as it's>= 1.10). There will be no release for 1.12 thus the current link is currently broken on `master`.

**Comment by ArmandGrillet** [comment]
@juliangieseke Thanks for the help, the commit message should now be properly formatted.

**Pull request merged**
