### PR TITLE
chore(dss): remove dss plugin

### PR DESCRIPTION
**Pull request by Poltergeist**
**⚠️  depends on https://github.com/mesosphere/dcos-ui-plugins-private/pull/715 and vice versa**

Closes DCOS-20140

### CODE REVIEW

**Comment by Poltergeist** [comment]
alfred please test this

**Comment by weblancaster** [comment]
Alfred retest this please

**Comment by weblancaster** [comment]
Another flaky test. alfred test this please.

**Comment by Poltergeist** [comment]
Alfred test this.

**Comment by nLight** [comment]
Alfred test this

**Comment by juliangieseke** [comment]
Alfred test this

**Comment by Poltergeist** [comment]
Alfred you can't test this.

**Comment by Poltergeist** [comment]
Alfred you can't test this. 👯 👯‍♂️ 🎉

**Comment by DanielMSchmidt** [comment]
Alfred test this please :)

**Pull request merged**
