### PR TITLE
DCOS-40353: update grid/list toggle visual design

### PR DESCRIPTION
**Pull request by mperrotti**
## Testing
Go to the Nodes view, interact with the toggle buttons at the top-right of the screen

## Trade-offs
This is done by extending CNVS button component styles inside of dcos-ui

## Dependencies
None

## Screenshots
Before:
filterswitchicons_before

After:
filterswitchicons_after

### CODE REVIEW

**Comment by mperrotti** [comment]
Tagging @lilysamimi to confirm this matches what she specified in [her JIRA ticket](https://jira.mesosphere.com/browse/DCOS-40353)

**Comment by lilysamimi** [comment]
The gifs look great @mperrotti! Had trouble reproducing when I pulled this branch. The icons didn't show up for some reason when I test this on the 1.12 soak cluster. https://cl.ly/2j1Q3s3h341o

**Comment by tnguyen0** [comment]
The icons don't show up for me either 🤷‍♂️ . I put in other icons to test and they work.

**Comment by nLight** [comment]
Shall we align them, so that they are dead in the center?
screen shot 2018-08-21 at 10 30 22

**Comment by GeorgiSTodorov** [comment]
Icons are invisible for me as well, even after running `npm install`.

**Pull request merged**
