### PR TITLE
DCOS-8058: Add client side service id validation

### PR DESCRIPTION
**Pull request by orlandohohmeier**

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @daiyiwhale

**Comment by pierlo-upitup** [comment]
Nice, however I only get the validation to run on my second click... is that a known issue, @orlandohohmeier ?

**Comment by orlandohohmeier** [comment]
@pierlo-upitup Sorry, I should have mention it in the description. It's a known issue, which will hopefully be fixed with https://github.com/mesosphere/reactjs-components/pull/303.

**Comment by aldipower** [comment]
LGTM!

**Comment by Poltergeist** [comment]
Looks good to me. Let's 🚢  this.

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Pull request merged**
