### PR TITLE
chore: remove obsolete webpack-plugin optimize-css-assets-webpack-plugin

### PR DESCRIPTION
**Pull request by pierrebeitz**
it's not used anymore and brings quite a few deps. let's remove it!

### CODE REVIEW

**Comment by juliangieseke** [comment]
conflicts :/

**Comment by pierrebeitz** [comment]
resolved conflicts. i'm not able to make the diff any smaller, as ~1500 lines are removed from the `package-lock.json` and the order of stuff within there is changed quite a bit.

**Comment by pierrebeitz** [comment]
no, i failed to corretly resolve a conflict and only noticed when looking at the diff on github. 😄 
it's back!

**Comment by GeorgiSTodorov** [comment]
@pierrebeitz , file conflict.

**Comment by pierrebeitz** [comment]
resolved conflicts.

**Comment by GeorgiSTodorov** [comment]
Are so many package-lock changes expected?

**Comment by pierrebeitz** [comment]
Yupp!

**Pull request merged**
