### PR TITLE
Activating new create/edit service flow

### PR DESCRIPTION
**Pull request by mlunoe**
This PR activates the new create/edit service flow:

### CODE REVIEW

**Comment by MatApple** [comment]
@mlunoe - I think we should rename the component and get rid of the leading `New`. What do you think?

**Comment by mlunoe** [comment]
We're keeping the old modal in here, so we can switch back if we need to, until it is removed, let's keep the name

**Comment by rcorral** [comment]
Let's keep the old one for now, until we have full functionality with the new create flow.

**Comment by MatApple** [comment]
@mesosphere-ci test this please

**Comment by MatApple** [comment]
@mesosphere-ci test this please

**Pull request merged**
