### PR TITLE
DCOS-8109 Add spacing between icon and text

### PR DESCRIPTION
**Pull request by pierlo-upitup**
From
image

To 
image

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @MatApple

**Comment by pierlo-upitup** [comment]
**mesosphere_ci** retest this please

**Comment by jfurrow** [comment]
@pierlo-upitup Pushed a commit, feel free to merge if you're cool with my changes.

**Comment by pierlo-upitup** [comment]
Duh, of course! I blanked out ;-) 
Thanks!!!

**Pull request merged**
