### PR TITLE
DCOS-19292 - adds an extra edit button to Services

### PR DESCRIPTION
**Pull request by Fabs**
This was done to provide users with an alternative Edit button to help then easily perform this common task.

image

Thanks for the pariring @Poltergeist

### CODE REVIEW

**Comment by juliangieseke** [comment]
Alfred test this

**Comment by Fabs** [comment]
Alfred test this

**Comment by Fabs** [comment]
Alfred test this

**Comment by Fabs** [comment]
Alfred test this please

**Comment by Fabs** [comment]
Alfred test this porfavor

**Comment by Fabs** [comment]
Alfred test this

**Comment by Fabs** [comment]
Alfred test this

**Comment by ahoskins** [comment]
screen shot 2018-01-08 at 11 12 32 am

@leemunroe On this page we now have two different button texts that do the same thing. Thoughts on consolidating this?

**Comment by Fabs** [comment]
Alfred test this

**Comment by leemunroe** [comment]
@ahoskins I hear you but I think that is ok. At least it doesn't bother me as much as this view looking different depending if I'm looking at an app, pod or package :-/ we should fix that inconsistency (config headings/hierarchy, edit/download actions, version)

image

**Pull request merged**
