### PR TITLE
DCOS-13055: Introduce .container-wide and apply in CreateService modal

### PR DESCRIPTION
**Pull request by jfurrow**
This PR introduces `.container-wide` class and implements it in the CreateService modal.

### CODE REVIEW

**Comment by jfurrow** [comment]
run unit tests

**Comment by philipnrmn** [comment]
I'm seeing a weird artifact where the JSON editor briefly appears as the window is resized:

https://cl.ly/2v1h0d03193f

**Comment by jfurrow** [comment]
Good catch @philipnrmn! I pushed a commit to toggle the `visibility` property which should prevent this from happening.

**Comment by orlandohohmeier** [comment]
LGTM 💯 ✨

**Pull request merged**
