### PR TITLE
DCOS-14255: Clean up advanced package install review

### PR DESCRIPTION
**Pull request by jfurrow**
This PR fixes a bug where the advanced package install modal's review stage wasn't rendering properly in Firefox. The modal's body wasn't shrinking to allow for the modal footer to be visible.

I also reduced the complexity of the displayed configuration by simply passing it to `HashMapDisplay` which improves the consistency of this view.

Before:

After:

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [x] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by jfurrow** [comment]
run integration tests

**Comment by mlunoe** [comment]
Thanks for the fix and the quick turnaround! Let's ⛵️ this thing!

**Comment by nLight** [comment]
retest this please

**Comment by MatApple** [comment]
@jfurrow test is failing - `ReviewConfig-test.js`

**Comment by jfurrow** [comment]
Thanks @MatApple, I accidentally committed an `autoMockOff()` and removing it killed the tests — fixing now!

**Comment by jfurrow** [comment]
@MatApple Fixed!

**Pull request merged**
