### PR TITLE
DCOS-8168: Copy Error message parsing from service to job

### PR DESCRIPTION
**Pull request by Poltergeist**
This adds the error message parsing from the service form also to the jobs form

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @orlandohohmeier

**Comment by rcorral** [comment]
Code looks good, @orlandohohmeier could you give it a look?

**Comment by orlandohohmeier** [comment]
Let's double check the mapping with @aquamatthias

**Comment by pierlo-upitup** [comment]
After my commits:

image

**Comment by pierlo-upitup** [comment]
Removing hold merge label.

**Comment by rcorral** [comment]
Going to merge now.

**Pull request merged**
