### PR TITLE
chore: remove maintenance feature flag for readonly features

### PR DESCRIPTION
**Pull request by brandonc**
## Overview

This needs to be included in the MWT alpha and must be included in the release tomorrow

## Testing

- Visit nodes table and ensure you can see status column and status filters
- Visit node details tab and ensure you can see Status section

### CODE REVIEW

**Comment by pierrebeitz** [comment]
LGTM, will do proper testing ~13:30

**Comment by pierrebeitz** [comment]
the failing system-test seems unrelated. it's a service that stays in `deploying` while we expect it to be `running` eventually. pretty sure that's not related to these changes.

**Comment by nLight** [comment]
For some reason test cluster fails to launch the test task in time

**Comment by nLight** [comment]
Screenshot 2019-07-23 at 13 36 37

**Pull request merged**
