### PR TITLE
chore(eslint): use @dcos/eslint-config

### PR DESCRIPTION
**Pull request by nLight**
This PR should resolve the issue with `shrinkwrap`.

I moved our eslint config from `dcos/javascript` to `dcos-labs/eslint-config` and published the module `@dcos/eslint-config`.

dcos/javascript used to have tag 0.2.1 but the version was 0.2.0 so that's ok

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
Alfred test this please :)

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
run system tests

**Comment by nLight** [comment]
run system tests

**Comment by nLight** [comment]
run system tests

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
run system tests

**Comment by nLight** [comment]
Alfred test this

**Pull request merged**
