### PR TITLE
[System Tests]: DCOS-12814: Add SI tests for pod with artifacts

### PR DESCRIPTION
**Pull request by jfurrow**
This PR introduces the automated tests for [Create a simple pod with artifacts](https://wiki.mesosphere.com/pages/viewpage.action?pageId=101253131)

To run this test, use:

<pre>
docker run -it --rm --ipc=host \
  -e CLUSTER_URL=$CLUSTER_URL  \
  -v `pwd`:/dcos-ui \
  mesosphere/dcos-ui dcos-system-test-driver \
  ./system-tests/driver-config/dev.sh
</pre>

### CODE REVIEW

**Comment by weblancaster** [comment]
hey @jfurrow after running the command you provided I got this error below.

screen shot 2017-04-07 at 5 26 07 pm

**Comment by jfurrow** [comment]
@weblancaster Sorry, I think this needed a rebase. It should be working now!

**Comment by jfurrow** [comment]
Ping @MatApple @weblancaster

**Comment by mlunoe** [comment]
@jfurrow there are some konflicts here

**Comment by jfurrow** [comment]
@mlunoe Flicts fixed!

**Comment by weblancaster** [comment]
hey @jfurrow I have tested again and got this error. I pulled your branch fired up a OSS cluster and then run the test.

screen shot 2017-04-17 at 4 16 33 pm

**Comment by jfurrow** [comment]
Sorry @weblancaster I'm actually experiencing the same thing as you. It looks like a route has changed which breaks these tests. @wavesoft fixes this in his PR here: https://github.com/dcos/dcos-ui/pull/2114

**Comment by wavesoft** [comment]
image

Looks good to me! 💯  ✨

**Pull request merged**
