### PR TITLE
DCOS-11781: fix scroll view not set correctly in packages table

### PR DESCRIPTION
**Pull request by mlunoe**
---
⚠️ Depends on this PR: https://github.com/dcos/dcos-ui/pull/2116

---

This PR is the same as this just for the 1.9 release: https://github.com/dcos/dcos-ui/pull/2078

This PR fixes so the bottom packages in the table are always visible:

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [x] Did you add new integration tests?
- [x] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by rcorral** [comment]
run integration tests

**Comment by rcorral** [comment]
@mlunoe I'm running the tests again, but they failed on the test you just wrote: https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-ui-pulls-integration/4566/console

**Comment by mlunoe** [comment]
Argh, I forgot the depending change from reactjs-components! Will update this PR!

**Comment by mlunoe** [comment]
Created a PR for the reactjs-components update here: https://github.com/dcos/dcos-ui/pull/2116

**Pull request merged**
