### PR TITLE
Hide breadcrumb when Services Page is empty

### PR DESCRIPTION
**Pull request by daiyiwhale**
what it says on the box

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @aldipower

**Comment by jfurrow** [comment]
:boat:

**Comment by pierlo-upitup** [comment]
I think what we actually want is to only hide the `Services` breadcrumb if we are in the root node and it's empty. For all other sub-groups, we still want to display the breadcrumb.

Examples:

1. Group: `/`, # apps: `0`. No breadcrumb.
2. Group: `/`, # apps: `1+`. Show breadcrumb: `Services`
2. Group: `/group`, # apps: `0`. Show breadcrumb: `Services > group`
etc.

cc @leemunroe can you confirm?

**Comment by leemunroe** [comment]
That sounds right. Although I would also add if I'm in an empty group, I should still see the other UI (search, sidebar filters). The empty state should only apply when 0 apps and 0 folders.

Examples:

Group `/`, # apps `0`
image

Group `/test`, # apps `0`
image

**Comment by daiyiwhale** [comment]
That makes a lot of sense, thanks for the super clear examples @leemunroe!

**Comment by daiyiwhale** [comment]
Done!

**Comment by daiyiwhale** [comment]
@mesosphere-ci retest this please

**Comment by kennyt** [comment]
retest this please

**Comment by pierlo-upitup** [comment]
Thanks!

**Pull request merged**
