### PR TITLE
DCOS-11642: High-level marathon error handlers

### PR DESCRIPTION
**Pull request by wavesoft**
---
~⚠️  This PR is based on #1371 and will need a rebase~

---

This PR introduces the `MarathonAppValidators` validator that will provide the high-level marathon validation errors. For this purpose, I am importing the validations from the [`AppDefinition.scala`](https://github.com/mesosphere/marathon/blob/08bc0aed722ad9f3e989a597cb264a994387756f/src/main/scala/mesosphere/marathon/state/AppDefinition.scala) on marathon.

The following functions are so far imported:

- [X] [containsCmdArgsOrContainer](https://github.com/mesosphere/marathon/blob/08bc0aed722ad9f3e989a597cb264a994387756f/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L548)
- [X] [complyWithIpAddressRules](https://github.com/mesosphere/marathon/blob/08bc0aed722ad9f3e989a597cb264a994387756f/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L535)
- [X] [complyWithResidencyRules](https://github.com/mesosphere/marathon/blob/08bc0aed722ad9f3e989a597cb264a994387756f/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L543)
- [ ] [complyWithMigrationAPI](https://github.com/mesosphere/marathon/blob/08bc0aed722ad9f3e989a597cb264a994387756f/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L561)
- [ ] [complyWithSingleInstanceLabelRules](https://github.com/mesosphere/marathon/blob/08bc0aed722ad9f3e989a597cb264a994387756f/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L578)
- [ ] [complyWithReadinessCheckRules](https://github.com/mesosphere/marathon/blob/08bc0aed722ad9f3e989a597cb264a994387756f/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L583)
- [ ] [complyWithUpgradeStrategyRules](https://github.com/mesosphere/marathon/blob/08bc0aed722ad9f3e989a597cb264a994387756f/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L588)
- [ ] [complyWithGpuRules](https://github.com/mesosphere/marathon/blob/08bc0aed722ad9f3e989a597cb264a994387756f/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L593)
- [ ] [haveAtMostOneMesosHealthCheck](https://github.com/mesosphere/marathon/blob/08bc0aed722ad9f3e989a597cb264a994387756f/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L662)

### CODE REVIEW

**Comment by wavesoft** [comment]
I am extending this a bit more, properly adding the marathon error handlers from here: https://github.com/mesosphere/marathon/blob/08bc0aed722ad9f3e989a597cb264a994387756f/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L550

**Comment by orlandohohmeier** [comment]
Do we still need this?

**Comment by wavesoft** [comment]
Open for debate 😄  Good to have or too much effort?

**Comment by orlandohohmeier** [comment]
I don't think that we need all of them... The `containsCmdArgsOrContainer` validator is definitely useful, but I'm not sure if we need the rest. 
Let's check which of the validators will improve the usability with the least effort and implement those.

**Comment by mlunoe** [comment]
We could ship what we have here then. Code looks good to me! 👍

**Comment by wavesoft** [comment]
Ok then I am going to rebase this in order to land what's there already.

**Comment by wavesoft** [comment]
Rebased

**Comment by mlunoe** [comment]
**mesosphere-ci** Retest this please

**Comment by mlunoe** [comment]
**mesosphere-ci** Retest this please

**Comment by jfurrow** [comment]
It's showing an error on a disabled field for me here:


To reproduce, enter a service ID then click on "Add Artifact"

**Comment by jfurrow** [comment]
@mlunoe @wavesoft It seems like the validation is one transaction behind, or something... see the following gif:

**Comment by jfurrow** [comment]
retest this please

**Comment by mlunoe** [comment]
All comments addressed!

**Comment by jfurrow** [comment]
Nice work!

**Pull request merged**
