### PR TITLE
Bump @dcos/mesos-client 0.1.9

### PR DESCRIPTION
**Pull request by nLight**
---
✅  This PR depends on changes that are going to be introduced with #2593. For a list of changes please see: https://github.com/dcos/dcos-ui/compare/orlandohohmeier/fix/adjust-mesos-request-stubs...drozhkov/mesos-client-0.1.9 

---

We thought we've resolved the issue, but that time bundle distribution messed up thus the old version persisted in the `dist` folder. With this bump I reassured that the updates went through.

Closes DCOS-19946

### CODE REVIEW

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Fail consistently on Jenkins
```
navigates to health tab [0fc].Node Health Tab [0fa] Navigate to tab [0fb] navigates to health tab [0fc]
"before each" hook for "filters by health [0fe]".Node Health Tab [0fa] Health Tab [0fd] "before each" hook for "filters by health [0fe]"
navigates to node detail page.Nodes Detail Page Navigate to node detail page navigates to node detail page
shows the contents of the Mesos sandbox.Tasks Table Task row Files tab shows the contents of the Mesos sandbox
"before each" hook for "correctly shows health".Tasks Table For a Service Running task without healthcheck "before each" hook for "correctly shows health"
```

But locally they pass
```
  (Tests Finished)

  - Tests:           341
  - Passes:          331
  - Failures:        0
  - Pending:         10
  - Duration:        14 minutes, 51 seconds
  - Screenshots:     0
  - Video Recorded:  true
  - Cypress Version: 0.19.1
```

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by ahoskins** [comment]
Alfred test this

**Comment by bstavroulakis** [comment]
Note: I made a commit to retrieve the expected data from the mesos master that fixed the tests. 
But I notice that there is a WIP commit from @nLight which probably has to get fixed first and we'll have to override my commit since that should solve the issue that occurred.

**Comment by nLight** [comment]
Rebased & lifted the `hold merge` label

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by nLight** [comment]
Alfred test this

**Comment by orlandohohmeier** [comment]
🚢

**Pull request merged**
