### PR TITLE
DCOS-9162: Add force setting to kill and scale if application is currently locked

### PR DESCRIPTION
**Pull request by Poltergeist**
The behaviour seems a bit off here. But the kill and scale does work now with the force option.

killandscale mov

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
@Poltergeist The behavior inconsistent and feels very strange. Could you please align the `force` behavior with the other actions?

**Comment by Poltergeist** [comment]
I'll do my best.

**Comment by Poltergeist** [comment]
taskkill mov
Updated! I tried to do this in the most non destructive way.

**Comment by mlunoe** [comment]
Also maybe update the text to say something that explains the action a little bit more, when you force it

**Comment by mlunoe** [comment]
Added `Force ` in front of the button text to show the action better

**Pull request merged**
