### PR TITLE
Removing scale button for SINGLE_INSTANCE_APPS

### PR DESCRIPTION
**Pull request by MatApple**
We no longer show the scale button for services containing a label `service.labels.MARATHON_SINGLE_INSTANCE_APP`.

https://mesosphere.atlassian.net/browse/DCOS-9284

### CODE REVIEW

**Comment by MatApple** [comment]
@mesosphere-ci retest this please!

**Comment by rcorral** [comment]
Could we point this to `master`?

**Comment by rcorral** [comment]
Scaling is still available in the collection
img

**Comment by MatApple** [comment]
@rcorral I'd prefer not to point at master because we will have significant conflicts. This file and method deviates significantly from master.

**Comment by MatApple** [comment]
@rcorral good catch with collection view. Updating now

**Comment by MatApple** [comment]
@rcorral fixed your catch.

**Pull request merged**
