### PR TITLE
Style duplicable rows

### PR DESCRIPTION
**Pull request by kennyt**
px

README:

The reason that we don't have the 100% correct icons for these is because we're going to be doing an icon overhaul soon and we'll use the correct ones then :)

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @mlunoe

**Comment by pierlo-upitup** [comment]
The heading of a duplicable row should not be repeated on each row

**Comment by rcorral** [comment]
flicts!

**Comment by kennyt** [comment]
@pierlo-upitup that's going to take some logic on the side of javascript. this PR pretty much just focuses on the CSS (some JS changes in order to pass classnames down)

**Comment by rcorral** [comment]
Merge after conflicts are fixed.

**Comment by kennyt** [comment]
retest this please

**Comment by rcorral** [comment]
retest this please

**Comment by kennyt** [comment]
retest this please

**Comment by Poltergeist** [comment]
Somehow this looks different on my machine. Tested on Chrome and Firefox.

image

**Comment by Poltergeist** [comment]
**mesosphere-ci** retest this please

**Comment by Poltergeist** [comment]
image

**Comment by Poltergeist** [comment]
Fixed it in https://github.com/dcos/dcos-ui/pull/429/commits/19ca5f5dbb20ecdd87942f1bb83d07549262da70

**Comment by Poltergeist** [comment]
Lets 🚢  this. Thanks @kennyt for doing this, your work is appreciated.

**Pull request merged**
