### PR TITLE
[review screen] Healthchecks: Add fallback text to max failures column

### PR DESCRIPTION
**Pull request by Poltergeist**
Now:

image

Before:

image

### CODE REVIEW

**Comment by nLight** [comment]
Shall we also address Command Health Checks?

**Comment by Poltergeist** [comment]
Makes sense I will add it.

**Comment by Poltergeist** [comment]
run unit tests

**Comment by Poltergeist** [comment]
Added the same thing for Command health checks

**Comment by Poltergeist** [comment]
**mesosphere** run unit tests

**Comment by Poltergeist** [comment]
run unit tests

**Comment by nLight** [comment]
LGTM! 💯 ✨

**Pull request merged**
