### PR TITLE
[Sidebar: 4 of 4] Expanding/collapsing sidebar sections

### PR DESCRIPTION
**Pull request by jfurrow**
This PR includes commits from ~~#1412, #1417~~, and ~~#1419~~. It introduces the expanding/collapsing sidebar sections. 🔽 🔼

### CODE REVIEW

**Comment by jfurrow** [comment]
Adding `hold merge` until @ashenden and team decides how some of the subtleties of this should work.

**Comment by ashenden** [comment]
I've updated the sidebar styling to match what we aim to ship with.  There are however 2 open issues I don't know how to fix and need @jfurrow or someone else to resolve:

- [ ] When a `.sidebar-menu-item` item has a child element selected in it's submenu (https://cl.ly/110O1C200O0j) I should be unable to collapse it.
- [ ] When any `.sidebar-menu-item` is open, it should have the class `.open` added to it, not just when it has a child element selected.

**Comment by jfurrow** [comment]
@ashenden All of those items have been added, I'll remove the `hold merge` label.

**Comment by wavesoft** [comment]
Looks good! ✨ :shipit:

**Pull request merged**
