### PR TITLE
[1.11 Backport] feat(PodEndpoints): Add vip input to virtual networks

### PR DESCRIPTION
**Pull request by Poltergeist**
Add the vip port input field to the virtual networks of Multi container services.

image

Closes DCOS_OSS-1553

### CODE REVIEW

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
@DanielMSchmidt  please give it another shot

**Comment by MatApple** [comment]
We will merge this and dismiss your review @nLight seeing it is a call for also adding the fix to master. I'd prefer not to hold up a 1.11 blocker - @Poltergeist can you please add a PR against master?

**Comment by nLight** [comment]
@MatApple it has been merged https://github.com/dcos/dcos-ui/pull/2735 😊

**Pull request merged**
