### PR TITLE
DCOS_OSS-4957: clarify restart configuration

### PR DESCRIPTION
**Pull request by natmegs**
Clarify layout of restart configuration in jobs form.

Closes DCOS_OSS-4957.

## Testing

See [designs](https://mesosphere.invisionapp.com/share/Y6Q8EFKBA3G#/screens/345675728)
- Open Jobs form
- Check that tab names match designs (it is known that the tab labels will wrap onto a new line on smaller screen sizes. Design is aware)
- Go to Run Configuration tab
- Under Restart Policy heading, there should be no "Restart Job" label above radio buttons, and radio button labels should be "Never/On Failure" instead of "Yes/No". "Retry Time" label has changed to "Keep Trying Time"
- If "On Failure" is not selected for Restart Policy, Keep Trying Time input should be disabled (it's ok if the activeDeadlineSeconds is not removed from the JSON)

## Trade-offs

N/A

## Dependencies

N/A

## Screenshots

Before
Screen Shot 2019-04-03 at 8 47 46 AM

After
Screen Shot 2019-04-04 at 11 41 27 AM

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
I still see some differences between design and actual form. For example:
Design:
Screenshot from 2019-04-04 11-11-15
Screenshot from 2019-04-04 11-11-22
Screenshot from 2019-04-04 11-11-47

Actual form:
Screenshot from 2019-04-04 11-12-47
Screenshot from 2019-04-04 11-12-54
Screenshot from 2019-04-04 11-11-55

Is changing them out of scope here and if yes what is the scope here?

**Comment by GeorgiSTodorov** [comment]
I amended a commit that should fix the failing integration test. I hope you don't mind.

**Comment by natmegs** [comment]
@GeorgiSTodorov default values are being handled separately (here's the [JIRA](https://jira.mesosphere.com/browse/DCOS_OSS-4955) and PR #3774 )

**Comment by GeorgiSTodorov** [comment]
Is there a reason why this doesn't follow the design?
Design:
Screenshot from 2019-04-05 11-34-15
Here:
Screenshot from 2019-04-05 11-34-23

Also, in the design we have to click on the text to enable the restart policy checkbox, while here clicking on the label also changes it.
Design:
Screenshot from 2019-04-05 11-36-32
Here:
Peek 2019-04-05 11-36

**Comment by natmegs** [comment]
@GeorgiSTodorov I've asked for clarification from design on what the help text should be. The default is handled in another ticket. As for where to click for radios - it's not my understanding that invision is meant to replicate our exact click boundaries or interactions 🙂 This is the same behaviour in all the forms that use this radio input, like the services form.

**Pull request merged**
