### PR TITLE
Revert "[Backports 1.11] Fabs/1.11/fix/dcos 21784 mesos stream microtask"

### PR DESCRIPTION
**Pull request by orlandohohmeier**
Reverts dcos/dcos-ui#2858 as the merged fix is not sufficient in preventing errors form propagating so that errors in MESOS_STATE_CHANGE handlers could still break the stream.

### CODE REVIEW

**Comment by nLight** [comment]
run integration tests

**Comment by nLight** [comment]
run integration test

**Comment by nLight** [comment]
run integration tests

**Comment by juliangieseke** [comment]
creating a new PR…

**Pull request closed without merging**
