### PR TITLE
DCOS-48883: render icons from ui-kit (Secrets table enabler)

### PR DESCRIPTION
**Pull request by mperrotti**
This became a subtask of replacing the Secrets table because we need the ui-kit icon sprites in the document to properly render the checkboxes in the CheckboxTable component

Closes DCOS-48883

## Testing
Click around the app and see if any icons are missing, are the wrong color, or look broken in some other way.

## Trade-offs
None

## Dependencies
plugins-private PR: https://github.com/mesosphere/dcos-ui-plugins-private/pull/938

### CODE REVIEW

**Comment by pierrebeitz** [comment]
@mperrotti 	are there easy-to-reproduce steps that make the diff smaller? The diff is too big for me to find slips. Or is just poking around and trying to spot stuff "good enough" in terms of review quality?

**Comment by mperrotti** [comment]
Thanks for the suggestion @pierrebeitz, I wasn't sure how to split this up either.
Sadly, I don't think splitting out the `InfoTooltipIcon` changes into it's own commit will make this PR that much easier to review. Though I'd be happy to do that if you think it will make things easier :)

I think poking around and trying to spot issues is "good enough" for this PR.

**Comment by GeorgiSTodorov** [comment]
Package-lock conflict.

**Comment by mperrotti** [comment]
@GeorgiSTodorov - I fixed the first two issues. The secrets issue fix is in the plugins-private PR: https://github.com/mesosphere/dcos-ui-plugins-private/pull/938

I couldn't reproduce the issue with the CLI modal - maybe you can show me in a screenshare tomorrow

**Comment by mperrotti** [comment]
@GeorgiSTodorov - I think if the icon is different, it was made different intentionally. I don't think we should change it

**Comment by GeorgiSTodorov** [comment]
File conflict.

**Comment by GeorgiSTodorov** [comment]
@natmegs @Poltergeist , please re-review.

**Pull request merged**
