### PR TITLE
[spike] DCOS-46611: [1.12] Cannot read property 'stateTypes' of undefined

### PR DESCRIPTION
**Pull request by GeorgiSTodorov**
Add a check to prevent trying to read a property from something that
is not defined.

Closes https://jira.mesosphere.com/browse/DCOS-46611

## Testing
Not sure how to test this.

## Trade-offs
None.

## Dependencies
None.

## Screenshots
None.

### CODE REVIEW

**Comment by nLight** [comment]
@GeorgiSTodorov do we know what state is missing? We shouldn't get undefined there...

**Comment by GeorgiSTodorov** [comment]
@nLight , it's a bug from sentry that first appeared about 5 months ago.

**Comment by nLight** [comment]
@GeorgiSTodorov I know, just wonder if we could trace code and deduct what those sates are and if backends started giving other states

**Comment by GeorgiSTodorov** [comment]
@nLight , I plan on investigating this.

**Pull request merged**
