### PR TITLE
ci(tests): fix integration tests script

### PR DESCRIPTION
**Pull request by juliangieseke**
removed timeout, didnt help on ci but broke local setups on mac :( 

## Testing

ci has to be green and `npm run integration-tests` on you machine also should work again…

### CODE REVIEW

**Comment by nLight** [comment]
timestamping ci fixes is so 😭

**Comment by nLight** [comment]
Maybe adding time with seconds to those timestamps tho! :trollface:

**Comment by nLight** [comment]
```
/cypress/pages/nodes/NodesPage-cy.js-1/screenshots/Nodes Page -- Nodes grid -- On nodes grid -- can switch resources
```

Fails locally

**Comment by juliangieseke** [comment]
Ping @DanielMSchmidt @Poltergeist @mperrotti 🙇

**Comment by mperrotti** [comment]
I'm seeing the same local failure Dmitry mentioned. Here's a screenshot:
nodesgrid_testfail

**Comment by juliangieseke** [comment]
weird, this PR doesnt change anything on our code - and CI is green…

we had some issues before with cypress on mac, @nLight they are green with cypress 3, correct?

**Comment by nLight** [comment]
@juliangieseke I bet it's failing locally with 3.1.0 as well

**Comment by juliangieseke** [comment]
checking…

**Comment by juliangieseke** [comment]
master is green 🤔 CI also merges master before running tests, might be that it was broken when this branch was branched and if you check it locally, you havend the latest master -> `git rebase` should fix it

**Comment by tnguyen0** [comment]
Same problem here. Rebased with latest master. Seems it doesn't have the latest (missing header bar as well):
nodes page -- nodes grid -- on nodes grid -- can switch resources

**Comment by juliangieseke** [comment]
ping @DanielMSchmidt @tnguyen0 @Poltergeist @mperrotti 🙇

**Comment by mperrotti** [comment]
Still getting the same failure, even after pulling from remote this morning. I'm happy to get on a video chat and look through it together to diagnose the issue @juliangieseke

**Pull request merged**
