### PR TITLE
DCOS-49714: no content-based column width sizing on nodes table

### PR DESCRIPTION
**Pull request by mperrotti**
## Testing
Navigate to the Nodes tab and try hovering table rows and scrolling the table

## Trade-offs
Columns don't automatically size the their widest cell content

## ⚠️Dependencies
https://github.com/dcos-labs/ui-kit/pull/311

## Screenshots
Before:
NodesTable_before

After:
NodesTable_after

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
Hold merge until ui-kit PR is merged.

**Comment by GeorgiSTodorov** [comment]
For testing this, I recommend using the fixtures from this PR - https://github.com/dcos/dcos-ui/pull/3417 or SOAK.

**Comment by juliangieseke** [comment]
integrated ui kit release, removing `hold-merge`

**Comment by GeorgiSTodorov** [comment]
```
+ npm --unsafe-perm ci

npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.

npm ERR! 

npm ERR! 

npm ERR! Invalid: lock file's @dcos/ui-kit@1.35.0 does not satisfy @dcos/ui-kit@2.0.0
```
Package-lock needs to be updated.

**Comment by juliangieseke** [comment]
seems like @mperrotti force pushed again 🤔
fixed & updated ui-kit to 2.0.1 👍

**Comment by juliangieseke** [comment]
@GeorgiSTodorov is this related to this PR? 🤔I can imagine it was like that before. (still something we should fix, but not in this PR if its unrelated)

**Comment by GeorgiSTodorov** [comment]
@juliangieseke , it's also happening on master.

**Comment by juliangieseke** [comment]
@GeorgiSTodorov can you please create a JIRA? thanks! 🙇

**Comment by GeorgiSTodorov** [comment]
https://jira.mesosphere.com/browse/DCOS-50412

**Pull request merged**
