### PR TITLE
DCOS-13243: Adjust the apply configuration operation

### PR DESCRIPTION
**Pull request by orlandohohmeier**
---
~~⚠️  _This branch will fail until #1798 is merged._~~

---

Change the apply service configuration handler to clean the JSON before sending it back to Marathon to avoid validation errors.

Fixes DCOS-13243

### CODE REVIEW

**Comment by rcorral** [comment]
@orlandohohmeier could you rebase?

**Comment by orlandohohmeier** [comment]
♻️ ⚾️ 😄

**Comment by wavesoft** [comment]
Looks good 👍  💯

**Comment by jfurrow** [comment]
run integration tests

**Comment by mlunoe** [comment]
⛵️

**Comment by mlunoe** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
run integration tests

**Comment by jfurrow** [comment]
run integration tests

**Comment by orlandohohmeier** [comment]
run integration tests

**Comment by rcorral** [comment]
Merged as Integration tests are not meant to pass in 1.8.

**Pull request merged**
