### PR TITLE
[1.10] DCOS-18055: Improvements for deployment behavior in Catalog

### PR DESCRIPTION
**Pull request by MatApple**
---
⚠️  _This branch depends on changes that are going be introduced with #2413. For a list of changes please see: https://github.com/dcos/dcos-ui/compare/orlandohohmeier/1.10/chore/remove-beta-opt-in...mat/review-and-run_ 

---

On **catalog > package detail** page.
- Consolidates "CONFIGURE" and "DEPLOY" buttons into a single "REVIEW & RUN" button.
- Opens review screen first with options to edit configuration or run service

**To better understand these changes, walk through the commits from top to bottom and read the commit messages.**

**To test**:
- Run Service without editing configuration. Attempt to run service again with same name and witness failure failure.
- Edit configuration for a package to change name and run service. Ensure service is then running.
- Try to run artifactory package without editing. Should fail, show option to edit config. Click option to edit and witness errors in the form.

**Checklist**
- [ ] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
Could you please move the beta opt in into a separate PR?

**Comment by orlandohohmeier** [comment]
The deployment fails due to wrong value types when hit "RUN SERVICE" without adjusting the configuration.

**Comment by orlandohohmeier** [comment]
@MatApple I've fixed the install issue and created a separate PR for the beta-opt-in clean up.

**Comment by MatApple** [comment]
Thanks @orlandohohmeier 👍

**Comment by nLight** [comment]
Alfred 🔥 retest 🍏 this por favor

**Comment by nLight** [comment]
Trying to open `spark-history` page I get an error :(

`SchemUtil#schemaToMultipleDefinition`

screen shot 2017-09-11 at 12 12 47

**Pull request merged**
