### PR TITLE
DCOS-17250: Do/Don't Component for Design System

### PR DESCRIPTION
**Pull request by tnguyen0**
~⚠️ This PR depends on #2349~
---
A Do/Don't component is a block that informs the user on how to/how not to use UI components. It consists of a title ("Do" or "Don't"), a description for the user and the UI component in question. The children of the component are the UI components to show. There is also a DoDontPanel component that wraps the blocks in a grid.

Example use:
```
<DoDontPanel>
  <Do description="...">
    <button className="button button-primary" type="button">
      Primary Button
    </button>
  </Do>
  <Dont description="...">
    <button className="button button-primary" type="button">
      Primary Button
    </button>
  </Dont>
</DoDontPanel>
```

Closes DCOS-17250

To test:
* See Overview Tab for Checkboxes component

**Checklist**
- [ ] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by nLight** [comment]
Alfred retest this please

**Comment by leemunroe** [comment]
@tnguyen0 Can you include an example of what this looks like in the PR description? Both a screenshot and what the HTML output would be?

**Comment by orlandohohmeier** [comment]
I'd like us to build a set of components that one compose as illustrated below:

```html
<Section>
    <Headline>Usage</Headline>
    
    Every button that confirms or cancels and action should have the `button-primary` class.
    
    <Code language="jsx">
        <button className="button button-primary" type="button">
            Confirm Button
        </button>
    </Code>
    
    <Code language="jsx">
        <button className="button button-primary button-danger" type="button">
            Cancle Button
        </button>
    </Code>
    
    <Hint>    
        You the  `button-primary` class also for submit "buttons"
        
        <Code language="jsx">
            <input type="submit" value="Submit Button" className="button button-primary">
        </Code>
    </Hint>
    
    <Warning>    
        Don't use the `button-primary"`  for simple links.
        
        <Code language="jsx">
            <Link className="button primary-button">
                Simple Link
            </Link>    
        </Code>
    </Warning>
</Section>
```

**Comment by Fabs** [comment]
On the Lean spirit of reducing waste, I am closing this after a chat with team, because it looks to me it won't ever get merged.

**Comment by leemunroe** [comment]
💔

**Comment by Fabs** [comment]
I believe that the new UI dreamers could pick up on this work, @weblancaster and @Poltergeist

**Pull request closed without merging**
