### PR TITLE
Disable SDK Actions in the UI

### PR DESCRIPTION
**Pull request by rcorral**
This is the feature branch that disables all actions in the UI for SDK services.

### CODE REVIEW

**Comment by jfurrow** [comment]
All of the SDK-related PRs have been tested and merged into this feature branch. Let's :shipit:!

**Comment by jfurrow** [comment]
This works great still. Let's :ship:

**Comment by weblancaster** [comment]
Seems like everything is working fine but I can't see the menu under services. is that expected? @jfurrow @MatApple 

Other than that looks good.

screen shot 2017-05-10 at 11 49 23 am

**Comment by MatApple** [comment]
@weblancaster - yes that is the expected behavior! Thanks for checking :)

**Pull request merged**
