### PR TITLE
Extract method from Tree for decoupling

### PR DESCRIPTION
**Pull request by pierlo-upitup**
This is a follow-up to #330 

While not being an exhaustive solution, it introduces a slightly more meaningful separation of concerns between Tree and ServiceTree.

### CODE REVIEW

**Comment by mesosphere-web** [comment]
Reviewer: @mlunoe

**Comment by pierlo-upitup** [comment]
cc @orlandohohmeier

**Comment by orlandohohmeier** [comment]
🙀 There weren't any tests?! Not in the scope of this PR but let's make sure the next iteration of this method is proplerly tested.

**Comment by pierlo-upitup** [comment]
Scary right??

**Comment by aldipower** [comment]
Just my mustard.
There are very well programmed integration tests for that!

**Comment by aldipower** [comment]
LGTM. Thx!

**Comment by pierlo-upitup** [comment]
retest this please

**Comment by aldipower** [comment]
ok ;)

**Pull request merged**
