### PR TITLE
Fix force action and error message handling for modals

### PR DESCRIPTION
**Pull request by MatApple**
Fixing force action and error handling on modals.

### CODE REVIEW

**Comment by rcorral** [comment]
Thanks for this fix @MatApple - I pushed a commit too.

**Comment by MatApple** [comment]
Thanks for the extra cleanup @rcorral.

**Comment by rcorral** [comment]
@MatApple for some reason the force delete doesn't work.
Could you check it out?
gif

**Comment by MatApple** [comment]
Fixed @rcorral - good find!

**Pull request merged**
