### PR TITLE
fix(PodStorageConfigSection): fix variable reference

### PR DESCRIPTION
**Pull request by Poltergeist**
This commit fixes a variable reference which lead to have multiple lines in the volume mount table
with the same values.
Before:
image

After:
image

To test:

```JSON
{
  "id": "/host-volume",
  "volumes": [
    {
      "name": "etc",
      "host": "/etc"
    }
  ],
  "scaling": {
    "kind": "fixed",
    "instances": 1
  },
  "scheduling": {
    "upgrade": {
      "minimumHealthCapacity": 0,
      "maximumOverCapacity": 0
    }
  },
  "containers": [
    {
      "name": "container1",
      "exec": {
        "command": {
          "shell": "sleep 5000"
        }
      },
      "resources": {
        "cpus": 0.1,
        "mem": 128,
        "disk": 0,
        "gpus": 0
      },
      "image": {
        "id": "alpine",
        "kind": "DOCKER",
        "forcePull": false
      },
      "volumeMounts": [
        {
          "name": "etc",
          "mountPath": "/mnt/etc1",
          "readOnly": true
        }
      ],
      "lifecycle": {
        "killGracePeriodSeconds": 60
      }
    },
    {
      "name": "container2",
      "exec": {
        "command": {
          "shell": "sleep 5000"
        }
      },
      "resources": {
        "cpus": 0.1,
        "mem": 128,
        "disk": 0,
        "gpus": 0
      },
      "image": {
        "id": "alpine",
        "kind": "DOCKER",
        "forcePull": false
      },
      "volumeMounts": [
        {
          "name": "etc",
          "mountPath": "/mnt/etc2",
          "readOnly": true
        }
      ],
      "lifecycle": {
        "killGracePeriodSeconds": 60
      }
    }
  ]
}
```
Go to the create multiple container service form and open the JSON Editor and add the previously added JSON.
Then hit review and run if everything is okay the table at the bottom should show two different volume mounts.

Closes DCOS-19219

### CODE REVIEW

**Comment by Poltergeist** [comment]
:trollface: omg pasted the wrong stuff. Will add the test tomorrow.

**Comment by Poltergeist** [comment]
@nLight Added a integration test for the behaviour. Also updated the description images to reflect the actual change.

**Comment by nLight** [comment]
run integration tests

**Comment by Poltergeist** [comment]
run integration tests

**Comment by nLight** [comment]
run integration tests

**Pull request merged**
