### PR TITLE
Comment out networking section

### PR DESCRIPTION
**Pull request by jfurrow**

### CODE REVIEW

**Comment by rcorral** [comment]
ship-it

**Comment by rcorral** [comment]
@mesosphere-mergebot ship-it

**Comment by rcorral** [comment]
👿

**Comment by orsenthil** [comment]
It looks like it can understand only one command.  Let's enable others.  :-)

```
This repo has @mesosphere-mergebot integration. You can interact with the following commands.

@mesosphere-mergebot integrate-it
```

**Pull request merged**
