### PR TITLE
DCOS-14911: Universe package grid update

### PR DESCRIPTION
**Pull request by jfurrow**
This PR...
* Adjusts the styling on the packages grid
* Adjusts the styling on the package detail view
* Renames "Selected" to "Certified"
* Changes the packages table into a second grid of packages (now called "Community")
* Adds `.badge--primary`
* Removes icon size overrides and updates the icon size in the service create modal
---

---

**Checklist**
- [x] Did you add a JIRA issue in a commit message or as part of the branch name?
- [ ] Did you add new unit tests?
- [ ] Did you add new integration tests?
- [ ] If this is a regression, did you write a test to catch this in the future?

### CODE REVIEW

**Comment by Poltergeist** [comment]
run integration tests

**Comment by Poltergeist** [comment]
run unit tests

**Comment by Poltergeist** [comment]
run unit tests

**Comment by jfurrow** [comment]
run unit tests

**Comment by jfurrow** [comment]
run unit tests

**Comment by Poltergeist** [comment]
run integration tests

**Comment by Poltergeist** [comment]
LGTM 💯 👍  :shipit:

**Comment by rcorral** [comment]
This looks good to me, please rebase so we can merge!

**Pull request merged**
