### PR TITLE
DCOS-48834 FBS Single Container service support

### PR DESCRIPTION
**Pull request by TattdCodeMonkey**
Changes in this PR are in support of features in plugins. The changes as presented should just enable other feature work without breaking any existing functionality.

1. Adding Mount to `VolumeFormSection` for info box when using file-based secrets
2. Migrated `Transaction` & `TransactionTypes` to TS
3. Extracted messages for file-based secrets support in single-container services

### CODE REVIEW

**Comment by brandonc** [comment]
Can you help us understand the goal and other context of this PR?

**Comment by TattdCodeMonkey** [comment]
force-pushed rebase and catalog updates for changes in plugins

**Comment by TattdCodeMonkey** [comment]
@natmegs from the matching plugins-private PR

**Comment by GeorgiSTodorov** [comment]
Why was this merged before the other PR?

**Pull request merged**
