### PR TITLE
DCOS-40646: add base tech version parsing to services table 

### PR DESCRIPTION
**Pull request by juliangieseke**
Closes [DCOS-40646](https://jira.mesosphere.com/browse/DCOS-40646)

## Testing

check various frameworks to see that version is displayed correctly (parsed in table, full in tooltip)

## Trade-offs

Please see the linkes JIRA Issue for more details. I parsed all packages in the current universe and also shared the result in JIRA

## Dependencies

None

## Screenshots

Before:
screen shot 2018-08-21 at 11 44 32

After:
screen shot 2018-08-21 at 11 43 57

### CODE REVIEW

**Comment by juliangieseke** [comment]
Ping @leemunroe @AmrAbdelrazik

**Comment by juliangieseke** [comment]
yeah… what kind of struct is it? my check was `service instanceof Framework` 🤔

**Comment by DanielMSchmidt** [comment]
🤷‍♂️ I "just" clicked on kibana and kibana-beta and deployed them

**Comment by juliangieseke** [comment]
updated JIRA… It is a bug that is already on master, not directly related to this PR. I think we can merge this as-is, but need to figure out how to solve the whole situation.

**Pull request merged**
